// Class: Read2HDMaVWjets_2017_BDT_42Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_22Var
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::2HDMaVWjets_2017_BDT_42Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_22Var
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : svanputt
Date           : Wed Apr 22 22:13:48 2020
Host           : Linux vocms0315.cern.ch 2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 09:23:05 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /scratch/40001731.cream02.iihe.ac.be/42Trees
Training events: 437017
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "True" [Print method-specific help message]
NTrees: "42" [Number of trees in the forest]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
SeparationType: "giniindex" [Separation criterion for node splitting]
PruneMethod: "costcomplexity" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "1.200000e+01" [Pruning strength]
# Default:
VerbosityLevel: "Verbose" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "5" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 22
mtw1                          mtw1                          mtw1                          mtw1                                                            'F'    [0,1316.13671875]
MHlnjj_deta_ljjVmet           MHlnjj_deta_ljjVmet           MHlnjj_deta_ljjVmet           MHlnjj_deta_ljjVmet                                             'F'    [1.84355883448e-06,7.9948887825]
MHlnjj_dphi_ljjVmet           MHlnjj_dphi_ljjVmet           MHlnjj_dphi_ljjVmet           MHlnjj_dphi_ljjVmet                                             'F'    [1.16606834126e-05,3.14159178734]
MHlnjj_deta_jjVl              MHlnjj_deta_jjVl              MHlnjj_deta_jjVl              MHlnjj_deta_jjVl                                                'F'    [4.67996233056e-06,10.0481100082]
MHlnjj_dphi_jjVl              MHlnjj_dphi_jjVl              MHlnjj_dphi_jjVl              MHlnjj_dphi_jjVl                                                'F'    [4.14871465182e-05,3.14158701897]
MHlnjj_dphi_lVmet             MHlnjj_dphi_lVmet             MHlnjj_dphi_lVmet             MHlnjj_dphi_lVmet                                               'F'    [0,3.14158368111]
MHlnjj_deta_lVmet             MHlnjj_deta_lVmet             MHlnjj_deta_lVmet             MHlnjj_deta_lVmet                                               'F'    [1.0596588254e-05,2.49951171875]
PuppiMET_pt                   PuppiMET_pt                   PuppiMET_pt                   PuppiMET_pt                                                     'F'    [50.0001335144,1523.65405273]
MHlnjj_pt_ljj                 MHlnjj_pt_ljj                 MHlnjj_pt_ljj                 MHlnjj_pt_ljj                                                   'F'    [0.11474018544,1025.22814941]
MHlnjj_m_lmetjj               MHlnjj_m_lmetjj               MHlnjj_m_lmetjj               MHlnjj_m_lmetjj                                                 'F'    [105.564781189,2536.88208008]
MHlnjj_PTljj_D_PTmet          MHlnjj_PTljj_D_PTmet          MHlnjj_PTljj_D_PTmet          MHlnjj_PTljj_D_PTmet                                            'F'    [0.00212299986742,12.7120838165]
MHlnjj_PTljj_D_Mlmetjj        MHlnjj_PTljj_D_Mlmetjj        MHlnjj_PTljj_D_Mlmetjj        MHlnjj_PTljj_D_Mlmetjj                                          'F'    [0.000469836377306,3.65420365334]
MHlnjj_MINPTlj_D_PTmet        MHlnjj_MINPTlj_D_PTmet        MHlnjj_MINPTlj_D_PTmet        MHlnjj_MINPTlj_D_PTmet                                          'F'    [0.0209071692079,3.49794340134]
MHlnjj_MINPTlj_D_Mlmetjj      MHlnjj_MINPTlj_D_Mlmetjj      MHlnjj_MINPTlj_D_Mlmetjj      MHlnjj_MINPTlj_D_Mlmetjj                                        'F'    [0.0134515520185,0.638022661209]
MHlnjj_dphi_jVj               MHlnjj_dphi_jVj               MHlnjj_dphi_jVj               MHlnjj_dphi_jVj                                                 'F'    [0,3.1415913105]
MHlnjj_deta_jVj               MHlnjj_deta_jVj               MHlnjj_deta_jVj               MHlnjj_deta_jVj                                                 'F'    [0,2.59130859375]
MHlnjj_m_jj                   MHlnjj_m_jj                   MHlnjj_m_jj                   MHlnjj_m_jj                                                     'F'    [65.0002822876,104.999908447]
MHlnjj_m_ljj                  MHlnjj_m_ljj                  MHlnjj_m_ljj                  MHlnjj_m_ljj                                                    'F'    [74.5745773315,2237.96362305]
MHlnjj_MAXPTlj_D_PTmet        MHlnjj_MAXPTlj_D_PTmet        MHlnjj_MAXPTlj_D_PTmet        MHlnjj_MAXPTlj_D_PTmet                                          'F'    [0.0414094999433,13.7160482407]
MHlnjj_MAXPTlj_D_Mlmetjj      MHlnjj_MAXPTlj_D_Mlmetjj      MHlnjj_MAXPTlj_D_Mlmetjj      MHlnjj_MAXPTlj_D_Mlmetjj                                        'F'    [0.062865190208,2.91850996017]
MHlnjj_MTljj_D_PTmet          MHlnjj_MTljj_D_PTmet          MHlnjj_MTljj_D_PTmet          MHlnjj_MTljj_D_PTmet                                            'F'    [0.0818054527044,20.0676307678]
MHlnjj_MTljj_D_Mlmetjj        MHlnjj_MTljj_D_Mlmetjj        MHlnjj_MTljj_D_Mlmetjj        MHlnjj_MTljj_D_Mlmetjj                                          'F'    [0.059488967061,0.938192307949]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new 2HDMaVWjets_2017_BDT_42Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_22VarNode
   
#ifndef 2HDMaVWjets_2017_BDT_42Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_22VarNode__def
#define 2HDMaVWjets_2017_BDT_42Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_22VarNode__def
   
class 2HDMaVWjets_2017_BDT_42Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_22VarNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   2HDMaVWjets_2017_BDT_42Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_22VarNode ( 2HDMaVWjets_2017_BDT_42Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_22VarNode* left,2HDMaVWjets_2017_BDT_42Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_22VarNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~2HDMaVWjets_2017_BDT_42Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_22VarNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   2HDMaVWjets_2017_BDT_42Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_22VarNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   2HDMaVWjets_2017_BDT_42Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_22VarNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   2HDMaVWjets_2017_BDT_42Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_22VarNode*   fLeft;     // pointer to the left daughter node
   2HDMaVWjets_2017_BDT_42Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_22VarNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   2HDMaVWjets_2017_BDT_42Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_22VarNode::~2HDMaVWjets_2017_BDT_42Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_22VarNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool 2HDMaVWjets_2017_BDT_42Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_22VarNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool 2HDMaVWjets_2017_BDT_42Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_22VarNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class Read2HDMaVWjets_2017_BDT_42Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_22Var : public IClassifierReader {

 public:

   // constructor
   Read2HDMaVWjets_2017_BDT_42Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_22Var( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "Read2HDMaVWjets_2017_BDT_42Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_22Var" ),
        fNvars( 22 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "mtw1", "MHlnjj_deta_ljjVmet", "MHlnjj_dphi_ljjVmet", "MHlnjj_deta_jjVl", "MHlnjj_dphi_jjVl", "MHlnjj_dphi_lVmet", "MHlnjj_deta_lVmet", "PuppiMET_pt", "MHlnjj_pt_ljj", "MHlnjj_m_lmetjj", "MHlnjj_PTljj_D_PTmet", "MHlnjj_PTljj_D_Mlmetjj", "MHlnjj_MINPTlj_D_PTmet", "MHlnjj_MINPTlj_D_Mlmetjj", "MHlnjj_dphi_jVj", "MHlnjj_deta_jVj", "MHlnjj_m_jj", "MHlnjj_m_ljj", "MHlnjj_MAXPTlj_D_PTmet", "MHlnjj_MAXPTlj_D_Mlmetjj", "MHlnjj_MTljj_D_PTmet", "MHlnjj_MTljj_D_Mlmetjj" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;
      fVmin[17] = 0;
      fVmax[17] = 0;
      fVmin[18] = 0;
      fVmax[18] = 0;
      fVmin[19] = 0;
      fVmax[19] = 0;
      fVmin[20] = 0;
      fVmax[20] = 0;
      fVmin[21] = 0;
      fVmax[21] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';
      fType[20] = 'F';
      fType[21] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~Read2HDMaVWjets_2017_BDT_42Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_22Var() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[22];
   double fVmax[22];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[22];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<2HDMaVWjets_2017_BDT_42Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_22VarNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double Read2HDMaVWjets_2017_BDT_42Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_22Var::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      2HDMaVWjets_2017_BDT_42Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_22VarNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(2HDMaVWjets_2017_BDT_42Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_22VarNode*)current->GetRight();
         else current=(2HDMaVWjets_2017_BDT_42Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_22VarNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void Read2HDMaVWjets_2017_BDT_42Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_22Var::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.705028462144668);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.917479,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.63733,-99) , 
NN(
0, 
0, 
-1, 1.93991, 1, -1, 0.229023,-99) , 
0, 119.605, 0, 0, 0.297401,-99) , 
20, 1.03351, 1, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.472505);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.91393, 1, 1, 0.728599,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504945,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.278822,-99) , 
11, 0.247511, 0, 0, 0.39332,-99) , 
20, 1.35074, 1, 0, 0.607189,-99) , 
NN(
0, 
0, 
-1, 1.54732, 1, -1, 0.197415,-99) , 
20, 1.98522, 1, 0, 0.487954,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.362555);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.644153,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553822,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.321701,-99) , 
17, 133.202, 1, 0, 0.426422,-99) , 
NN(
0, 
0, 
-1, 96.7818, 0, -1, 0.225772,-99) , 
17, 177.173, 1, 0, 0.34147,-99) , 
7, 120.174, 0, 0, 0.432901,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.319418);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.659158,-99) , 
NN(
0, 
0, 
-1, 1.54732, 1, -1, 0.346974,-99) , 
0, 125.346, 0, 0, 0.421529,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.279897);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.674451,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512253,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.282321,-99) , 
3, 1.26583, 1, 0, 0.416058,-99) , 
20, 1.2265, 1, 0, 0.561869,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538543,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.397986,-99) , 
0, 42.5653, 1, 0, 0.429921,-99) , 
NN(
0, 
0, 
-1, 195.168, 1, -1, 0.205882,-99) , 
6, 1.54732, 1, 0, 0.380954,-99) , 
4, 1.64561, 1, 0, 0.459174,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.233211);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.671228,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434407,-99) , 
5, 1.04719, 0, 0, 0.579485,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518607,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39218,-99) , 
6, 0.515715, 1, 0, 0.444163,-99) , 
8, 97.7446, 0, 0, 0.49681,-99) , 
NN(
0, 
0, 
-1, 0.361167, 1, -1, 0.312928,-99) , 
6, 1.54732, 1, 0, 0.456478,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.159886);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579741,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501581,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.383114,-99) , 
7, 74.8413, 0, 0, 0.441576,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.240599,-99) , 
6, 1.90439, 1, 0, 0.422306,-99) , 
20, 1.03351, 1, 0, 0.462877,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.243267);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.656008,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443277,-99) , 
20, 1.53606, 1, 0, 0.607491,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530347,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.329916,-99) , 
13, 0.15125, 0, 0, 0.422024,-99) , 
0, 96.6568, 0, 0, 0.508271,-99) , 
NN(
0, 
0, 
-1, 1.90439, 1, -1, 0.37992,-99) , 
17, 177.593, 1, 0, 0.451099,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.165867);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555988,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.657478,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429164,-99) , 
6, 1.30927, 0, 0, 0.515389,-99) , 
NN(
0, 
0, 
-1, 2.30172, 1, -1, 0.410583,-99) , 
0, 56.7763, 1, 0, 0.432426,-99) , 
7, 120.174, 0, 0, 0.467013,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.189396);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571474,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.677975,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484575,-99) , 
4, 2.24402, 0, 0, 0.543541,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.599225,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.386515,-99) , 
0, 107.439, 0, 0, 0.423208,-99) , 
10, 1.2126, 0, 0, 0.453167,-99) , 
0, 125.346, 0, 0, 0.478357,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.124144);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533981,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39325,-99) , 
3, 2.45639, 1, 0, 0.515621,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.351648,-99) , 
21, 0.645291, 1, 0, 0.503174,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.3399,-99) , 
6, 1.90439, 1, 0, 0.487668,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.11802);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565501,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510619,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431536,-99) , 
17, 163.115, 1, 0, 0.468041,-99) , 
5, 2.69279, 0, 0, 0.488751,-99) , 
NN(
0, 
0, 
-1, 2.09442, 1, -1, 0.396303,-99) , 
6, 1.54732, 1, 0, 0.469362,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.174682);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582755,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458324,-99) , 
19, 0.342561, 1, 0, 0.550089,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.390084,-99) , 
16, 93.5715, 1, 0, 0.523084,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560652,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419869,-99) , 
3, 0.956968, 1, 0, 0.48601,-99) , 
NN(
0, 
0, 
-1, 0.55789, 1, -1, 0.385774,-99) , 
2, 2.69281, 1, 0, 0.43901,-99) , 
8, 97.7446, 0, 0, 0.470295,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.106557);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557424,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523204,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448441,-99) , 
4, 2.3936, 0, 0, 0.479336,-99) , 
NN(
0, 
0, 
-1, 1.49599, 0, -1, 0.387224,-99) , 
6, 1.54732, 1, 0, 0.463624,-99) , 
21, 0.310547, 1, 0, 0.478126,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.122472);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.602146,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476747,-99) , 
12, 0.394491, 1, 0, 0.521188,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522811,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428634,-99) , 
10, 1.06814, 0, 0, 0.45755,-99) , 
5, 1.79519, 0, 0, 0.489575,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.356519,-99) , 
20, 2.93692, 1, 0, 0.47902,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.103922);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576878,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521437,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442585,-99) , 
14, 1.496, 0, 0, 0.486208,-99) , 
17, 123.631, 1, 0, 0.503642,-99) , 
NN(
0, 
0, 
-1, 1.19027, 1, -1, 0.406664,-99) , 
17, 280.612, 1, 0, 0.490188,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0800876);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531934,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476418,-99) , 
8, 85.3855, 0, 0, 0.501978,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.374492,-99) , 
6, 2.02342, 1, 0, 0.493428,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.376713,-99) , 
21, 0.645291, 1, 0, 0.485646,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.121378);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549272,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45629,-99) , 
16, 89.5807, 1, 0, 0.519082,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515006,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.333873,-99) , 
21, 0.437785, 1, 0, 0.433943,-99) , 
2, 2.99199, 1, 0, 0.50223,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517493,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.359476,-99) , 
4, 2.3936, 0, 0, 0.424736,-99) , 
16, 72.6193, 0, 0, 0.48913,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0548953);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505342,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445055,-99) , 
5, 0.598397, 0, 0, 0.494963,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384895,-99) , 
21, 0.645291, 1, 0, 0.487179,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.377265,-99) , 
6, 2.02342, 1, 0, 0.480283,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0970888);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516729,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428382,-99) , 
16, 72.6193, 0, 0, 0.502299,-99) , 
NN(
0, 
0, 
-1, 1.79522, 0, -1, 0.38687,-99) , 
3, 2.39241, 1, 0, 0.486638,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518246,-99) , 
NN(
0, 
0, 
-1, 0.437785, 1, -1, 0.376283,-99) , 
15, 1.10033, 0, 0, 0.420577,-99) , 
2, 2.99199, 1, 0, 0.473196,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.104976);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552226,-99) , 
NN(
0, 
0, 
-1, 0.747998, 0, -1, 0.463464,-99) , 
9, 452.896, 0, 0, 0.476969,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533016,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.383863,-99) , 
15, 0.725551, 1, 0, 0.467909,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.349006,-99) , 
5, 1.64559, 0, 0, 0.418352,-99) , 
6, 1.54732, 1, 0, 0.464802,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0787663);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552389,-99) , 
NN(
0, 
0, 
-1, 2.84239, 1, -1, 0.479697,-99) , 
5, 2.69279, 0, 0, 0.495025,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516135,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391953,-99) , 
5, 1.64559, 0, 0, 0.460389,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.355927,-99) , 
13, 0.116657, 1, 0, 0.42563,-99) , 
6, 1.54732, 1, 0, 0.480678,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0790709);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553947,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492871,-99) , 
4, 2.39359, 0, 0, 0.514499,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401392,-99) , 
21, 0.652985, 1, 0, 0.506254,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512335,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.399643,-99) , 
10, 1.0338, 1, 0, 0.466252,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.374688,-99) , 
4, 2.09442, 1, 0, 0.429708,-99) , 
6, 1.54732, 1, 0, 0.490472,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0679718);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.24401, 1, 1, 0.51971,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42053,-99) , 
21, 0.652985, 1, 0, 0.512528,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507012,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.37044,-99) , 
15, 0.846476, 1, 0, 0.459572,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.366008,-99) , 
6, 2.04611, 1, 0, 0.434519,-99) , 
6, 1.54732, 1, 0, 0.496494,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.101883);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57955,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457694,-99) , 
16, 78.3328, 0, 0, 0.532611,-99) , 
NN(
0, 
0, 
-1, 0.596038, 1, -1, 0.47079,-99) , 
17, 143.253, 1, 0, 0.495202,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513797,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.340476,-99) , 
10, 1.21433, 0, 0, 0.415116,-99) , 
17, 280.612, 1, 0, 0.484178,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.104349);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.602289,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490223,-99) , 
13, 0.149791, 0, 0, 0.532262,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518727,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.300154,-99) , 
12, 0.574747, 1, 0, 0.481039,-99) , 
2, 2.69279, 1, 0, 0.508159,-99) , 
NN(
0, 
0, 
-1, 1.19027, 1, -1, 0.41702,-99) , 
17, 280.612, 1, 0, 0.495655,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.123612);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.956968, 1, 1, 0.547059,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411573,-99) , 
14, 0.747998, 0, 0, 0.523953,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.603085,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46485,-99) , 
20, 1.97863, 0, 0, 0.489613,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.30115,-99) , 
21, 0.550963, 1, 0, 0.461709,-99) , 
2, 2.69279, 1, 0, 0.494587,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0931894);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.973331, 0, 1, 0.55886,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515377,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419608,-99) , 
6, 0.725427, 1, 0, 0.49067,-99) , 
6, 1.08817, 0, 0, 0.506595,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531244,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424673,-99) , 
13, 0.0913545, 0, 0, 0.483665,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394852,-99) , 
13, 0.115699, 1, 0, 0.450961,-99) , 
6, 1.4283, 1, 0, 0.492778,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0928579);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522128,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.646952,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480782,-99) , 
6, 1.30927, 0, 0, 0.545864,-99) , 
NN(
0, 
0, 
-1, 2.30172, 1, -1, 0.448661,-99) , 
0, 56.7763, 1, 0, 0.468919,-99) , 
7, 120.174, 0, 0, 0.483092,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.100682);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.59586,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486566,-99) , 
14, 1.79519, 1, 0, 0.52772,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.396781,-99) , 
18, 1.32534, 1, 0, 0.512942,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53426,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458633,-99) , 
0, 40.7465, 1, 0, 0.483508,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393851,-99) , 
2, 2.99199, 1, 0, 0.469816,-99) , 
5, 1.79519, 0, 0, 0.49093,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.101482);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544913,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469181,-99) , 
0, 85.0977, 0, 0, 0.521228,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534342,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.363911,-99) , 
0, 100.933, 1, 0, 0.449445,-99) , 
18, 1.32534, 1, 0, 0.51144,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521248,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393076,-99) , 
5, 0.227961, 1, 0, 0.45003,-99) , 
5, 0.598397, 0, 0, 0.500436,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0809492);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552213,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489606,-99) , 
12, 0.459101, 0, 0, 0.511536,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530027,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.327891,-99) , 
2, 2.6928, 1, 0, 0.454513,-99) , 
12, 0.596038, 1, 0, 0.501848,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514321,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.35071,-99) , 
6, 1.19027, 1, 0, 0.440479,-99) , 
17, 280.612, 1, 0, 0.49351,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.087227);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534031,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472843,-99) , 
16, 76.4287, 0, 0, 0.517241,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515773,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.349785,-99) , 
7, 55.5171, 0, 0, 0.448322,-99) , 
12, 0.596038, 1, 0, 0.505569,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514221,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.378916,-99) , 
10, 1.21433, 0, 0, 0.437728,-99) , 
17, 280.612, 1, 0, 0.496378,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.116448);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.07125, 0, 1, 0.570482,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543878,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455381,-99) , 
7, 133.332, 0, 0, 0.488482,-99) , 
12, 0.470319, 0, 0, 0.502183,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57115,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454007,-99) , 
8, 85.3855, 0, 0, 0.491397,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.313589,-99) , 
0, 113.553, 1, 0, 0.460839,-99) , 
12, 0.517627, 1, 0, 0.488552,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0803088);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524699,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412017,-99) , 
6, 1.90439, 1, 0, 0.515042,-99) , 
NN(
0, 
0, 
-1, 0.5254, 1, -1, 0.438913,-99) , 
18, 1.32534, 1, 0, 0.504685,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510932,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423549,-99) , 
5, 0.313446, 1, 0, 0.47462,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.360938,-99) , 
17, 273.414, 1, 0, 0.44281,-99) , 
5, 0.598397, 0, 0, 0.493619,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0780441);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545971,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516721,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43775,-99) , 
5, 0.712374, 0, 0, 0.496572,-99) , 
NN(
0, 
0, 
-1, 2.56454, 1, -1, 0.439776,-99) , 
12, 0.517627, 1, 0, 0.478781,-99) , 
5, 2.99198, 0, 0, 0.484207,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0915598);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536461,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.472971,-99) , 
3, 0.956967, 1, 0, 0.503375,-99) , 
NN(
0, 
0, 
-1, 0.719525, 1, -1, 0.437221,-99) , 
15, 1.23396, 1, 0, 0.491065,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533195,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.425556,-99) , 
2, 3.05305, 0, 0, 0.479616,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.352622,-99) , 
2, 3.09885, 1, 0, 0.445939,-99) , 
2, 2.99199, 1, 0, 0.481981,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0878776);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574859,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490724,-99) , 
2, 2.2864, 1, 0, 0.508014,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520404,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410828,-99) , 
6, 0.833201, 1, 0, 0.466417,-99) , 
2, 1.85219, 0, 0, 0.495908,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561409,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411356,-99) , 
9, 330.36, 1, 0, 0.48082,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.363832,-99) , 
13, 0.13667, 1, 0, 0.451332,-99) , 
2, 2.99199, 1, 0, 0.486961,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0792028);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55941,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495634,-99) , 
1, 1.78603, 0, 0, 0.520888,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528704,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438107,-99) , 
2, 0.529203, 1, 0, 0.465787,-99) , 
2, 1.85219, 0, 0, 0.504882,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.535645,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453101,-99) , 
15, 0.978074, 0, 0, 0.485663,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.378373,-99) , 
2, 3.09885, 1, 0, 0.457526,-99) , 
2, 2.99199, 1, 0, 0.495415,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0802351);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545879,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.596439,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476745,-99) , 
6, 0.714155, 1, 0, 0.534366,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545222,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469349,-99) , 
15, 1.48075, 0, 0, 0.479346,-99) , 
10, 1.2126, 0, 0, 0.492969,-99) , 
21, 0.310547, 1, 0, 0.500983,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0904956);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547864,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473898,-99) , 
8, 47.6637, 0, 0, 0.53171,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507673,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442662,-99) , 
6, 0.952223, 1, 0, 0.479042,-99) , 
2, 1.85219, 0, 0, 0.51643,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549225,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522161,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.385889,-99) , 
10, 1.00771, 0, 0, 0.441434,-99) , 
15, 0.366778, 1, 0, 0.471261,-99) , 
2, 2.99199, 1, 0, 0.507435,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0858813);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.174565, 1, 1, 0.583472,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523388,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.399949,-99) , 
14, 1.94479, 0, 0, 0.462752,-99) , 
19, 0.209471, 1, 0, 0.53448,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552291,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486837,-99) , 
4, 0.598431, 1, 0, 0.498594,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.355463,-99) , 
3, 2.53165, 1, 0, 0.485664,-99) , 
10, 0.607359, 1, 0, 0.498635,-99)    );
   return;
};
 
// Clean up
inline void Read2HDMaVWjets_2017_BDT_42Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_22Var::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double Read2HDMaVWjets_2017_BDT_42Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_22Var::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
