// Class: Read2HDMaVWjets_2017_BDT_57Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_15Var
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::2HDMaVWjets_2017_BDT_57Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_15Var
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : svanputt
Date           : Wed Apr 22 22:11:27 2020
Host           : Linux vocms0315.cern.ch 2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 09:23:05 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /scratch/40001651.cream02.iihe.ac.be/57Trees
Training events: 437017
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "True" [Print method-specific help message]
NTrees: "57" [Number of trees in the forest]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
SeparationType: "giniindex" [Separation criterion for node splitting]
PruneMethod: "costcomplexity" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "1.200000e+01" [Pruning strength]
# Default:
VerbosityLevel: "Verbose" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "4" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 15
mtw1                          mtw1                          mtw1                          mtw1                                                            'F'    [0,1316.13671875]
MHlnjj_deta_ljjVmet           MHlnjj_deta_ljjVmet           MHlnjj_deta_ljjVmet           MHlnjj_deta_ljjVmet                                             'F'    [1.84355883448e-06,7.9948887825]
MHlnjj_dphi_ljjVmet           MHlnjj_dphi_ljjVmet           MHlnjj_dphi_ljjVmet           MHlnjj_dphi_ljjVmet                                             'F'    [1.16606834126e-05,3.14159178734]
MHlnjj_deta_jjVl              MHlnjj_deta_jjVl              MHlnjj_deta_jjVl              MHlnjj_deta_jjVl                                                'F'    [4.67996233056e-06,10.0481100082]
MHlnjj_dphi_jjVl              MHlnjj_dphi_jjVl              MHlnjj_dphi_jjVl              MHlnjj_dphi_jjVl                                                'F'    [4.14871465182e-05,3.14158701897]
MHlnjj_deta_lVmet             MHlnjj_deta_lVmet             MHlnjj_deta_lVmet             MHlnjj_deta_lVmet                                               'F'    [1.0596588254e-05,2.49951171875]
PuppiMET_pt                   PuppiMET_pt                   PuppiMET_pt                   PuppiMET_pt                                                     'F'    [50.0001335144,1523.65405273]
MHlnjj_pt_ljj                 MHlnjj_pt_ljj                 MHlnjj_pt_ljj                 MHlnjj_pt_ljj                                                   'F'    [0.11474018544,1025.22814941]
MHlnjj_PTljj_D_Mlmetjj        MHlnjj_PTljj_D_Mlmetjj        MHlnjj_PTljj_D_Mlmetjj        MHlnjj_PTljj_D_Mlmetjj                                          'F'    [0.000469836377306,3.65420365334]
MHlnjj_MINPTlj_D_PTmet        MHlnjj_MINPTlj_D_PTmet        MHlnjj_MINPTlj_D_PTmet        MHlnjj_MINPTlj_D_PTmet                                          'F'    [0.0209071692079,3.49794340134]
MHlnjj_MINPTlj_D_Mlmetjj      MHlnjj_MINPTlj_D_Mlmetjj      MHlnjj_MINPTlj_D_Mlmetjj      MHlnjj_MINPTlj_D_Mlmetjj                                        'F'    [0.0134515520185,0.638022661209]
MHlnjj_m_jj                   MHlnjj_m_jj                   MHlnjj_m_jj                   MHlnjj_m_jj                                                     'F'    [65.0002822876,104.999908447]
MHlnjj_m_ljj                  MHlnjj_m_ljj                  MHlnjj_m_ljj                  MHlnjj_m_ljj                                                    'F'    [74.5745773315,2237.96362305]
MHlnjj_MAXPTlj_D_PTmet        MHlnjj_MAXPTlj_D_PTmet        MHlnjj_MAXPTlj_D_PTmet        MHlnjj_MAXPTlj_D_PTmet                                          'F'    [0.0414094999433,13.7160482407]
MHlnjj_MTljj_D_Mlmetjj        MHlnjj_MTljj_D_Mlmetjj        MHlnjj_MTljj_D_Mlmetjj        MHlnjj_MTljj_D_Mlmetjj                                          'F'    [0.059488967061,0.938192307949]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new 2HDMaVWjets_2017_BDT_57Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_15VarNode
   
#ifndef 2HDMaVWjets_2017_BDT_57Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_15VarNode__def
#define 2HDMaVWjets_2017_BDT_57Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_15VarNode__def
   
class 2HDMaVWjets_2017_BDT_57Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_15VarNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   2HDMaVWjets_2017_BDT_57Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_15VarNode ( 2HDMaVWjets_2017_BDT_57Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_15VarNode* left,2HDMaVWjets_2017_BDT_57Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_15VarNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~2HDMaVWjets_2017_BDT_57Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_15VarNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   2HDMaVWjets_2017_BDT_57Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_15VarNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   2HDMaVWjets_2017_BDT_57Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_15VarNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   2HDMaVWjets_2017_BDT_57Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_15VarNode*   fLeft;     // pointer to the left daughter node
   2HDMaVWjets_2017_BDT_57Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_15VarNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   2HDMaVWjets_2017_BDT_57Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_15VarNode::~2HDMaVWjets_2017_BDT_57Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_15VarNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool 2HDMaVWjets_2017_BDT_57Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_15VarNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool 2HDMaVWjets_2017_BDT_57Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_15VarNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class Read2HDMaVWjets_2017_BDT_57Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_15Var : public IClassifierReader {

 public:

   // constructor
   Read2HDMaVWjets_2017_BDT_57Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_15Var( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "Read2HDMaVWjets_2017_BDT_57Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_15Var" ),
        fNvars( 15 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "mtw1", "MHlnjj_deta_ljjVmet", "MHlnjj_dphi_ljjVmet", "MHlnjj_deta_jjVl", "MHlnjj_dphi_jjVl", "MHlnjj_deta_lVmet", "PuppiMET_pt", "MHlnjj_pt_ljj", "MHlnjj_PTljj_D_Mlmetjj", "MHlnjj_MINPTlj_D_PTmet", "MHlnjj_MINPTlj_D_Mlmetjj", "MHlnjj_m_jj", "MHlnjj_m_ljj", "MHlnjj_MAXPTlj_D_PTmet", "MHlnjj_MTljj_D_Mlmetjj" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~Read2HDMaVWjets_2017_BDT_57Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_15Var() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[15];
   double fVmax[15];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[15];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<2HDMaVWjets_2017_BDT_57Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_15VarNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double Read2HDMaVWjets_2017_BDT_57Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_15Var::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      2HDMaVWjets_2017_BDT_57Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_15VarNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(2HDMaVWjets_2017_BDT_57Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_15VarNode*)current->GetRight();
         else current=(2HDMaVWjets_2017_BDT_57Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_15VarNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void Read2HDMaVWjets_2017_BDT_57Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_15Var::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.668313017417833);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.92357,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.649663,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485725,-99) , 
14, 0.439866, 1, 0, 0.578827,-99) , 
4, 1.94481, 1, 0, 0.814815,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.67832,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.237444,-99) , 
7, 72.1079, 0, 0, 0.546332,-99) , 
NN(
0, 
0, 
-1, 82.1071, 0, -1, 0.19782,-99) , 
4, 1.34642, 1, 0, 0.295471,-99) , 
9, 0.352053, 1, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.521861);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.844318,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.643926,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410457,-99) , 
0, 95.4977, 0, 0, 0.506017,-99) , 
NN(
0, 
0, 
-1, 1.78537, 1, -1, 0.248566,-99) , 
13, 0.719525, 1, 0, 0.339801,-99) , 
0, 125.346, 0, 0, 0.473104,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.403874);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.743045,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559394,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.318205,-99) , 
12, 142.973, 1, 0, 0.46604,-99) , 
NN(
0, 
0, 
-1, 96.7818, 0, -1, 0.249814,-99) , 
12, 177.173, 1, 0, 0.373619,-99) , 
6, 120.174, 0, 0, 0.489705,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.319648);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.704509,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553984,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.387793,-99) , 
0, 47.7506, 1, 0, 0.428111,-99) , 
NN(
0, 
0, 
-1, 1.79523, 1, -1, 0.228315,-99) , 
5, 1.54732, 1, 0, 0.380992,-99) , 
0, 125.346, 0, 0, 0.457914,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.271185);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.624978,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.59177,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420038,-99) , 
8, 0.30277, 0, 0, 0.486447,-99) , 
NN(
0, 
0, 
-1, 1.78537, 1, -1, 0.316806,-99) , 
6, 73.391, 0, 0, 0.398806,-99) , 
6, 120.174, 0, 0, 0.466239,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.228783);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.706302,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572174,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42865,-99) , 
0, 96.6568, 0, 0, 0.494201,-99) , 
12, 118.725, 1, 0, 0.545854,-99) , 
NN(
0, 
0, 
-1, 1.54732, 1, -1, 0.377694,-99) , 
12, 177.593, 1, 0, 0.470897,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.17065);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.653366,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449217,-99) , 
9, 0.40158, 1, 0, 0.604426,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504619,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.387256,-99) , 
4, 2.69279, 1, 0, 0.475808,-99) , 
13, 0.692583, 1, 0, 0.524014,-99) , 
NN(
0, 
0, 
-1, 1.79523, 1, -1, 0.355376,-99) , 
5, 1.54732, 1, 0, 0.487251,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.174515);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.604292,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517413,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.29934,-99) , 
12, 269.353, 1, 0, 0.487843,-99) , 
NN(
0, 
0, 
-1, 0.563521, 1, -1, 0.369599,-99) , 
2, 2.69279, 1, 0, 0.435295,-99) , 
0, 125.346, 0, 0, 0.471897,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.210155);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.635611,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542212,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.399872,-99) , 
5, 0.714154, 1, 0, 0.466075,-99) , 
14, 0.310598, 1, 0, 0.501876,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511365,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.344068,-99) , 
11, 81.508, 0, 0, 0.416086,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.258823,-99) , 
11, 89.7619, 1, 0, 0.368453,-99) , 
9, 0.517627, 1, 0, 0.457778,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.168579);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.606199,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511816,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.389751,-99) , 
4, 1.64554, 1, 0, 0.455865,-99) , 
13, 0.506532, 1, 0, 0.525007,-99) , 
NN(
0, 
0, 
-1, 2.53165, 1, -1, 0.414309,-99) , 
13, 0.692583, 1, 0, 0.454079,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.148376);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582386,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.570347,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443494,-99) , 
0, 107.439, 0, 0, 0.462805,-99) , 
0, 125.346, 0, 0, 0.48753,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.333267,-99) , 
5, 1.90439, 1, 0, 0.472404,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.126272);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560809,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.474642,-99) , 
7, 85.3855, 0, 0, 0.51838,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.340157,-99) , 
14, 0.652081, 1, 0, 0.505655,-99) , 
NN(
0, 
0, 
-1, 2.24399, 0, -1, 0.368239,-99) , 
3, 2.39241, 1, 0, 0.486555,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.105636);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529769,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370071,-99) , 
14, 0.652081, 1, 0, 0.517672,-99) , 
NN(
0, 
0, 
-1, 1.94478, 0, -1, 0.402251,-99) , 
3, 2.45639, 1, 0, 0.504067,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370734,-99) , 
5, 1.90439, 1, 0, 0.491256,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.159637);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595591,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527409,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.375556,-99) , 
2, 2.84239, 1, 0, 0.473648,-99) , 
4, 1.19693, 1, 0, 0.510844,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574234,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424251,-99) , 
10, 0.0982972, 0, 0, 0.523571,-99) , 
NN(
0, 
0, 
-1, 2.25571, 1, -1, 0.409769,-99) , 
4, 2.54319, 0, 0, 0.443641,-99) , 
3, 0.956967, 1, 0, 0.475775,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.108447);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553623,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576659,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489844,-99) , 
2, 2.09441, 1, 0, 0.518942,-99) , 
NN(
0, 
0, 
-1, 0.527937, 1, -1, 0.436007,-99) , 
5, 0.476106, 1, 0, 0.462069,-99) , 
14, 0.310547, 1, 0, 0.475665,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0810444);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550323,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484817,-99) , 
4, 2.3936, 0, 0, 0.507115,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.374027,-99) , 
14, 0.645291, 1, 0, 0.497591,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.369528,-99) , 
5, 2.02342, 1, 0, 0.48932,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.127434);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575611,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.558341,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459765,-99) , 
0, 108.87, 0, 0, 0.497094,-99) , 
9, 0.25744, 1, 0, 0.5172,-99) , 
NN(
NN(
0, 
0, 
-1, 1.14939, 1, 1, 0.559011,-99) , 
NN(
0, 
0, 
-1, 106.034, 1, -1, 0.40849,-99) , 
5, 0.476108, 1, 0, 0.454847,-99) , 
9, 0.517627, 1, 0, 0.496543,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.073201);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522836,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451556,-99) , 
3, 2.45639, 1, 0, 0.513782,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.395427,-99) , 
5, 2.02342, 1, 0, 0.505701,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392247,-99) , 
14, 0.645291, 1, 0, 0.498136,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.104765);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.07125, 0, 1, 0.58365,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534506,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458179,-99) , 
6, 133.332, 0, 0, 0.486668,-99) , 
9, 0.470319, 0, 0, 0.502924,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521006,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430356,-99) , 
12, 168.261, 1, 0, 0.481183,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.336512,-99) , 
0, 113.553, 1, 0, 0.455894,-99) , 
9, 0.517627, 1, 0, 0.487327,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.0830125);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555816,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504668,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434065,-99) , 
0, 62.6732, 0, 0, 0.486633,-99) , 
3, 0.414604, 1, 0, 0.503422,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523004,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41334,-99) , 
3, 1.43548, 1, 0, 0.48852,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.374849,-99) , 
11, 89.7619, 1, 0, 0.455956,-99) , 
9, 0.517627, 1, 0, 0.487676,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0754961);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529566,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476338,-99) , 
4, 2.39359, 0, 0, 0.494908,-99) , 
NN(
0, 
0, 
-1, 2.09442, 1, -1, 0.433022,-99) , 
5, 1.66634, 1, 0, 0.483846,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.397179,-99) , 
14, 0.645291, 1, 0, 0.478153,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0873655);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554089,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491488,-99) , 
4, 0.897626, 1, 0, 0.508157,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.403572,-99) , 
3, 2.37797, 1, 0, 0.499007,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554321,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414272,-99) , 
1, 2.07696, 1, 0, 0.485362,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.313469,-99) , 
13, 1.05727, 1, 0, 0.444941,-99) , 
8, 0.174457, 0, 0, 0.486415,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.105899);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.575456,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48921,-99) , 
4, 1.34652, 0, 0, 0.550829,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546818,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.473433,-99) , 
3, 0.396333, 1, 0, 0.49066,-99) , 
1, 1.66568, 0, 0, 0.510153,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561178,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.413567,-99) , 
14, 0.483685, 1, 0, 0.484923,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.336566,-99) , 
5, 1.54732, 1, 0, 0.448481,-99) , 
8, 0.174457, 0, 0, 0.495837,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0760767);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.81179, 0, 1, 0.522115,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441445,-99) , 
3, 2.37797, 1, 0, 0.515151,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53227,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.380252,-99) , 
11, 87.857, 1, 0, 0.486583,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.347364,-99) , 
13, 1.05727, 1, 0, 0.454486,-99) , 
8, 0.174457, 0, 0, 0.501135,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0866156);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.620067,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485578,-99) , 
12, 123.558, 1, 0, 0.517971,-99) , 
NN(
0, 
0, 
-1, 2.0944, 0, -1, 0.463856,-99) , 
12, 187.04, 1, 0, 0.496518,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511634,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.385119,-99) , 
12, 177.173, 0, 0, 0.443312,-99) , 
11, 72.6193, 0, 0, 0.487695,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0569228);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.163572, 0, 1, 0.519084,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437617,-99) , 
9, 0.6832, 1, 0, 0.511861,-99) , 
NN(
0, 
0, 
-1, 80.7377, 0, -1, 0.443841,-99) , 
11, 72.6193, 0, 0, 0.500588,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.102989);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.609088,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49497,-99) , 
13, 1.2229, 0, 0, 0.516708,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5376,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417467,-99) , 
2, 2.5432, 0, 0, 0.477512,-99) , 
8, 0.340161, 1, 0, 0.502723,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.602168,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431221,-99) , 
2, 2.24406, 1, 0, 0.498479,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.366262,-99) , 
8, 0.108176, 0, 0, 0.458034,-99) , 
8, 0.174457, 0, 0, 0.492434,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.099574);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566869,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.485248,-99) , 
4, 2.09441, 1, 0, 0.5322,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504641,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.383076,-99) , 
13, 1.38193, 1, 0, 0.477145,-99) , 
8, 0.340161, 1, 0, 0.512608,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.594684,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.448865,-99) , 
5, 0.952153, 0, 0, 0.505665,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.377673,-99) , 
5, 1.4283, 1, 0, 0.468927,-99) , 
8, 0.174457, 0, 0, 0.502598,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0726422);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58356,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475854,-99) , 
14, 0.490216, 1, 0, 0.534147,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514941,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459587,-99) , 
8, 0.350382, 1, 0, 0.500071,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.381369,-99) , 
8, 0.120932, 0, 0, 0.489176,-99) , 
5, 0.357082, 1, 0, 0.498975,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0624011);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585445,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498417,-99) , 
10, 0.14847, 0, 0, 0.532579,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51583,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.471273,-99) , 
2, 2.5432, 1, 0, 0.490681,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398648,-99) , 
8, 0.120932, 0, 0, 0.482303,-99) , 
5, 0.357082, 1, 0, 0.49323,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0732655);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573684,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48971,-99) , 
1, 1.03066, 0, 0, 0.535762,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.592443,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487126,-99) , 
2, 2.28674, 1, 0, 0.501731,-99) , 
NN(
0, 
0, 
-1, 0.648272, 1, -1, 0.43316,-99) , 
2, 1.9448, 0, 0, 0.485276,-99) , 
5, 0.357082, 1, 0, 0.496246,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0819175);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543037,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533016,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446299,-99) , 
4, 1.04722, 0, 0, 0.512298,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504851,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.371344,-99) , 
11, 85.9528, 1, 0, 0.459786,-99) , 
6, 109.909, 1, 0, 0.497997,-99) , 
0, 125.346, 0, 0, 0.507038,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0958044);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.562305,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489211,-99) , 
5, 1.07123, 0, 0, 0.522344,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517783,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.40829,-99) , 
13, 0.692583, 1, 0, 0.473721,-99) , 
2, 2.244, 0, 0, 0.506508,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543925,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517246,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.386954,-99) , 
2, 2.39362, 1, 0, 0.436429,-99) , 
7, 95.2127, 0, 0, 0.469386,-99) , 
9, 0.517627, 1, 0, 0.494294,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.102759);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551627,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48662,-99) , 
2, 2.6928, 0, 0, 0.520585,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524269,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.365049,-99) , 
5, 0.476083, 1, 0, 0.448575,-99) , 
14, 0.571497, 1, 0, 0.505178,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546505,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.413456,-99) , 
10, 0.0913545, 0, 0, 0.48611,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.402841,-99) , 
10, 0.115699, 1, 0, 0.455541,-99) , 
5, 1.4283, 1, 0, 0.492708,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0917432);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530439,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461365,-99) , 
11, 72.075, 0, 0, 0.516186,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511848,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.365875,-99) , 
9, 0.527867, 1, 0, 0.467644,-99) , 
11, 89.762, 1, 0, 0.50291,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560437,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.435631,-99) , 
2, 3.06323, 0, 0, 0.48788,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.369651,-99) , 
2, 3.09885, 1, 0, 0.456029,-99) , 
2, 2.99199, 1, 0, 0.493335,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.05048);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541162,-99) , 
NN(
0, 
0, 
-1, 0.340662, 0, -1, 0.482054,-99) , 
14, 0.310547, 1, 0, 0.489814,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412654,-99) , 
5, 2.02342, 1, 0, 0.484902,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.0725557);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.54319, 0, 1, 0.520182,-99) , 
NN(
0, 
0, 
-1, 0.612103, 1, -1, 0.449074,-99) , 
14, 0.571497, 1, 0, 0.505084,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530005,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416023,-99) , 
2, 2.6928, 1, 0, 0.483597,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39534,-99) , 
4, 2.5432, 1, 0, 0.462454,-99) , 
5, 1.4283, 1, 0, 0.494391,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0723406);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.578048,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529401,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451772,-99) , 
10, 0.11928, 1, 0, 0.488791,-99) , 
10, 0.168219, 0, 0, 0.506573,-99) , 
NN(
0, 
0, 
-1, 0.88426, 0, -1, 0.471978,-99) , 
5, 0.714154, 1, 0, 0.486733,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0852763);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577849,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458207,-99) , 
10, 0.109894, 0, 0, 0.543613,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508941,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404588,-99) , 
10, 0.141382, 1, 0, 0.484484,-99) , 
2, 2.62868, 1, 0, 0.504225,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.515675,-99) , 
NN(
0, 
0, 
-1, 0.10532, 1, -1, 0.430619,-99) , 
10, 0.133581, 0, 0, 0.470628,-99) , 
2, 1.9448, 0, 0, 0.495762,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0433873);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536461,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502767,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451042,-99) , 
2, 2.17277, 0, 0, 0.490919,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417056,-99) , 
14, 0.605111, 1, 0, 0.483449,-99) , 
2, 0.598408, 1, 0, 0.487717,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0764434);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532579,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48488,-99) , 
4, 2.39363, 0, 0, 0.502485,-99) , 
NN(
0, 
0, 
-1, 0.527867, 1, -1, 0.457732,-99) , 
11, 89.762, 1, 0, 0.490278,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550338,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421685,-99) , 
10, 0.124348, 0, 0, 0.481577,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.376554,-99) , 
2, 3.09885, 1, 0, 0.453533,-99) , 
2, 2.99199, 1, 0, 0.482782,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.059679);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.563052,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497729,-99) , 
4, 2.54319, 0, 0, 0.5094,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500558,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.390495,-99) , 
4, 2.24401, 1, 0, 0.465433,-99) , 
2, 2.99199, 1, 0, 0.499577,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544976,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445154,-99) , 
3, 1.26583, 1, 0, 0.492564,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.379383,-99) , 
11, 78.3335, 0, 0, 0.461192,-99) , 
8, 0.174457, 0, 0, 0.490863,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0874229);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525987,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449227,-99) , 
3, 2.37797, 1, 0, 0.519082,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5384,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421934,-99) , 
8, 0.141419, 0, 0, 0.470288,-99) , 
8, 0.174559, 0, 0, 0.507082,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532137,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416307,-99) , 
5, 0.952201, 0, 0, 0.482077,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.376756,-99) , 
10, 0.13667, 1, 0, 0.455656,-99) , 
2, 2.99199, 1, 0, 0.496618,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0744453);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522933,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561912,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47653,-99) , 
0, 56.7763, 1, 0, 0.496456,-99) , 
NN(
0, 
0, 
-1, 2.8424, 1, -1, 0.443437,-99) , 
9, 0.358405, 0, 0, 0.480681,-99) , 
14, 0.310547, 1, 0, 0.486921,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0913836);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.615908,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426067,-99) , 
5, 0.475922, 1, 0, 0.529935,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545564,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483285,-99) , 
0, 125.346, 0, 0, 0.498103,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541941,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.290608,-99) , 
6, 58.4241, 0, 0, 0.41881,-99) , 
9, 0.596506, 1, 0, 0.488206,-99) , 
10, 0.162159, 0, 0, 0.494697,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.0355589);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 3.27519, 0, 1, 0.511945,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447243,-99) , 
5, 2.02342, 1, 0, 0.507546,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437072,-99) , 
14, 0.645291, 1, 0, 0.503084,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.08262);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.142823, 0, 1, 0.52801,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422372,-99) , 
13, 1.34376, 1, 0, 0.510844,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571006,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481101,-99) , 
13, 1.11014, 0, 0, 0.500934,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.352793,-99) , 
14, 0.550963, 1, 0, 0.479762,-99) , 
2, 2.69279, 1, 0, 0.49633,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0326829);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550981,-99) , 
NN(
0, 
0, 
-1, 0.605917, 1, -1, 0.491617,-99) , 
10, 0.163572, 0, 0, 0.498663,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452832,-99) , 
9, 0.6832, 1, 0, 0.494728,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0773853);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.07125, 0, 1, 0.565068,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525001,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479235,-99) , 
4, 1.64562, 1, 0, 0.499594,-99) , 
9, 0.470319, 0, 0, 0.510558,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553412,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458195,-99) , 
0, 86.5161, 0, 0, 0.499373,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392279,-99) , 
0, 113.553, 1, 0, 0.481623,-99) , 
9, 0.517627, 1, 0, 0.501118,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.11173);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.07123, 0, 1, 0.558822,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528964,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441371,-99) , 
14, 0.49901, 1, 0, 0.492592,-99) , 
8, 0.268115, 0, 0, 0.514787,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.56256,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455323,-99) , 
12, 125.587, 1, 0, 0.509338,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.367886,-99) , 
12, 171.964, 1, 0, 0.478564,-99) , 
4, 1.49602, 0, 0, 0.501774,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.0238064);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568503,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5003,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412502,-99) , 
3, 2.49538, 1, 0, 0.494967,-99) , 
3, 3.27519, 0, 0, 0.499009,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446174,-99) , 
5, 2.02342, 1, 0, 0.49565,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0693898);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572344,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489995,-99) , 
8, 0.270327, 0, 0, 0.507999,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398748,-99) , 
8, 0.315304, 1, 0, 0.498138,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519766,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434577,-99) , 
11, 78.334, 1, 0, 0.470979,-99) , 
8, 0.348444, 1, 0, 0.491027,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0835415);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539096,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467131,-99) , 
11, 78.3335, 0, 0, 0.517756,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415495,-99) , 
8, 0.315304, 1, 0, 0.508571,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518992,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441704,-99) , 
1, 0.662327, 1, 0, 0.47339,-99) , 
8, 0.348444, 1, 0, 0.499367,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0756236);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577458,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455297,-99) , 
4, 0.783641, 0, 0, 0.537981,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505542,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41192,-99) , 
5, 1.54732, 1, 0, 0.487209,-99) , 
4, 1.64561, 1, 0, 0.50247,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526563,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442774,-99) , 
5, 0.951874, 0, 0, 0.477042,-99) , 
8, 0.348444, 1, 0, 0.49582,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0452956);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528821,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554674,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486428,-99) , 
13, 1.57859, 0, 0, 0.491796,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42999,-99) , 
14, 0.605111, 1, 0, 0.485654,-99) , 
2, 0.598408, 1, 0, 0.489123,-99)    );
  // itree = 55
  fBoostWeights.push_back(0.0315291);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522674,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.503073,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442494,-99) , 
14, 0.338442, 0, 0, 0.493667,-99) , 
13, 0.553804, 1, 0, 0.499848,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.456272,-99) , 
14, 0.645291, 1, 0, 0.497131,-99)    );
  // itree = 56
  fBoostWeights.push_back(0.0425849);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538936,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522609,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500234,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438594,-99) , 
9, 0.358405, 0, 0, 0.480624,-99) , 
0, 125.346, 0, 0, 0.489366,-99) , 
3, 3.34937, 0, 0, 0.491968,-99)    );
   return;
};
 
// Clean up
inline void Read2HDMaVWjets_2017_BDT_57Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_15Var::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double Read2HDMaVWjets_2017_BDT_57Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_15Var::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
