// Class: ReaddarkHiggsVWjets_2017_BDT_55Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_16Var
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::darkHiggsVWjets_2017_BDT_55Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_16Var
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : svanputt
Date           : Thu May 28 15:32:12 2020
Host           : Linux vocms0315.cern.ch 2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 09:23:05 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /scratch/40878817.cream02.iihe.ac.be/55Trees
Training events: 440551
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "True" [Print method-specific help message]
NTrees: "55" [Number of trees in the forest]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
SeparationType: "giniindex" [Separation criterion for node splitting]
PruneMethod: "costcomplexity" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "1.200000e+01" [Pruning strength]
# Default:
VerbosityLevel: "Verbose" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "4" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 16
mtw1                          mtw1                          mtw1                          mtw1                                                            'F'    [0,1429.77636719]
MHlnjj_deta_ljjVmet           MHlnjj_deta_ljjVmet           MHlnjj_deta_ljjVmet           MHlnjj_deta_ljjVmet                                             'F'    [1.36037840548e-06,7.68385124207]
MHlnjj_deta_jjVl              MHlnjj_deta_jjVl              MHlnjj_deta_jjVl              MHlnjj_deta_jjVl                                                'F'    [4.67996233056e-06,10.0481100082]
MHlnjj_dphi_jjVl              MHlnjj_dphi_jjVl              MHlnjj_dphi_jjVl              MHlnjj_dphi_jjVl                                                'F'    [4.14871465182e-05,3.14158701897]
MHlnjj_deta_lVmet             MHlnjj_deta_lVmet             MHlnjj_deta_lVmet             MHlnjj_deta_lVmet                                               'F'    [5.51156699657e-06,2.49951171875]
PuppiMET_pt                   PuppiMET_pt                   PuppiMET_pt                   PuppiMET_pt                                                     'F'    [50.0000076294,1308.07995605]
MHlnjj_m_lmetjj               MHlnjj_m_lmetjj               MHlnjj_m_lmetjj               MHlnjj_m_lmetjj                                                 'F'    [105.564781189,2611.10766602]
MHlnjj_PTljj_D_PTmet          MHlnjj_PTljj_D_PTmet          MHlnjj_PTljj_D_PTmet          MHlnjj_PTljj_D_PTmet                                            'F'    [0.00319861224853,12.7120838165]
MHlnjj_PTljj_D_Mlmetjj        MHlnjj_PTljj_D_Mlmetjj        MHlnjj_PTljj_D_Mlmetjj        MHlnjj_PTljj_D_Mlmetjj                                          'F'    [0.000932293245569,3.17160820961]
MHlnjj_MINPTlj_D_PTmet        MHlnjj_MINPTlj_D_PTmet        MHlnjj_MINPTlj_D_PTmet        MHlnjj_MINPTlj_D_PTmet                                          'F'    [0.0279273837805,3.62337827682]
MHlnjj_deta_jVj               MHlnjj_deta_jVj               MHlnjj_deta_jVj               MHlnjj_deta_jVj                                                 'F'    [0,2.58422851562]
MHlnjj_m_jj                   MHlnjj_m_jj                   MHlnjj_m_jj                   MHlnjj_m_jj                                                     'F'    [65.000038147,104.999923706]
MHlnjj_m_ljj                  MHlnjj_m_ljj                  MHlnjj_m_ljj                  MHlnjj_m_ljj                                                    'F'    [75.383644104,2460.1262207]
MHlnjj_MAXPTlj_D_PTmet        MHlnjj_MAXPTlj_D_PTmet        MHlnjj_MAXPTlj_D_PTmet        MHlnjj_MAXPTlj_D_PTmet                                          'F'    [0.0622296258807,13.7160482407]
MHlnjj_MTljj_D_PTmet          MHlnjj_MTljj_D_PTmet          MHlnjj_MTljj_D_PTmet          MHlnjj_MTljj_D_PTmet                                            'F'    [0.079993866384,18.6729679108]
MHlnjj_MTljj_D_Mlmetjj        MHlnjj_MTljj_D_Mlmetjj        MHlnjj_MTljj_D_Mlmetjj        MHlnjj_MTljj_D_Mlmetjj                                          'F'    [0.0539623014629,0.951482534409]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new darkHiggsVWjets_2017_BDT_55Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_16VarNode
   
#ifndef darkHiggsVWjets_2017_BDT_55Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_16VarNode__def
#define darkHiggsVWjets_2017_BDT_55Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_16VarNode__def
   
class darkHiggsVWjets_2017_BDT_55Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_16VarNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   darkHiggsVWjets_2017_BDT_55Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_16VarNode ( darkHiggsVWjets_2017_BDT_55Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_16VarNode* left,darkHiggsVWjets_2017_BDT_55Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_16VarNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~darkHiggsVWjets_2017_BDT_55Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_16VarNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   darkHiggsVWjets_2017_BDT_55Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_16VarNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   darkHiggsVWjets_2017_BDT_55Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_16VarNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   darkHiggsVWjets_2017_BDT_55Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_16VarNode*   fLeft;     // pointer to the left daughter node
   darkHiggsVWjets_2017_BDT_55Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_16VarNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   darkHiggsVWjets_2017_BDT_55Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_16VarNode::~darkHiggsVWjets_2017_BDT_55Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_16VarNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool darkHiggsVWjets_2017_BDT_55Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_16VarNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool darkHiggsVWjets_2017_BDT_55Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_16VarNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReaddarkHiggsVWjets_2017_BDT_55Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_16Var : public IClassifierReader {

 public:

   // constructor
   ReaddarkHiggsVWjets_2017_BDT_55Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_16Var( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReaddarkHiggsVWjets_2017_BDT_55Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_16Var" ),
        fNvars( 16 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "mtw1", "MHlnjj_deta_ljjVmet", "MHlnjj_deta_jjVl", "MHlnjj_dphi_jjVl", "MHlnjj_deta_lVmet", "PuppiMET_pt", "MHlnjj_m_lmetjj", "MHlnjj_PTljj_D_PTmet", "MHlnjj_PTljj_D_Mlmetjj", "MHlnjj_MINPTlj_D_PTmet", "MHlnjj_deta_jVj", "MHlnjj_m_jj", "MHlnjj_m_ljj", "MHlnjj_MAXPTlj_D_PTmet", "MHlnjj_MTljj_D_PTmet", "MHlnjj_MTljj_D_Mlmetjj" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReaddarkHiggsVWjets_2017_BDT_55Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_16Var() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[16];
   double fVmax[16];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[16];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<darkHiggsVWjets_2017_BDT_55Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_16VarNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReaddarkHiggsVWjets_2017_BDT_55Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_16Var::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      darkHiggsVWjets_2017_BDT_55Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_16VarNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(darkHiggsVWjets_2017_BDT_55Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_16VarNode*)current->GetRight();
         else current=(darkHiggsVWjets_2017_BDT_55Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_16VarNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReaddarkHiggsVWjets_2017_BDT_55Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_16Var::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1.07097814731944);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.950479,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.6808,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.260335,-99) , 
14, 1.30058, 1, 0, 0.415833,-99) , 
NN(
0, 
0, 
-1, 0.385552, 1, -1, 0.0575165,-99) , 
3, 1.79521, 1, 0, 0.193688,-99) , 
14, 0.965374, 1, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.773816);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.912904,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553571,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.165758,-99) , 
12, 135.102, 1, 0, 0.37525,-99) , 
NN(
0, 
0, 
-1, 0.370351, 1, -1, 0.0595981,-99) , 
12, 179.892, 1, 0, 0.253617,-99) , 
0, 136.169, 0, 0, 0.46817,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.604046);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.778811,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543481,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.242043,-99) , 
2, 1.53245, 1, 0, 0.448133,-99) , 
NN(
0, 
0, 
-1, 174.959, 1, -1, 0.182234,-99) , 
0, 103.748, 0, 0, 0.248587,-99) , 
0, 136.169, 0, 0, 0.405262,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.511111);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.783136,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.352074,-99) , 
12, 192.447, 1, 0, 0.674957,-99) , 
NN(
0, 
0, 
-1, 179.892, 1, -1, 0.271534,-99) , 
5, 109.909, 0, 0, 0.406528,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.374144);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.725865,-99) , 
NN(
0, 
0, 
-1, 1.39217, 1, -1, 0.361545,-99) , 
12, 150.192, 1, 0, 0.625397,-99) , 
NN(
0, 
0, 
-1, 1.10318, 1, -1, 0.338669,-99) , 
8, 0.302901, 0, 0, 0.462603,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.27748);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.711188,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401871,-99) , 
0, 68.0846, 0, 0, 0.646323,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522814,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.309175,-99) , 
12, 153.383, 1, 0, 0.459993,-99) , 
5, 109.909, 0, 0, 0.526347,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0596939,-99) , 
14, 2.73613, 1, 0, 0.494924,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.248108);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.642884,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520369,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.311763,-99) , 
11, 76.4288, 0, 0, 0.46498,-99) , 
NN(
0, 
0, 
-1, 2.3936, 1, -1, 0.288274,-99) , 
4, 1.19025, 1, 0, 0.404834,-99) , 
0, 136.169, 0, 0, 0.461549,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.283052);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.729139,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477568,-99) , 
4, 1.4283, 1, 0, 0.649581,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559873,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.377119,-99) , 
0, 117.515, 0, 0, 0.424571,-99) , 
6, 418.782, 0, 0, 0.464836,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0764759,-99) , 
14, 2.73613, 1, 0, 0.438125,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.230027);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.66232, 1, 1, 0.622153,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58364,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411034,-99) , 
12, 119.121, 1, 0, 0.456231,-99) , 
6, 418.782, 0, 0, 0.485764,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0990193,-99) , 
14, 2.73613, 1, 0, 0.461471,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.183308);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.552334,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417404,-99) , 
11, 76.4286, 0, 0, 0.517508,-99) , 
NN(
0, 
0, 
-1, 0.330234, 0, -1, 0.328242,-99) , 
2, 2.39241, 1, 0, 0.496041,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.121517,-99) , 
14, 2.73613, 1, 0, 0.474187,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.157933);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531395,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.413259,-99) , 
2, 1.2686, 1, 0, 0.491304,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.248965,-99) , 
4, 2.02342, 1, 0, 0.476861,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.142481,-99) , 
14, 2.73613, 1, 0, 0.458557,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.165133);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579133,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.459428,-99) , 
3, 0.598431, 1, 0, 0.489257,-99) , 
NN(
0, 
0, 
-1, 1.92865, 1, -1, 0.349477,-99) , 
13, 1.02586, 1, 0, 0.464708,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.162887,-99) , 
14, 2.73613, 1, 0, 0.448995,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.149799);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.592207,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476684,-99) , 
14, 1.37871, 0, 0, 0.522145,-99) , 
NN(
0, 
0, 
-1, 1.19025, 1, -1, 0.412818,-99) , 
3, 2.09441, 1, 0, 0.492291,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.287909,-99) , 
13, 1.36259, 1, 0, 0.47358,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.178051);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.675344,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527642,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.390137,-99) , 
4, 1.19027, 1, 0, 0.491652,-99) , 
6, 332.711, 0, 0, 0.554321,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517995,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391417,-99) , 
4, 0.76507, 0, 0, 0.462536,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.198242,-99) , 
4, 1.78537, 1, 0, 0.433529,-99) , 
13, 0.712411, 1, 0, 0.490092,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.117558);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.606037,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481264,-99) , 
6, 418.782, 0, 0, 0.504367,-99) , 
NN(
0, 
0, 
-1, 1.68826, 1, -1, 0.388257,-99) , 
14, 1.97723, 1, 0, 0.486604,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.218592,-99) , 
14, 2.73613, 1, 0, 0.473071,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.251142);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.627838,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.374919,-99) , 
13, 0.883572, 1, 0, 0.58688,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.567765,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.379279,-99) , 
9, 0.553122, 0, 0, 0.455062,-99) , 
0, 96.9181, 0, 0, 0.524807,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560902,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.352973,-99) , 
3, 1.94482, 0, 0, 0.483374,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.257063,-99) , 
8, 0.212238, 0, 0, 0.397722,-99) , 
12, 188.943, 1, 0, 0.493434,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.124102);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53074,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.36971,-99) , 
11, 70.7146, 0, 0, 0.514052,-99) , 
NN(
0, 
0, 
-1, 170.334, 1, -1, 0.39389,-99) , 
14, 2.03123, 1, 0, 0.494275,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.297842,-99) , 
12, 302.502, 1, 0, 0.481252,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.118948);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522184,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.374343,-99) , 
11, 70.7146, 0, 0, 0.508748,-99) , 
NN(
0, 
0, 
-1, 2.39366, 0, -1, 0.388275,-99) , 
15, 0.566831, 1, 0, 0.488204,-99) , 
NN(
0, 
0, 
-1, 188.943, 1, -1, 0.383718,-99) , 
4, 1.54732, 1, 0, 0.467696,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.185798);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.609433,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.338505,-99) , 
9, 0.360786, 1, 0, 0.520352,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519287,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404564,-99) , 
11, 85.9525, 0, 0, 0.458703,-99) , 
NN(
0, 
0, 
-1, 0.714179, 1, -1, 0.335839,-99) , 
6, 337.119, 1, 0, 0.436752,-99) , 
15, 0.353136, 1, 0, 0.460344,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.132683);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548092,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447976,-99) , 
12, 124.422, 1, 0, 0.480646,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.322983,-99) , 
12, 281.344, 1, 0, 0.469649,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.319875,-99) , 
4, 2.02342, 1, 0, 0.461691,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.129133);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54257,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433752,-99) , 
4, 1.19025, 1, 0, 0.502389,-99) , 
NN(
0, 
0, 
-1, 1.78813, 1, -1, 0.41283,-99) , 
6, 224.876, 0, 0, 0.484194,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.362833,-99) , 
10, 1.59976, 1, 0, 0.475525,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0758007);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577754,-99) , 
NN(
0, 
0, 
-1, 205.165, 1, -1, 0.473725,-99) , 
10, 0.123058, 1, 0, 0.484044,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.365527,-99) , 
12, 302.502, 1, 0, 0.476633,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.109308);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.645665,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462571,-99) , 
3, 1.04724, 0, 0, 0.558392,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506777,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.34148,-99) , 
13, 0.867213, 1, 0, 0.478942,-99) , 
7, 1.07461, 0, 0, 0.50117,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394371,-99) , 
13, 1.36259, 1, 0, 0.491957,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.108906);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 82.1431, 1, 1, 0.559518,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.602311,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467596,-99) , 
0, 53.43, 1, 0, 0.484966,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.348482,-99) , 
12, 209.094, 1, 0, 0.470022,-99) , 
6, 463.499, 0, 0, 0.481368,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0854443);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.24399, 0, 1, 0.560158,-99) , 
NN(
0, 
0, 
-1, 206.741, 1, -1, 0.475145,-99) , 
7, 1.04404, 0, 0, 0.504121,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.371517,-99) , 
12, 302.502, 1, 0, 0.495826,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.105685);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.83327, 0, 1, 0.531423,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.566177,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.374966,-99) , 
11, 80.2381, 1, 0, 0.446808,-99) , 
12, 172.719, 1, 0, 0.510667,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391677,-99) , 
12, 302.502, 1, 0, 0.503281,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.142081);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.69557,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490111,-99) , 
15, 0.401979, 0, 0, 0.543632,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522906,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.386375,-99) , 
15, 0.37174, 1, 0, 0.46661,-99) , 
4, 1.07122, 0, 0, 0.509293,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.65249,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452426,-99) , 
11, 72.6193, 1, 0, 0.487641,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.325132,-99) , 
4, 1.19025, 1, 0, 0.460561,-99) , 
15, 0.438614, 1, 0, 0.487087,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.148964);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.672188,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.447271,-99) , 
4, 0.833174, 0, 0, 0.595677,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418174,-99) , 
13, 1.07805, 1, 0, 0.541127,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577277,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524248,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429994,-99) , 
1, 1.00234, 1, 0, 0.467457,-99) , 
6, 464.004, 0, 0, 0.485184,-99) , 
9, 0.541563, 0, 0, 0.501879,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.165812);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.664137,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446568,-99) , 
4, 1.19025, 1, 0, 0.590923,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439216,-99) , 
6, 224.876, 0, 0, 0.5443,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559635,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433653,-99) , 
6, 261.315, 0, 0, 0.513442,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546264,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.395458,-99) , 
2, 0.383747, 1, 0, 0.438424,-99) , 
13, 0.712411, 1, 0, 0.485113,-99) , 
9, 0.541563, 0, 0, 0.502673,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.115853);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.64931,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494265,-99) , 
4, 0.833174, 0, 0, 0.595536,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438721,-99) , 
13, 1.07805, 1, 0, 0.547288,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.60272,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455858,-99) , 
15, 0.331365, 0, 0, 0.537268,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.507971,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.382907,-99) , 
12, 159.154, 1, 0, 0.473233,-99) , 
2, 2.073, 0, 0, 0.48451,-99) , 
9, 0.541563, 0, 0, 0.503081,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.118334);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 87.8571, 0, 1, 0.586957,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46742,-99) , 
13, 1.07805, 1, 0, 0.550097,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539169,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540017,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438237,-99) , 
7, 0.536114, 1, 0, 0.460666,-99) , 
6, 464.004, 0, 0, 0.473026,-99) , 
9, 0.541563, 0, 0, 0.495752,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.10449);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.630631,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457778,-99) , 
4, 1.19025, 1, 0, 0.572223,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464676,-99) , 
6, 224.876, 0, 0, 0.538485,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55748,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476949,-99) , 
3, 1.94481, 0, 0, 0.499881,-99) , 
NN(
0, 
0, 
-1, 0.861409, 1, -1, 0.44385,-99) , 
1, 1.67056, 1, 0, 0.482004,-99) , 
9, 0.541563, 0, 0, 0.498645,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.144311);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.88888, 0, 1, 0.578686,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.554178,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453803,-99) , 
15, 0.338858, 1, 0, 0.495791,-99) , 
9, 0.490216, 0, 0, 0.526709,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.693329,-99) , 
NN(
0, 
0, 
-1, 197.615, 1, -1, 0.423218,-99) , 
7, 1.21357, 0, 0, 0.472334,-99) , 
3, 2.09441, 1, 0, 0.510424,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0996781);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548863,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469689,-99) , 
14, 1.1091, 0, 0, 0.524623,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398905,-99) , 
12, 281.344, 1, 0, 0.516014,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.402911,-99) , 
4, 2.02342, 1, 0, 0.510294,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.116506);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.645176,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533993,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.418758,-99) , 
0, 82.4072, 0, 0, 0.506741,-99) , 
4, 1.78538, 0, 0, 0.528958,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52688,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.403614,-99) , 
3, 0.897626, 0, 0, 0.497484,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.33677,-99) , 
8, 0.152213, 0, 0, 0.481916,-99) , 
13, 0.712411, 1, 0, 0.504313,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.100422);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.617731,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539519,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462644,-99) , 
4, 0.510077, 1, 0, 0.491312,-99) , 
4, 1.78538, 0, 0, 0.511409,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.581344,-99) , 
NN(
0, 
0, 
-1, 1.94175, 1, -1, 0.455039,-99) , 
10, 0.123058, 1, 0, 0.470262,-99) , 
13, 0.712411, 1, 0, 0.489835,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.07033);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559938,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487548,-99) , 
12, 124.422, 1, 0, 0.511785,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.42062,-99) , 
12, 281.344, 1, 0, 0.505611,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.402871,-99) , 
4, 2.02342, 1, 0, 0.500419,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0643641);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58117,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52312,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.470796,-99) , 
2, 1.2686, 1, 0, 0.50621,-99) , 
1, 2.54617, 0, 0, 0.512239,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419899,-99) , 
4, 2.02342, 1, 0, 0.507593,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0593815);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561573,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557078,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.489093,-99) , 
2, 1.91393, 0, 0, 0.503463,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401682,-99) , 
3, 2.57169, 1, 0, 0.495977,-99) , 
3, 2.84239, 0, 0, 0.502089,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0620381);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546736,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579645,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495866,-99) , 
2, 1.91038, 0, 0, 0.511675,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.378188,-99) , 
15, 0.310397, 0, 0, 0.500086,-99) , 
0, 136.169, 0, 0, 0.508795,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.0878973);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 119.518, 1, 1, 0.532726,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542666,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.379975,-99) , 
1, 1.46361, 1, 0, 0.477258,-99) , 
12, 178.364, 1, 0, 0.519522,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.437019,-99) , 
2, 2.87089, 1, 0, 0.514127,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0941801);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.619515,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.542228,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.384245,-99) , 
0, 38.9053, 1, 0, 0.467296,-99) , 
10, 0.984468, 0, 0, 0.531501,-99) , 
NN(
NN(
0, 
0, 
-1, 0.476102, 1, 1, 0.527704,-99) , 
NN(
0, 
0, 
-1, 2.244, 1, -1, 0.459589,-99) , 
10, 0.611296, 1, 0, 0.490466,-99) , 
0, 68.0846, 1, 0, 0.498831,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0764458);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.59327,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.477789,-99) , 
7, 1.32971, 1, 0, 0.546902,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506899,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370457,-99) , 
13, 0.867213, 1, 0, 0.486192,-99) , 
7, 1.07461, 0, 0, 0.503174,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443241,-99) , 
13, 1.36259, 1, 0, 0.498257,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.0722387);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538289,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.573963,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523348,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462635,-99) , 
4, 1.30927, 0, 0, 0.479529,-99) , 
1, 2.65001, 0, 0, 0.485041,-99) , 
3, 2.84239, 0, 0, 0.48997,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.0762163);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53565,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469784,-99) , 
14, 1.36637, 0, 0, 0.503255,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436411,-99) , 
12, 281.344, 1, 0, 0.498699,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405809,-99) , 
4, 2.02342, 1, 0, 0.494032,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.103394);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.719413, 0, 1, 0.551882,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.428878,-99) , 
11, 76.4288, 0, 0, 0.524814,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537326,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.590444,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451437,-99) , 
3, 2.84239, 0, 0, 0.469734,-99) , 
0, 123.611, 0, 0, 0.486226,-99) , 
1, 0.731797, 1, 0, 0.495828,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0740885);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.638227,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483758,-99) , 
1, 1.5082, 0, 0, 0.565305,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508827,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438788,-99) , 
1, 2.02452, 1, 0, 0.4972,-99) , 
11, 97.381, 0, 0, 0.506465,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557079,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.38304,-99) , 
3, 2.94213, 0, 0, 0.456661,-99) , 
3, 2.5432, 1, 0, 0.498204,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.107736);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.604733,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530874,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.445049,-99) , 
4, 1.07122, 0, 0, 0.492056,-99) , 
11, 97.381, 0, 0, 0.505756,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.600199,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.468776,-99) , 
11, 72.6193, 1, 0, 0.491474,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.361768,-99) , 
4, 1.19025, 1, 0, 0.470235,-99) , 
15, 0.438614, 1, 0, 0.489539,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0796414);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556555,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486131,-99) , 
12, 119.518, 1, 0, 0.509932,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533365,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.412206,-99) , 
9, 0.370351, 1, 0, 0.471356,-99) , 
12, 178.364, 1, 0, 0.499901,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405696,-99) , 
4, 2.02342, 1, 0, 0.49518,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.109961);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.611253,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462627,-99) , 
6, 266.096, 0, 0, 0.5361,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539091,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458971,-99) , 
14, 1.24875, 0, 0, 0.504437,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.30682,-99) , 
13, 1.36259, 1, 0, 0.491694,-99) , 
4, 0.357078, 1, 0, 0.500818,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.109221);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559825,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484527,-99) , 
11, 82.143, 0, 0, 0.523991,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.37969,-99) , 
12, 167.312, 1, 0, 0.510394,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.58171,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.458142,-99) , 
7, 1.14798, 0, 0, 0.504131,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.356126,-99) , 
11, 91.6666, 1, 0, 0.462734,-99) , 
12, 188.943, 1, 0, 0.499412,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0892091);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.564126,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488416,-99) , 
11, 82.143, 1, 0, 0.526388,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525473,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400048,-99) , 
12, 166.008, 1, 0, 0.503416,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.371209,-99) , 
6, 344.188, 1, 0, 0.488577,-99) , 
9, 0.370351, 1, 0, 0.503371,-99)    );
  // itree = 52
  fBoostWeights.push_back(0.0630977);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 1.94481, 0, 1, 0.526393,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510488,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.442238,-99) , 
4, 1.19025, 1, 0, 0.489223,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.383567,-99) , 
2, 2.39241, 1, 0, 0.478126,-99) , 
9, 0.370351, 1, 0, 0.497023,-99)    );
  // itree = 53
  fBoostWeights.push_back(0.0841985);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.61246,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.432663,-99) , 
6, 320.374, 1, 0, 0.533613,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517881,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464533,-99) , 
3, 1.19682, 1, 0, 0.488975,-99) , 
0, 68.0846, 1, 0, 0.498145,-99) , 
NN(
0, 
0, 
-1, 1.78813, 1, -1, 0.453691,-99) , 
6, 224.876, 0, 0, 0.488563,-99)    );
  // itree = 54
  fBoostWeights.push_back(0.0738525);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587546,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467625,-99) , 
6, 266.096, 0, 0, 0.526709,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587649,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487008,-99) , 
7, 1.09829, 0, 0, 0.498571,-99) , 
NN(
0, 
0, 
-1, 1.20793, 1, -1, 0.429991,-99) , 
7, 1.21357, 1, 0, 0.485222,-99) , 
4, 0.357078, 1, 0, 0.493735,-99)    );
   return;
};
 
// Clean up
inline void ReaddarkHiggsVWjets_2017_BDT_55Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_16Var::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReaddarkHiggsVWjets_2017_BDT_55Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_16Var::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
