// Class: Read2HDMaVWjets_2017_BDT_52Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_12Var
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::2HDMaVWjets_2017_BDT_52Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_12Var
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : svanputt
Date           : Wed Apr 22 22:14:00 2020
Host           : Linux vocms0315.cern.ch 2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 09:23:05 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /scratch/40001614.cream02.iihe.ac.be/52Trees
Training events: 437017
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "True" [Print method-specific help message]
NTrees: "52" [Number of trees in the forest]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
SeparationType: "giniindex" [Separation criterion for node splitting]
PruneMethod: "costcomplexity" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "1.200000e+01" [Pruning strength]
# Default:
VerbosityLevel: "Verbose" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "4" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 12
mtw1                          mtw1                          mtw1                          mtw1                                                            'F'    [0,1316.13671875]
MHlnjj_dphi_ljjVmet           MHlnjj_dphi_ljjVmet           MHlnjj_dphi_ljjVmet           MHlnjj_dphi_ljjVmet                                             'F'    [1.16606834126e-05,3.14159178734]
MHlnjj_dphi_jjVl              MHlnjj_dphi_jjVl              MHlnjj_dphi_jjVl              MHlnjj_dphi_jjVl                                                'F'    [4.14871465182e-05,3.14158701897]
MHlnjj_deta_lVmet             MHlnjj_deta_lVmet             MHlnjj_deta_lVmet             MHlnjj_deta_lVmet                                               'F'    [1.0596588254e-05,2.49951171875]
PuppiMET_pt                   PuppiMET_pt                   PuppiMET_pt                   PuppiMET_pt                                                     'F'    [50.0001335144,1523.65405273]
MHlnjj_pt_ljj                 MHlnjj_pt_ljj                 MHlnjj_pt_ljj                 MHlnjj_pt_ljj                                                   'F'    [0.11474018544,1025.22814941]
MHlnjj_PTljj_D_Mlmetjj        MHlnjj_PTljj_D_Mlmetjj        MHlnjj_PTljj_D_Mlmetjj        MHlnjj_PTljj_D_Mlmetjj                                          'F'    [0.000469836377306,3.65420365334]
MHlnjj_MINPTlj_D_Mlmetjj      MHlnjj_MINPTlj_D_Mlmetjj      MHlnjj_MINPTlj_D_Mlmetjj      MHlnjj_MINPTlj_D_Mlmetjj                                        'F'    [0.0134515520185,0.638022661209]
MHlnjj_m_jj                   MHlnjj_m_jj                   MHlnjj_m_jj                   MHlnjj_m_jj                                                     'F'    [65.0002822876,104.999908447]
MHlnjj_m_ljj                  MHlnjj_m_ljj                  MHlnjj_m_ljj                  MHlnjj_m_ljj                                                    'F'    [74.5745773315,2237.96362305]
MHlnjj_MAXPTlj_D_PTmet        MHlnjj_MAXPTlj_D_PTmet        MHlnjj_MAXPTlj_D_PTmet        MHlnjj_MAXPTlj_D_PTmet                                          'F'    [0.0414094999433,13.7160482407]
MHlnjj_MTljj_D_Mlmetjj        MHlnjj_MTljj_D_Mlmetjj        MHlnjj_MTljj_D_Mlmetjj        MHlnjj_MTljj_D_Mlmetjj                                          'F'    [0.059488967061,0.938192307949]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new 2HDMaVWjets_2017_BDT_52Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_12VarNode
   
#ifndef 2HDMaVWjets_2017_BDT_52Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_12VarNode__def
#define 2HDMaVWjets_2017_BDT_52Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_12VarNode__def
   
class 2HDMaVWjets_2017_BDT_52Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_12VarNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   2HDMaVWjets_2017_BDT_52Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_12VarNode ( 2HDMaVWjets_2017_BDT_52Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_12VarNode* left,2HDMaVWjets_2017_BDT_52Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_12VarNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~2HDMaVWjets_2017_BDT_52Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_12VarNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   2HDMaVWjets_2017_BDT_52Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_12VarNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   2HDMaVWjets_2017_BDT_52Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_12VarNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   2HDMaVWjets_2017_BDT_52Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_12VarNode*   fLeft;     // pointer to the left daughter node
   2HDMaVWjets_2017_BDT_52Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_12VarNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   2HDMaVWjets_2017_BDT_52Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_12VarNode::~2HDMaVWjets_2017_BDT_52Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_12VarNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool 2HDMaVWjets_2017_BDT_52Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_12VarNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool 2HDMaVWjets_2017_BDT_52Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_12VarNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class Read2HDMaVWjets_2017_BDT_52Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_12Var : public IClassifierReader {

 public:

   // constructor
   Read2HDMaVWjets_2017_BDT_52Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_12Var( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "Read2HDMaVWjets_2017_BDT_52Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_12Var" ),
        fNvars( 12 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "mtw1", "MHlnjj_dphi_ljjVmet", "MHlnjj_dphi_jjVl", "MHlnjj_deta_lVmet", "PuppiMET_pt", "MHlnjj_pt_ljj", "MHlnjj_PTljj_D_Mlmetjj", "MHlnjj_MINPTlj_D_Mlmetjj", "MHlnjj_m_jj", "MHlnjj_m_ljj", "MHlnjj_MAXPTlj_D_PTmet", "MHlnjj_MTljj_D_Mlmetjj" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~Read2HDMaVWjets_2017_BDT_52Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_12Var() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[12];
   double fVmax[12];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[12];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<2HDMaVWjets_2017_BDT_52Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_12VarNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double Read2HDMaVWjets_2017_BDT_52Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_12Var::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      2HDMaVWjets_2017_BDT_52Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_12VarNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(2HDMaVWjets_2017_BDT_52Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_12VarNode*)current->GetRight();
         else current=(2HDMaVWjets_2017_BDT_52Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_12VarNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void Read2HDMaVWjets_2017_BDT_52Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_12Var::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.647187461869894);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.883301,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.727403,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.385968,-99) , 
10, 0.5648, 1, 0, 0.574942,-99) , 
NN(
0, 
0, 
-1, 97.7446, 0, -1, 0.221269,-99) , 
10, 0.719525, 1, 0, 0.341283,-99) , 
0, 125.346, 0, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.540978);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.78023,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.667968,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.370526,-99) , 
9, 150.956, 1, 0, 0.566771,-99) , 
NN(
0, 
0, 
-1, 1.54732, 1, -1, 0.218403,-99) , 
2, 1.64561, 1, 0, 0.356836,-99) , 
4, 120.174, 0, 0, 0.491867,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.36325);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.700451,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.648041,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.492198,-99) , 
2, 1.19682, 1, 0, 0.579568,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.53638,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.283194,-99) , 
0, 107.439, 0, 0, 0.32122,-99) , 
6, 0.348444, 0, 0, 0.383001,-99) , 
0, 125.346, 0, 0, 0.463861,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.322915);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.739088,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546141,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.330066,-99) , 
3, 1.30927, 1, 0, 0.476045,-99) , 
9, 177.593, 1, 0, 0.605321,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.586262,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.388217,-99) , 
5, 79.1491, 0, 0, 0.428762,-99) , 
NN(
0, 
0, 
-1, 0.161387, 0, -1, 0.258386,-99) , 
10, 0.916035, 1, 0, 0.370522,-99) , 
5, 97.7446, 0, 0, 0.461178,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.236623);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.666078,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55039,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.411033,-99) , 
10, 0.719525, 1, 0, 0.462303,-99) , 
NN(
0, 
0, 
-1, 1.95543, 1, -1, 0.259762,-99) , 
3, 1.54732, 1, 0, 0.424522,-99) , 
11, 0.310547, 1, 0, 0.46654,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.216031);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.676814,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547503,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394754,-99) , 
1, 2.6928, 1, 0, 0.481291,-99) , 
11, 0.357497, 1, 0, 0.534656,-99) , 
NN(
0, 
0, 
-1, 1.90439, 1, -1, 0.386794,-99) , 
9, 177.593, 1, 0, 0.469616,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.189762);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.612861,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556327,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.424597,-99) , 
0, 47.7506, 1, 0, 0.456495,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.255567,-99) , 
3, 1.90439, 1, 0, 0.436471,-99) , 
0, 125.346, 0, 0, 0.476835,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.177883);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.587015,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.589504,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.433985,-99) , 
4, 96.7818, 0, 0, 0.462132,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.255649,-99) , 
3, 1.90439, 1, 0, 0.440612,-99) , 
4, 120.174, 0, 0, 0.482093,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.175456);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.714156, 1, 1, 0.624582,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520819,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.422489,-99) , 
7, 0.113913, 1, 0, 0.464019,-99) , 
9, 133.442, 1, 0, 0.513182,-99) , 
NN(
0, 
0, 
-1, 1.19027, 1, -1, 0.344042,-99) , 
9, 280.612, 1, 0, 0.489004,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.11643);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.16645, 0, 1, 0.563247,-99) , 
NN(
0, 
0, 
-1, 283.229, 1, -1, 0.467594,-99) , 
3, 0.544092, 1, 0, 0.502364,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.31009,-99) , 
3, 1.90439, 1, 0, 0.483521,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.142859);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.589243,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55065,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444863,-99) , 
0, 89.5324, 0, 0, 0.485911,-99) , 
0, 125.346, 0, 0, 0.507858,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.335532,-99) , 
3, 1.90439, 1, 0, 0.491304,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.124854);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548338,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.464657,-99) , 
8, 89.7619, 1, 0, 0.524799,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.366795,-99) , 
11, 0.652985, 1, 0, 0.512182,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520361,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.451844,-99) , 
8, 82.1434, 0, 0, 0.487704,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.325451,-99) , 
6, 0.221263, 0, 0, 0.409521,-99) , 
3, 1.54732, 1, 0, 0.490826,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.0787348);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.57026,-99) , 
NN(
0, 
0, 
-1, 1.78537, 1, -1, 0.466455,-99) , 
11, 0.310547, 1, 0, 0.482689,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.133617);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.585004,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478573,-99) , 
9, 142.451, 1, 0, 0.522125,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561904,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.286096,-99) , 
0, 79.737, 1, 0, 0.429826,-99) , 
10, 1.34376, 1, 0, 0.507467,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.383823,-99) , 
3, 1.90439, 1, 0, 0.495944,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.162062);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.79524, 1, 1, 0.589117,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.413825,-99) , 
10, 1.37982, 1, 0, 0.548029,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.655609,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423718,-99) , 
1, 2.39362, 1, 0, 0.538173,-99) , 
NN(
0, 
0, 
-1, 0.136386, 1, -1, 0.443535,-99) , 
7, 0.148604, 0, 0, 0.474061,-99) , 
5, 97.7446, 0, 0, 0.501739,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.137905);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565876,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574481,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39655,-99) , 
1, 2.992, 1, 0, 0.541017,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.572072,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439873,-99) , 
0, 107.439, 0, 0, 0.466655,-99) , 
2, 2.3936, 0, 0, 0.49518,-99) , 
0, 125.346, 0, 0, 0.50992,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.0757824);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.581158,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511867,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.40507,-99) , 
9, 243.235, 1, 0, 0.50182,-99) , 
9, 123.631, 1, 0, 0.516759,-99) , 
NN(
0, 
0, 
-1, 0.477919, 1, -1, 0.422066,-99) , 
9, 280.612, 1, 0, 0.503448,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0680006);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559347,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495985,-99) , 
3, 1.10509, 0, 0, 0.513475,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501673,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.351678,-99) , 
2, 2.09442, 1, 0, 0.44261,-99) , 
3, 1.54732, 1, 0, 0.497766,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391345,-99) , 
11, 0.645291, 1, 0, 0.490143,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0806783);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.515713, 1, 1, 0.52,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409906,-99) , 
11, 0.652985, 1, 0, 0.511273,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541046,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.398551,-99) , 
8, 82.1431, 1, 0, 0.4746,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.337057,-99) , 
2, 2.39361, 1, 0, 0.434552,-99) , 
3, 1.54732, 1, 0, 0.495382,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.1031);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547981,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529131,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438852,-99) , 
6, 0.247321, 0, 0, 0.48773,-99) , 
9, 148.042, 1, 0, 0.513465,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528881,-99) , 
NN(
0, 
0, 
-1, 1.22431, 0, -1, 0.436468,-99) , 
5, 128.096, 0, 0, 0.457523,-99) , 
3, 0.714154, 1, 0, 0.4813,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0920286);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.546995,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.548578,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46085,-99) , 
10, 1.26149, 0, 0, 0.474671,-99) , 
0, 125.346, 0, 0, 0.489038,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.380141,-99) , 
10, 1.99493, 1, 0, 0.483469,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.096873);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.593165,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514324,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410813,-99) , 
10, 0.555047, 0, 0, 0.492734,-99) , 
11, 0.288971, 1, 0, 0.505265,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522754,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.311964,-99) , 
0, 79.737, 1, 0, 0.422064,-99) , 
10, 1.34376, 1, 0, 0.491643,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0789632);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568586,-99) , 
NN(
0, 
0, 
-1, 1.90439, 1, -1, 0.476097,-99) , 
11, 0.288971, 1, 0, 0.487541,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.514224,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.45524,-99) , 
3, 0.833201, 1, 0, 0.484228,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.304879,-99) , 
2, 2.39368, 0, 0, 0.418198,-99) , 
10, 1.34376, 1, 0, 0.476247,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.075178);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.544203,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490684,-99) , 
9, 142.451, 1, 0, 0.512263,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400634,-99) , 
3, 1.90439, 1, 0, 0.502316,-99) , 
NN(
0, 
0, 
-1, 79.737, 1, -1, 0.424491,-99) , 
10, 1.34376, 1, 0, 0.489678,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0960916);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.537342,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.69897,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.496671,-99) , 
3, 1.30927, 0, 0, 0.576855,-99) , 
NN(
0, 
0, 
-1, 1.55274, 1, -1, 0.456406,-99) , 
0, 56.7763, 1, 0, 0.48237,-99) , 
4, 120.174, 0, 0, 0.496728,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.100348);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 123.558, 1, 1, 0.54817,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504263,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.383655,-99) , 
11, 0.518754, 1, 0, 0.466362,-99) , 
9, 187.04, 1, 0, 0.516081,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531115,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.393014,-99) , 
2, 2.3936, 0, 0, 0.450014,-99) , 
8, 72.6193, 0, 0, 0.504873,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.0569747);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530434,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.487871,-99) , 
3, 0.481663, 1, 0, 0.501493,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416701,-99) , 
8, 68.8098, 0, 0, 0.49519,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.389986,-99) , 
3, 2.02342, 1, 0, 0.488415,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.0711305);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553064,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486039,-99) , 
3, 1.15598, 0, 0, 0.509083,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502203,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.373574,-99) , 
3, 1.05966, 1, 0, 0.444282,-99) , 
9, 280.612, 1, 0, 0.500791,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.403622,-99) , 
3, 2.02342, 1, 0, 0.494565,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0832533);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.559242,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520172,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.414378,-99) , 
2, 1.19682, 0, 0, 0.497698,-99) , 
9, 123.631, 1, 0, 0.508996,-99) , 
NN(
0, 
0, 
-1, 1.19027, 1, -1, 0.440735,-99) , 
9, 280.612, 1, 0, 0.499585,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0698796);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517701,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479492,-99) , 
8, 79.1498, 0, 0, 0.505887,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426174,-99) , 
8, 68.8098, 0, 0, 0.499992,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539268,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.416796,-99) , 
1, 2.6928, 1, 0, 0.487067,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.35951,-99) , 
2, 2.39361, 1, 0, 0.450174,-99) , 
3, 1.54732, 1, 0, 0.489702,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.0800073);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529004,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434443,-99) , 
1, 1.79522, 0, 0, 0.511298,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510158,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423137,-99) , 
1, 2.69279, 1, 0, 0.473853,-99) , 
11, 0.436076, 1, 0, 0.490554,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417569,-99) , 
3, 2.02342, 1, 0, 0.485915,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.0757428);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534433,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.47083,-99) , 
2, 2.39359, 0, 0, 0.493124,-99) , 
NN(
0, 
0, 
-1, 2.09442, 1, -1, 0.453646,-99) , 
3, 1.54732, 1, 0, 0.484438,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41711,-99) , 
11, 0.645291, 1, 0, 0.479705,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.0830903);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54766,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517324,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.478178,-99) , 
3, 0.634773, 1, 0, 0.49574,-99) , 
3, 1.90439, 0, 0, 0.500443,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550495,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.359306,-99) , 
8, 87.857, 1, 0, 0.496128,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.309029,-99) , 
10, 1.05727, 1, 0, 0.450496,-99) , 
6, 0.174457, 0, 0, 0.488769,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0829808);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543317,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453163,-99) , 
1, 1.9448, 0, 0, 0.523267,-99) , 
NN(
0, 
0, 
-1, 0.725449, 1, -1, 0.480399,-99) , 
3, 0.952201, 0, 0, 0.500141,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527125,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429667,-99) , 
8, 84.0476, 1, 0, 0.486398,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.327047,-99) , 
10, 1.05727, 1, 0, 0.447857,-99) , 
6, 0.174457, 0, 0, 0.487982,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.0829007);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.592522,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.463262,-99) , 
4, 96.9515, 1, 0, 0.529525,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508481,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409292,-99) , 
10, 1.37982, 1, 0, 0.496997,-99) , 
0, 62.6732, 1, 0, 0.505698,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528686,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415085,-99) , 
9, 205.129, 1, 0, 0.482372,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.335655,-99) , 
8, 76.4287, 0, 0, 0.449629,-99) , 
6, 0.174457, 0, 0, 0.492696,-99)    );
  // itree = 35
  fBoostWeights.push_back(0.0773913);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547273,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.541649,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479038,-99) , 
0, 125.346, 0, 0, 0.493888,-99) , 
NN(
0, 
0, 
-1, 0.468764, 1, -1, 0.416067,-99) , 
5, 47.6637, 0, 0, 0.477819,-99) , 
1, 0.598408, 1, 0, 0.483431,-99)    );
  // itree = 36
  fBoostWeights.push_back(0.031717);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55019,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49738,-99) , 
8, 99.2857, 0, 0, 0.502849,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446081,-99) , 
11, 0.645291, 1, 0, 0.498582,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43648,-99) , 
3, 1.90439, 1, 0, 0.492877,-99)    );
  // itree = 37
  fBoostWeights.push_back(0.0335439);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528067,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499213,-99) , 
2, 2.39359, 0, 0, 0.509102,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.453931,-99) , 
11, 0.645291, 1, 0, 0.504961,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.444297,-99) , 
3, 1.90439, 1, 0, 0.499397,-99)    );
  // itree = 38
  fBoostWeights.push_back(0.0915907);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.594364,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450636,-99) , 
8, 85.9522, 1, 0, 0.548426,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.519932,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.449418,-99) , 
3, 1.30927, 1, 0, 0.500763,-99) , 
0, 62.6732, 1, 0, 0.513539,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.522842,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.439337,-99) , 
3, 1.42833, 1, 0, 0.498328,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.366249,-99) , 
10, 1.05727, 1, 0, 0.467133,-99) , 
6, 0.174457, 0, 0, 0.502863,-99)    );
  // itree = 39
  fBoostWeights.push_back(0.0847369);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.627544,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497042,-99) , 
3, 1.30929, 0, 0, 0.540047,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524651,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469194,-99) , 
8, 87.8573, 0, 0, 0.489954,-99) , 
0, 62.6732, 1, 0, 0.503336,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.55894,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.513449,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.334064,-99) , 
11, 0.480397, 1, 0, 0.436008,-99) , 
6, 0.157886, 0, 0, 0.464804,-99) , 
6, 0.174457, 0, 0, 0.494481,-99)    );
  // itree = 40
  fBoostWeights.push_back(0.08146);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582826,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.488577,-99) , 
8, 84.0475, 1, 0, 0.5472,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533203,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.479281,-99) , 
4, 109.909, 0, 0, 0.495045,-99) , 
0, 62.6732, 1, 0, 0.508964,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523928,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.41344,-99) , 
8, 90.034, 1, 0, 0.483937,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.360537,-99) , 
8, 76.4287, 0, 0, 0.456699,-99) , 
6, 0.174457, 0, 0, 0.496977,-99)    );
  // itree = 41
  fBoostWeights.push_back(0.0765128);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.90439, 0, 1, 0.522951,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534942,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.399071,-99) , 
2, 1.64556, 1, 0, 0.476471,-99) , 
8, 93.5714, 1, 0, 0.513785,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539816,-99) , 
NN(
0, 
0, 
-1, 0.480397, 1, -1, 0.430279,-99) , 
6, 0.157886, 0, 0, 0.456179,-99) , 
6, 0.174457, 0, 0, 0.500594,-99)    );
  // itree = 42
  fBoostWeights.push_back(0.0651778);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5674,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484512,-99) , 
4, 96.9515, 1, 0, 0.526874,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50016,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.44387,-99) , 
2, 2.0944, 1, 0, 0.486955,-99) , 
0, 62.6732, 1, 0, 0.497571,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553208,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.427553,-99) , 
9, 191.027, 1, 0, 0.495947,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.410075,-99) , 
8, 80.2382, 0, 0, 0.465922,-99) , 
6, 0.174457, 0, 0, 0.490339,-99)    );
  // itree = 43
  fBoostWeights.push_back(0.10047);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.622883,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490628,-99) , 
3, 1.07123, 0, 0, 0.542229,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526182,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423497,-99) , 
1, 2.54322, 1, 0, 0.472954,-99) , 
6, 0.268115, 0, 0, 0.496196,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511535,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430222,-99) , 
5, 64.1546, 0, 0, 0.490027,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.381452,-99) , 
10, 1.01362, 1, 0, 0.468306,-99) , 
2, 1.49602, 0, 0, 0.486232,-99)    );
  // itree = 44
  fBoostWeights.push_back(0.109126);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 2.43633, 0, 1, 0.547795,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.577603,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452905,-99) , 
3, 0.238061, 1, 0, 0.473381,-99) , 
6, 0.268115, 0, 0, 0.498338,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531481,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430625,-99) , 
9, 125.587, 1, 0, 0.480801,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400589,-99) , 
9, 171.964, 1, 0, 0.463641,-99) , 
2, 1.49602, 0, 0, 0.485941,-99)    );
  // itree = 45
  fBoostWeights.push_back(0.100967);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545146,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441378,-99) , 
4, 120.174, 1, 0, 0.519059,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561904,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406215,-99) , 
11, 0.41289, 1, 0, 0.463227,-99) , 
8, 78.3335, 0, 0, 0.501167,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50472,-99) , 
NN(
0, 
0, 
-1, 1.54736, 0, -1, 0.448678,-99) , 
8, 78.3335, 1, 0, 0.46935,-99) , 
2, 1.49602, 0, 0, 0.489809,-99)    );
  // itree = 46
  fBoostWeights.push_back(0.0755274);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533486,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.596205,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.486647,-99) , 
8, 99.2857, 0, 0, 0.500483,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.516925,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.402641,-99) , 
7, 0.151099, 0, 0, 0.466014,-99) , 
7, 0.126753, 1, 0, 0.483501,-99) , 
7, 0.0729345, 1, 0, 0.487663,-99)    );
  // itree = 47
  fBoostWeights.push_back(0.0771261);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534495,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491134,-99) , 
11, 0.366338, 0, 0, 0.514856,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.511084,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.404635,-99) , 
11, 0.579538, 1, 0, 0.458162,-99) , 
11, 0.519762, 1, 0, 0.505244,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549298,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.462071,-99) , 
2, 2.09439, 0, 0, 0.497925,-99) , 
NN(
0, 
0, 
-1, 1.79524, 1, -1, 0.427023,-99) , 
1, 2.69279, 1, 0, 0.471433,-99) , 
7, 0.132417, 1, 0, 0.491573,-99)    );
  // itree = 48
  fBoostWeights.push_back(0.0568433);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.536391,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.584759,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.481231,-99) , 
10, 1.08286, 0, 0, 0.526927,-99) , 
NN(
0, 
0, 
-1, 0.549651, 1, -1, 0.477775,-99) , 
0, 42.5653, 1, 0, 0.486903,-99) , 
11, 0.310547, 1, 0, 0.49427,-99)    );
  // itree = 49
  fBoostWeights.push_back(0.0825953);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.383203, 0, 1, 0.549103,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.524584,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.436176,-99) , 
2, 1.64561, 1, 0, 0.502609,-99) , 
6, 0.205875, 1, 0, 0.517335,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526153,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.40511,-99) , 
2, 2.84239, 1, 0, 0.506521,-99) , 
NN(
0, 
0, 
-1, 2.39365, 0, -1, 0.441329,-99) , 
8, 78.3335, 0, 0, 0.48858,-99) , 
11, 0.436076, 1, 0, 0.502229,-99)    );
  // itree = 50
  fBoostWeights.push_back(0.067143);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.582817,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.494425,-99) , 
6, 0.268115, 0, 0, 0.521185,-99) , 
NN(
0, 
0, 
-1, 1.00315, 1, -1, 0.480655,-99) , 
2, 1.94481, 0, 0, 0.501719,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531608,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.455149,-99) , 
5, 95.5009, 1, 0, 0.497637,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.363887,-99) , 
5, 49.0143, 0, 0, 0.471989,-99) , 
8, 89.762, 1, 0, 0.493207,-99)    );
  // itree = 51
  fBoostWeights.push_back(0.0751205);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547068,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.490119,-99) , 
0, 81.3478, 0, 0, 0.523021,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518722,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430158,-99) , 
3, 1.07123, 0, 0, 0.470526,-99) , 
1, 2.99199, 1, 0, 0.513216,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523106,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466666,-99) , 
2, 1.6456, 1, 0, 0.49555,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.379566,-99) , 
5, 49.0143, 0, 0, 0.473435,-99) , 
8, 89.762, 1, 0, 0.501842,-99)    );
   return;
};
 
// Clean up
inline void Read2HDMaVWjets_2017_BDT_52Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_12Var::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double Read2HDMaVWjets_2017_BDT_52Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_12Var::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
