// Class: Read2HDMaWjetsSRetaAda_2017_BDT_35Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21Var
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::2HDMaWjetsSRetaAda_2017_BDT_35Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21Var
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : svanputt
Date           : Mon Mar 30 20:47:24 2020
Host           : Linux vocms0315.cern.ch 2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 09:23:05 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /storage_mnt/storage/user/svanputt/monoHiggs/MVA/CMSSW_8_0_17/src/UATmva
Training events: 437017
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "True" [Print method-specific help message]
NTrees: "35" [Number of trees in the forest]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
SeparationType: "giniindex" [Separation criterion for node splitting]
PruneMethod: "costcomplexity" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "1.200000e+01" [Pruning strength]
# Default:
VerbosityLevel: "Verbose" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "5" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 21
mtw1                          mtw1                          mtw1                          mtw1                                                            'F'    [0,1316.13671875]
MHlnjj_deta_ljjVmet           MHlnjj_deta_ljjVmet           MHlnjj_deta_ljjVmet           MHlnjj_deta_ljjVmet                                             'F'    [1.84355883448e-06,7.9948887825]
MHlnjj_dphi_ljjVmet           MHlnjj_dphi_ljjVmet           MHlnjj_dphi_ljjVmet           MHlnjj_dphi_ljjVmet                                             'F'    [1.16606834126e-05,3.14159178734]
MHlnjj_deta_jjVl              MHlnjj_deta_jjVl              MHlnjj_deta_jjVl              MHlnjj_deta_jjVl                                                'F'    [4.67996233056e-06,10.0481100082]
MHlnjj_dphi_jjVl              MHlnjj_dphi_jjVl              MHlnjj_dphi_jjVl              MHlnjj_dphi_jjVl                                                'F'    [4.14871465182e-05,3.14158701897]
MHlnjj_dphi_lVmet             MHlnjj_dphi_lVmet             MHlnjj_dphi_lVmet             MHlnjj_dphi_lVmet                                               'F'    [0,3.14158368111]
MHlnjj_deta_lVmet             MHlnjj_deta_lVmet             MHlnjj_deta_lVmet             MHlnjj_deta_lVmet                                               'F'    [1.0596588254e-05,2.49951171875]
PuppiMET_pt                   PuppiMET_pt                   PuppiMET_pt                   PuppiMET_pt                                                     'F'    [50.0001335144,1523.65405273]
MHlnjj_pt_ljj                 MHlnjj_pt_ljj                 MHlnjj_pt_ljj                 MHlnjj_pt_ljj                                                   'F'    [0.11474018544,1025.22814941]
MHlnjj_m_lmetjj               MHlnjj_m_lmetjj               MHlnjj_m_lmetjj               MHlnjj_m_lmetjj                                                 'F'    [105.564781189,2536.88208008]
MHlnjj_PTljj_D_PTmet          MHlnjj_PTljj_D_PTmet          MHlnjj_PTljj_D_PTmet          MHlnjj_PTljj_D_PTmet                                            'F'    [0.00212299986742,12.7120838165]
MHlnjj_PTljj_D_Mlmetjj        MHlnjj_PTljj_D_Mlmetjj        MHlnjj_PTljj_D_Mlmetjj        MHlnjj_PTljj_D_Mlmetjj                                          'F'    [0.000469836377306,3.65420365334]
MHlnjj_MINPTlj_D_PTmet        MHlnjj_MINPTlj_D_PTmet        MHlnjj_MINPTlj_D_PTmet        MHlnjj_MINPTlj_D_PTmet                                          'F'    [0.0209071692079,3.49794340134]
MHlnjj_MINPTlj_D_Mlmetjj      MHlnjj_MINPTlj_D_Mlmetjj      MHlnjj_MINPTlj_D_Mlmetjj      MHlnjj_MINPTlj_D_Mlmetjj                                        'F'    [0.0134515520185,0.638022661209]
MHlnjj_dphi_jVj               MHlnjj_dphi_jVj               MHlnjj_dphi_jVj               MHlnjj_dphi_jVj                                                 'F'    [0,3.1415913105]
MHlnjj_deta_jVj               MHlnjj_deta_jVj               MHlnjj_deta_jVj               MHlnjj_deta_jVj                                                 'F'    [0,2.59130859375]
MHlnjj_m_jj                   MHlnjj_m_jj                   MHlnjj_m_jj                   MHlnjj_m_jj                                                     'F'    [65.0002822876,104.999908447]
MHlnjj_m_ljj                  MHlnjj_m_ljj                  MHlnjj_m_ljj                  MHlnjj_m_ljj                                                    'F'    [74.5745773315,2237.96362305]
MHlnjj_MAXPTlj_D_PTmet        MHlnjj_MAXPTlj_D_PTmet        MHlnjj_MAXPTlj_D_PTmet        MHlnjj_MAXPTlj_D_PTmet                                          'F'    [0.0414094999433,13.7160482407]
MHlnjj_MTljj_D_PTmet          MHlnjj_MTljj_D_PTmet          MHlnjj_MTljj_D_PTmet          MHlnjj_MTljj_D_PTmet                                            'F'    [0.0818054527044,20.0676307678]
MHlnjj_MTljj_D_Mlmetjj        MHlnjj_MTljj_D_Mlmetjj        MHlnjj_MTljj_D_Mlmetjj        MHlnjj_MTljj_D_Mlmetjj                                          'F'    [0.059488967061,0.938192307949]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new 2HDMaWjetsSRetaAda_2017_BDT_35Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode
   
#ifndef 2HDMaWjetsSRetaAda_2017_BDT_35Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode__def
#define 2HDMaWjetsSRetaAda_2017_BDT_35Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode__def
   
class 2HDMaWjetsSRetaAda_2017_BDT_35Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   2HDMaWjetsSRetaAda_2017_BDT_35Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode ( 2HDMaWjetsSRetaAda_2017_BDT_35Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode* left,2HDMaWjetsSRetaAda_2017_BDT_35Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~2HDMaWjetsSRetaAda_2017_BDT_35Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   2HDMaWjetsSRetaAda_2017_BDT_35Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   2HDMaWjetsSRetaAda_2017_BDT_35Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   2HDMaWjetsSRetaAda_2017_BDT_35Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode*   fLeft;     // pointer to the left daughter node
   2HDMaWjetsSRetaAda_2017_BDT_35Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   2HDMaWjetsSRetaAda_2017_BDT_35Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode::~2HDMaWjetsSRetaAda_2017_BDT_35Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool 2HDMaWjetsSRetaAda_2017_BDT_35Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool 2HDMaWjetsSRetaAda_2017_BDT_35Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class Read2HDMaWjetsSRetaAda_2017_BDT_35Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21Var : public IClassifierReader {

 public:

   // constructor
   Read2HDMaWjetsSRetaAda_2017_BDT_35Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21Var( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "Read2HDMaWjetsSRetaAda_2017_BDT_35Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21Var" ),
        fNvars( 21 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "mtw1", "MHlnjj_deta_ljjVmet", "MHlnjj_dphi_ljjVmet", "MHlnjj_deta_jjVl", "MHlnjj_dphi_jjVl", "MHlnjj_dphi_lVmet", "MHlnjj_deta_lVmet", "PuppiMET_pt", "MHlnjj_pt_ljj", "MHlnjj_m_lmetjj", "MHlnjj_PTljj_D_PTmet", "MHlnjj_PTljj_D_Mlmetjj", "MHlnjj_MINPTlj_D_PTmet", "MHlnjj_MINPTlj_D_Mlmetjj", "MHlnjj_dphi_jVj", "MHlnjj_deta_jVj", "MHlnjj_m_jj", "MHlnjj_m_ljj", "MHlnjj_MAXPTlj_D_PTmet", "MHlnjj_MTljj_D_PTmet", "MHlnjj_MTljj_D_Mlmetjj" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;
      fVmin[17] = 0;
      fVmax[17] = 0;
      fVmin[18] = 0;
      fVmax[18] = 0;
      fVmin[19] = 0;
      fVmax[19] = 0;
      fVmin[20] = 0;
      fVmax[20] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';
      fType[20] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~Read2HDMaWjetsSRetaAda_2017_BDT_35Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21Var() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[21];
   double fVmax[21];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[21];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<2HDMaWjetsSRetaAda_2017_BDT_35Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double Read2HDMaWjetsSRetaAda_2017_BDT_35Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21Var::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      2HDMaWjetsSRetaAda_2017_BDT_35Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(2HDMaWjetsSRetaAda_2017_BDT_35Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode*)current->GetRight();
         else current=(2HDMaWjetsSRetaAda_2017_BDT_35Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void Read2HDMaWjetsSRetaAda_2017_BDT_35Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21Var::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(0.705028462144668);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.917479,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.63733,-99) , 
NN(
0, 
0, 
-1, 1.93991, 1, -1, 0.229023,-99) , 
0, 119.605, 0, 0, 0.297401,-99) , 
19, 1.03351, 1, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.472505);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.91393, 1, 1, 0.728599,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.504945,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.278822,-99) , 
11, 0.247511, 0, 0, 0.39332,-99) , 
19, 1.35074, 1, 0, 0.607189,-99) , 
NN(
0, 
0, 
-1, 1.54732, 1, -1, 0.197415,-99) , 
19, 1.98522, 1, 0, 0.487954,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.362555);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.644153,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553822,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.321701,-99) , 
17, 133.202, 1, 0, 0.426422,-99) , 
NN(
0, 
0, 
-1, 96.7818, 0, -1, 0.225772,-99) , 
17, 177.173, 1, 0, 0.34147,-99) , 
7, 120.174, 0, 0, 0.432901,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.319418);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.659158,-99) , 
NN(
0, 
0, 
-1, 1.54732, 1, -1, 0.346974,-99) , 
0, 125.346, 0, 0, 0.421529,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.279897);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.674451,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.512253,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.282321,-99) , 
3, 1.26583, 1, 0, 0.416058,-99) , 
19, 1.2265, 1, 0, 0.561869,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538543,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.397986,-99) , 
0, 42.5653, 1, 0, 0.429921,-99) , 
NN(
0, 
0, 
-1, 195.168, 1, -1, 0.205882,-99) , 
6, 1.54732, 1, 0, 0.380954,-99) , 
4, 1.64561, 1, 0, 0.459174,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.233211);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.671228,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434407,-99) , 
5, 1.04719, 0, 0, 0.579485,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.518607,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39218,-99) , 
6, 0.515715, 1, 0, 0.444163,-99) , 
8, 97.7446, 0, 0, 0.49681,-99) , 
NN(
0, 
0, 
-1, 0.361167, 1, -1, 0.312928,-99) , 
6, 1.54732, 1, 0, 0.456478,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.159886);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.579741,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.501581,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.383114,-99) , 
7, 74.8413, 0, 0, 0.441576,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.240599,-99) , 
6, 1.90439, 1, 0, 0.422306,-99) , 
19, 1.03351, 1, 0, 0.462877,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.243267);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.656008,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443277,-99) , 
19, 1.53606, 1, 0, 0.607491,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530347,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.329916,-99) , 
13, 0.15125, 0, 0, 0.422024,-99) , 
0, 96.6568, 0, 0, 0.508271,-99) , 
NN(
0, 
0, 
-1, 1.90439, 1, -1, 0.37992,-99) , 
17, 177.593, 1, 0, 0.451099,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.165867);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.555988,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.657478,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.429164,-99) , 
6, 1.30927, 0, 0, 0.515389,-99) , 
NN(
0, 
0, 
-1, 2.30172, 1, -1, 0.410583,-99) , 
0, 56.7763, 1, 0, 0.432426,-99) , 
7, 120.174, 0, 0, 0.467013,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.189396);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.571474,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.677975,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.484575,-99) , 
4, 2.24402, 0, 0, 0.543541,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.599225,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.386515,-99) , 
0, 107.439, 0, 0, 0.423208,-99) , 
10, 1.2126, 0, 0, 0.453167,-99) , 
0, 125.346, 0, 0, 0.478357,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.124144);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.533981,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.39325,-99) , 
3, 2.45639, 1, 0, 0.515621,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.351648,-99) , 
20, 0.645291, 1, 0, 0.503174,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.3399,-99) , 
6, 1.90439, 1, 0, 0.487668,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.11802);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565501,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510619,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.431536,-99) , 
17, 163.115, 1, 0, 0.468041,-99) , 
5, 2.69279, 0, 0, 0.488751,-99) , 
NN(
0, 
0, 
-1, 2.09442, 1, -1, 0.396303,-99) , 
6, 1.54732, 1, 0, 0.469362,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.161542);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.608126,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.498842,-99) , 
3, 0.739391, 1, 0, 0.550089,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.390084,-99) , 
16, 93.5715, 1, 0, 0.523084,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.560652,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.419869,-99) , 
3, 0.956968, 1, 0, 0.48601,-99) , 
NN(
0, 
0, 
-1, 0.55789, 1, -1, 0.385774,-99) , 
2, 2.69281, 1, 0, 0.43901,-99) , 
8, 97.7446, 0, 0, 0.470295,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.0806589);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.580148,-99) , 
NN(
0, 
0, 
-1, 0.639314, 1, -1, 0.467073,-99) , 
20, 0.310547, 1, 0, 0.48459,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.124576);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 84.0476, 1, 1, 0.574074,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.457161,-99) , 
6, 1.30927, 1, 0, 0.541154,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527073,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.349177,-99) , 
12, 0.647713, 1, 0, 0.504882,-99) , 
NN(
0, 
0, 
-1, 180.174, 0, -1, 0.401144,-99) , 
16, 78.3335, 0, 0, 0.472685,-99) , 
8, 97.7446, 0, 0, 0.498227,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.0880958);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583682,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.499413,-99) , 
4, 1.04723, 1, 0, 0.530046,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.508317,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.427221,-99) , 
11, 0.18362, 1, 0, 0.464831,-99) , 
8, 85.3855, 0, 0, 0.49491,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.361627,-99) , 
20, 0.645291, 1, 0, 0.48617,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.111788);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.597616,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.475368,-99) , 
16, 85.9524, 1, 0, 0.556841,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.434334,-99) , 
2, 1.496, 0, 0, 0.532388,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.510664,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438091,-99) , 
0, 88.1808, 0, 0, 0.477252,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.334999,-99) , 
6, 1.90439, 1, 0, 0.464283,-99) , 
8, 97.7446, 0, 0, 0.48954,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.0932743);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.19678, 0, 1, 0.559161,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561411,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426189,-99) , 
4, 2.39364, 0, 0, 0.490214,-99) , 
14, 0.747938, 0, 0, 0.529969,-99) , 
NN(
0, 
0, 
-1, 2.73769, 1, -1, 0.463106,-99) , 
8, 97.7446, 0, 0, 0.48783,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.0949825);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.568692,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.540915,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46467,-99) , 
4, 2.3936, 0, 0, 0.491412,-99) , 
18, 0.50948, 1, 0, 0.505448,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.400814,-99) , 
19, 2.93692, 1, 0, 0.497335,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.116733);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.550873,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.466047,-99) , 
15, 1.11056, 1, 0, 0.530143,-99) , 
NN(
0, 
0, 
-1, 82.1429, 1, -1, 0.404586,-99) , 
3, 2.39241, 1, 0, 0.513426,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.520074,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.351129,-99) , 
20, 0.437785, 1, 0, 0.445415,-99) , 
2, 2.99199, 1, 0, 0.499454,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.0743755);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.54752,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.491824,-99) , 
4, 2.39359, 0, 0, 0.511681,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509633,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.351472,-99) , 
4, 2.09442, 1, 0, 0.445688,-99) , 
6, 1.54732, 1, 0, 0.497043,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.387155,-99) , 
20, 0.645291, 1, 0, 0.48992,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.0899051);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528195,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461508,-99) , 
5, 0.598397, 0, 0, 0.516369,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.401463,-99) , 
20, 0.652985, 1, 0, 0.508133,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.52377,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.405833,-99) , 
0, 91.1584, 0, 0, 0.479124,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.34415,-99) , 
4, 2.39361, 1, 0, 0.438145,-99) , 
6, 1.54732, 1, 0, 0.493545,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.102521);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.529557,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.454308,-99) , 
16, 89.4898, 1, 0, 0.506912,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.369833,-99) , 
16, 68.8098, 0, 0, 0.497452,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531435,-99) , 
NN(
0, 
0, 
-1, 0.437785, 1, -1, 0.382588,-99) , 
15, 1.10033, 0, 0, 0.430096,-99) , 
2, 2.99199, 1, 0, 0.483607,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0728813);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.5392,-99) , 
NN(
NN(
0, 
0, 
-1, 2.99199, 1, -1, 0.478748,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.521937,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.302531,-99) , 
17, 185.501, 0, 0, 0.411609,-99) , 
16, 72.6193, 0, 0, 0.467697,-99) , 
4, 0.598431, 1, 0, 0.478154,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0961019);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.565434,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480957,-99) , 
17, 143.091, 1, 0, 0.526992,-99) , 
NN(
0, 
0, 
-1, 0.370187, 0, -1, 0.460961,-99) , 
17, 187.04, 1, 0, 0.501067,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.500336,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.373228,-99) , 
13, 0.108789, 1, 0, 0.42392,-99) , 
16, 72.6193, 0, 0, 0.488273,-99)    );
  // itree = 25
  fBoostWeights.push_back(0.0949997);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534911,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.441452,-99) , 
3, 2.39241, 1, 0, 0.522478,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.51277,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.379033,-99) , 
20, 0.437785, 1, 0, 0.454025,-99) , 
2, 2.99199, 1, 0, 0.509004,-99) , 
NN(
0, 
0, 
-1, 80.7377, 0, -1, 0.42781,-99) , 
16, 72.6193, 0, 0, 0.495569,-99)    );
  // itree = 26
  fBoostWeights.push_back(0.080989);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.557378,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.539819,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.469138,-99) , 
0, 42.5653, 1, 0, 0.482492,-99) , 
20, 0.310547, 1, 0, 0.492665,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394359,-99) , 
6, 2.02342, 1, 0, 0.486348,-99)    );
  // itree = 27
  fBoostWeights.push_back(0.103192);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.591138,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.438661,-99) , 
15, 0.489118, 0, 0, 0.549705,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.517255,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417731,-99) , 
6, 0.736657, 1, 0, 0.491597,-99) , 
6, 1.10509, 0, 0, 0.506943,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526195,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446026,-99) , 
5, 1.64559, 0, 0, 0.487991,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.378317,-99) , 
8, 62.7222, 0, 0, 0.449357,-99) , 
6, 1.54732, 1, 0, 0.494992,-99)    );
  // itree = 28
  fBoostWeights.push_back(0.0565024);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.615094,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.495126,-99) , 
19, 2.26649, 0, 0, 0.512649,-99) , 
NN(
0, 
0, 
-1, 1.04722, 0, -1, 0.473438,-99) , 
8, 85.3855, 0, 0, 0.491301,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.409944,-99) , 
20, 0.645291, 1, 0, 0.486121,-99)    );
  // itree = 29
  fBoostWeights.push_back(0.0477295);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532237,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.49324,-99) , 
12, 0.48174, 0, 0, 0.508662,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.43208,-99) , 
6, 2.02342, 1, 0, 0.503479,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.423678,-99) , 
20, 0.645291, 1, 0, 0.498416,-99)    );
  // itree = 30
  fBoostWeights.push_back(0.136453);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.07125, 0, 1, 0.60152,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.556928,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.461992,-99) , 
7, 133.332, 0, 0, 0.497762,-99) , 
12, 0.470319, 0, 0, 0.515529,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.597744,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.446035,-99) , 
2, 2.39361, 1, 0, 0.510319,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.305662,-99) , 
0, 113.553, 1, 0, 0.473866,-99) , 
12, 0.517627, 1, 0, 0.501775,-99)    );
  // itree = 31
  fBoostWeights.push_back(0.140248);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.595109,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.531407,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.413634,-99) , 
0, 112.125, 1, 0, 0.489795,-99) , 
12, 0.407586, 1, 0, 0.527628,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.639492,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.420173,-99) , 
4, 1.9451, 0, 0, 0.543285,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.525004,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.417169,-99) , 
14, 1.49594, 0, 0, 0.463034,-99) , 
10, 1.21268, 0, 0, 0.48384,-99) , 
5, 1.79519, 0, 0, 0.505408,-99)    );
  // itree = 32
  fBoostWeights.push_back(0.070084);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.532987,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.549693,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.48698,-99) , 
10, 1.2126, 0, 0, 0.50472,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.415726,-99) , 
19, 1.04793, 0, 0, 0.48703,-99) , 
0, 125.346, 0, 0, 0.496389,-99)    );
  // itree = 33
  fBoostWeights.push_back(0.0464708);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 1.245, 0, 1, 0.513532,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394723,-99) , 
18, 1.44562, 1, 0, 0.506248,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.426422,-99) , 
19, 2.93692, 1, 0, 0.500289,-99)    );
  // itree = 34
  fBoostWeights.push_back(0.082707);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.606732,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.497855,-99) , 
4, 2.5432, 0, 0, 0.519641,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.506235,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.365809,-99) , 
14, 0.747938, 0, 0, 0.458079,-99) , 
5, 0.747996, 0, 0, 0.504177,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530741,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.430629,-99) , 
2, 2.6928, 1, 0, 0.48922,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.351055,-99) , 
0, 113.553, 1, 0, 0.465257,-99) , 
12, 0.517627, 1, 0, 0.491368,-99)    );
   return;
};
 
// Clean up
inline void Read2HDMaWjetsSRetaAda_2017_BDT_35Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21Var::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double Read2HDMaWjetsSRetaAda_2017_BDT_35Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21Var::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
