// Class: ReaddarkHiggsWjetsSReta_2017_BDT_25Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21Var
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::darkHiggsWjetsSReta_2017_BDT_25Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21Var
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : svanputt
Date           : Wed Apr  1 16:05:31 2020
Host           : Linux vocms0315.cern.ch 2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 09:23:05 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /storage_mnt/storage/user/svanputt/monoHiggs/MVA/CMSSW_8_0_17/src/UATmva
Training events: 440551
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "True" [Print method-specific help message]
NTrees: "25" [Number of trees in the forest]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "AdaBoost" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
SeparationType: "giniindex" [Separation criterion for node splitting]
PruneMethod: "costcomplexity" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "1.200000e+01" [Pruning strength]
# Default:
VerbosityLevel: "Verbose" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "5" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "inverseboostnegweights" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 21
mtw1                          mtw1                          mtw1                          mtw1                                                            'F'    [0,1429.77636719]
MHlnjj_deta_ljjVmet           MHlnjj_deta_ljjVmet           MHlnjj_deta_ljjVmet           MHlnjj_deta_ljjVmet                                             'F'    [1.36037840548e-06,7.68385124207]
MHlnjj_dphi_ljjVmet           MHlnjj_dphi_ljjVmet           MHlnjj_dphi_ljjVmet           MHlnjj_dphi_ljjVmet                                             'F'    [2.73937985185e-05,3.14159226418]
MHlnjj_deta_jjVl              MHlnjj_deta_jjVl              MHlnjj_deta_jjVl              MHlnjj_deta_jjVl                                                'F'    [4.67996233056e-06,10.0481100082]
MHlnjj_dphi_jjVl              MHlnjj_dphi_jjVl              MHlnjj_dphi_jjVl              MHlnjj_dphi_jjVl                                                'F'    [4.14871465182e-05,3.14158701897]
MHlnjj_dphi_lVmet             MHlnjj_dphi_lVmet             MHlnjj_dphi_lVmet             MHlnjj_dphi_lVmet                                               'F'    [0,3.14158368111]
MHlnjj_deta_lVmet             MHlnjj_deta_lVmet             MHlnjj_deta_lVmet             MHlnjj_deta_lVmet                                               'F'    [5.51156699657e-06,2.49951171875]
PuppiMET_pt                   PuppiMET_pt                   PuppiMET_pt                   PuppiMET_pt                                                     'F'    [50.0000076294,1308.07995605]
MHlnjj_pt_ljj                 MHlnjj_pt_ljj                 MHlnjj_pt_ljj                 MHlnjj_pt_ljj                                                   'F'    [0.275938302279,1025.22814941]
MHlnjj_m_lmetjj               MHlnjj_m_lmetjj               MHlnjj_m_lmetjj               MHlnjj_m_lmetjj                                                 'F'    [105.564781189,2611.10766602]
MHlnjj_PTljj_D_PTmet          MHlnjj_PTljj_D_PTmet          MHlnjj_PTljj_D_PTmet          MHlnjj_PTljj_D_PTmet                                            'F'    [0.00319861224853,12.7120838165]
MHlnjj_PTljj_D_Mlmetjj        MHlnjj_PTljj_D_Mlmetjj        MHlnjj_PTljj_D_Mlmetjj        MHlnjj_PTljj_D_Mlmetjj                                          'F'    [0.000932293245569,3.17160820961]
MHlnjj_MINPTlj_D_PTmet        MHlnjj_MINPTlj_D_PTmet        MHlnjj_MINPTlj_D_PTmet        MHlnjj_MINPTlj_D_PTmet                                          'F'    [0.0279273837805,3.62337827682]
MHlnjj_MINPTlj_D_Mlmetjj      MHlnjj_MINPTlj_D_Mlmetjj      MHlnjj_MINPTlj_D_Mlmetjj      MHlnjj_MINPTlj_D_Mlmetjj                                        'F'    [0.0134515520185,0.453358799219]
MHlnjj_dphi_jVj               MHlnjj_dphi_jVj               MHlnjj_dphi_jVj               MHlnjj_dphi_jVj                                                 'F'    [0,3.14158368111]
MHlnjj_deta_jVj               MHlnjj_deta_jVj               MHlnjj_deta_jVj               MHlnjj_deta_jVj                                                 'F'    [0,2.58422851562]
MHlnjj_m_jj                   MHlnjj_m_jj                   MHlnjj_m_jj                   MHlnjj_m_jj                                                     'F'    [65.000038147,104.999923706]
MHlnjj_m_ljj                  MHlnjj_m_ljj                  MHlnjj_m_ljj                  MHlnjj_m_ljj                                                    'F'    [75.383644104,2460.1262207]
MHlnjj_MAXPTlj_D_PTmet        MHlnjj_MAXPTlj_D_PTmet        MHlnjj_MAXPTlj_D_PTmet        MHlnjj_MAXPTlj_D_PTmet                                          'F'    [0.0622296258807,13.7160482407]
MHlnjj_MTljj_D_PTmet          MHlnjj_MTljj_D_PTmet          MHlnjj_MTljj_D_PTmet          MHlnjj_MTljj_D_PTmet                                            'F'    [0.079993866384,18.6729679108]
MHlnjj_MTljj_D_Mlmetjj        MHlnjj_MTljj_D_Mlmetjj        MHlnjj_MTljj_D_Mlmetjj        MHlnjj_MTljj_D_Mlmetjj                                          'F'    [0.0539623014629,0.951482534409]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new darkHiggsWjetsSReta_2017_BDT_25Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode
   
#ifndef darkHiggsWjetsSReta_2017_BDT_25Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode__def
#define darkHiggsWjetsSReta_2017_BDT_25Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode__def
   
class darkHiggsWjetsSReta_2017_BDT_25Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   darkHiggsWjetsSReta_2017_BDT_25Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode ( darkHiggsWjetsSReta_2017_BDT_25Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode* left,darkHiggsWjetsSReta_2017_BDT_25Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~darkHiggsWjetsSReta_2017_BDT_25Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   darkHiggsWjetsSReta_2017_BDT_25Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   darkHiggsWjetsSReta_2017_BDT_25Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   darkHiggsWjetsSReta_2017_BDT_25Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode*   fLeft;     // pointer to the left daughter node
   darkHiggsWjetsSReta_2017_BDT_25Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   darkHiggsWjetsSReta_2017_BDT_25Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode::~darkHiggsWjetsSReta_2017_BDT_25Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool darkHiggsWjetsSReta_2017_BDT_25Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool darkHiggsWjetsSReta_2017_BDT_25Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReaddarkHiggsWjetsSReta_2017_BDT_25Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21Var : public IClassifierReader {

 public:

   // constructor
   ReaddarkHiggsWjetsSReta_2017_BDT_25Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21Var( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReaddarkHiggsWjetsSReta_2017_BDT_25Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21Var" ),
        fNvars( 21 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "mtw1", "MHlnjj_deta_ljjVmet", "MHlnjj_dphi_ljjVmet", "MHlnjj_deta_jjVl", "MHlnjj_dphi_jjVl", "MHlnjj_dphi_lVmet", "MHlnjj_deta_lVmet", "PuppiMET_pt", "MHlnjj_pt_ljj", "MHlnjj_m_lmetjj", "MHlnjj_PTljj_D_PTmet", "MHlnjj_PTljj_D_Mlmetjj", "MHlnjj_MINPTlj_D_PTmet", "MHlnjj_MINPTlj_D_Mlmetjj", "MHlnjj_dphi_jVj", "MHlnjj_deta_jVj", "MHlnjj_m_jj", "MHlnjj_m_ljj", "MHlnjj_MAXPTlj_D_PTmet", "MHlnjj_MTljj_D_PTmet", "MHlnjj_MTljj_D_Mlmetjj" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;
      fVmin[17] = 0;
      fVmax[17] = 0;
      fVmin[18] = 0;
      fVmax[18] = 0;
      fVmin[19] = 0;
      fVmax[19] = 0;
      fVmin[20] = 0;
      fVmax[20] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';
      fType[20] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReaddarkHiggsWjetsSReta_2017_BDT_25Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21Var() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[21];
   double fVmax[21];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[21];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<darkHiggsWjetsSReta_2017_BDT_25Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReaddarkHiggsWjetsSReta_2017_BDT_25Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21Var::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   double norm  = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      darkHiggsWjetsSReta_2017_BDT_25Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(darkHiggsWjetsSReta_2017_BDT_25Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode*)current->GetRight();
         else current=(darkHiggsWjetsSReta_2017_BDT_25Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode*)current->GetLeft();
      }
      myMVA += fBoostWeights[itree] *  current->GetNodeType();
      norm  += fBoostWeights[itree];
   }
   return myMVA /= norm;
};

void ReaddarkHiggsWjetsSReta_2017_BDT_25Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21Var::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1.07097814731944);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.950479,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.6808,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.260335,-99) , 
19, 1.30058, 1, 0, 0.415833,-99) , 
NN(
0, 
0, 
-1, 0.385552, 1, -1, 0.0575165,-99) , 
4, 1.79521, 1, 0, 0.193688,-99) , 
19, 0.965374, 1, 0, 0.5,-99)    );
  // itree = 1
  fBoostWeights.push_back(0.773816);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.912904,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.553571,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.165758,-99) , 
17, 135.102, 1, 0, 0.37525,-99) , 
NN(
0, 
0, 
-1, 0.370351, 1, -1, 0.0595981,-99) , 
17, 179.892, 1, 0, 0.253617,-99) , 
0, 136.169, 0, 0, 0.46817,-99)    );
  // itree = 2
  fBoostWeights.push_back(0.604046);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.778811,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.543481,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.242043,-99) , 
3, 1.53245, 1, 0, 0.448133,-99) , 
NN(
0, 
0, 
-1, 174.959, 1, -1, 0.182234,-99) , 
0, 103.748, 0, 0, 0.248587,-99) , 
0, 136.169, 0, 0, 0.405262,-99)    );
  // itree = 3
  fBoostWeights.push_back(0.515931);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.777621,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.323368,-99) , 
5, 0.897595, 0, 0, 0.674957,-99) , 
NN(
0, 
0, 
-1, 179.892, 1, -1, 0.271534,-99) , 
7, 109.909, 0, 0, 0.406528,-99)    );
  // itree = 4
  fBoostWeights.push_back(0.351768);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.731892,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.505842,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.319635,-99) , 
6, 1.19025, 1, 0, 0.446635,-99) , 
8, 96.3593, 0, 0, 0.550955,-99) , 
NN(
0, 
0, 
-1, 0.370351, 1, -1, 0.201016,-99) , 
17, 188.943, 1, 0, 0.460587,-99)    );
  // itree = 5
  fBoostWeights.push_back(0.38335);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.730889,-99) , 
NN(
0, 
0, 
-1, 161.885, 1, -1, 0.377417,-99) , 
3, 0.845733, 1, 0, 0.577954,-99) , 
NN(
0, 
0, 
-1, 2.76649, 1, -1, 0.318106,-99) , 
4, 1.19682, 1, 0, 0.429157,-99)    );
  // itree = 6
  fBoostWeights.push_back(0.229089);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.705916,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.443055,-99) , 
2, 2.54325, 0, 0, 0.619753,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.50094,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.304339,-99) , 
17, 153.383, 1, 0, 0.442542,-99) , 
7, 109.909, 0, 0, 0.502175,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.0782054,-99) , 
19, 2.73613, 1, 0, 0.475548,-99)    );
  // itree = 7
  fBoostWeights.push_back(0.231089);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.690367,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.476218,-99) , 
8, 121.178, 0, 0, 0.596038,-99) , 
NN(
0, 
0, 
-1, 2.09441, 1, -1, 0.388047,-99) , 
7, 109.909, 0, 0, 0.453196,-99)    );
  // itree = 8
  fBoostWeights.push_back(0.229733);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.589406,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.381974,-99) , 
6, 1.54732, 1, 0, 0.552125,-99) , 
NN(
0, 
0, 
-1, 2.24391, 0, -1, 0.394145,-99) , 
16, 76.4286, 0, 0, 0.510787,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.117762,-99) , 
19, 2.73613, 1, 0, 0.489559,-99)    );
  // itree = 9
  fBoostWeights.push_back(0.157319);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.611166,-99) , 
NN(
0, 
0, 
-1, 2.65185, 1, -1, 0.432424,-99) , 
19, 0.965374, 1, 0, 0.475237,-99)    );
  // itree = 10
  fBoostWeights.push_back(0.243658);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.673677,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.480215,-99) , 
11, 0.257431, 0, 0, 0.602571,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.292816,-99) , 
17, 180.349, 1, 0, 0.557406,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526491,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.368322,-99) , 
2, 2.74979, 1, 0, 0.458832,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.275045,-99) , 
2, 1.49603, 0, 0, 0.41761,-99) , 
5, 2.09439, 0, 0, 0.495527,-99)    );
  // itree = 11
  fBoostWeights.push_back(0.216664);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.613592,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.450471,-99) , 
10, 1.20333, 1, 0, 0.582695,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.267092,-99) , 
4, 2.3936, 1, 0, 0.553396,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.538989,-99) , 
NN(
0, 
0, 
-1, 60.3766, 1, -1, 0.389151,-99) , 
9, 463.499, 0, 0, 0.415863,-99) , 
5, 2.09439, 0, 0, 0.491832,-99)    );
  // itree = 12
  fBoostWeights.push_back(0.146258);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.624734,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.482321,-99) , 
17, 121.121, 1, 0, 0.527066,-99) , 
NN(
0, 
0, 
-1, 2.54319, 1, -1, 0.362259,-99) , 
3, 2.39241, 1, 0, 0.508262,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.305902,-99) , 
18, 1.36259, 1, 0, 0.490853,-99)    );
  // itree = 13
  fBoostWeights.push_back(0.106965);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 393.615, 0, 1, 0.535289,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.344711,-99) , 
17, 281.344, 1, 0, 0.52194,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.279352,-99) , 
6, 2.02342, 1, 0, 0.5088,-99)    );
  // itree = 14
  fBoostWeights.push_back(0.233308);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.639835,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.613175,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421409,-99) , 
4, 2.09441, 0, 0, 0.476426,-99) , 
7, 139.445, 0, 0, 0.549341,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574122,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.367033,-99) , 
16, 82.1428, 0, 0, 0.487504,-99) , 
NN(
0, 
0, 
-1, 1.21479, 0, -1, 0.3362,-99) , 
18, 1.00927, 1, 0, 0.446053,-99) , 
12, 0.370351, 1, 0, 0.485743,-99)    );
  // itree = 15
  fBoostWeights.push_back(0.154903);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.574653,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.583543,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.526878,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.392983,-99) , 
12, 0.541563, 0, 0, 0.444124,-99) , 
0, 116.716, 0, 0, 0.462591,-99) , 
0, 136.169, 0, 0, 0.483968,-99)    );
  // itree = 16
  fBoostWeights.push_back(0.145277);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0.38467, 1, 1, 0.576118,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.509859,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.316086,-99) , 
3, 1.43545, 1, 0, 0.445875,-99) , 
12, 0.38032, 1, 0, 0.528397,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.502179,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.394438,-99) , 
17, 162.485, 1, 0, 0.458492,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.217972,-99) , 
11, 0.152213, 0, 0, 0.43083,-99) , 
18, 0.712411, 1, 0, 0.476224,-99)    );
  // itree = 17
  fBoostWeights.push_back(0.152115);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.530149,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.337066,-99) , 
2, 1.49603, 0, 0, 0.509717,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.551846,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.391924,-99) , 
1, 2.33879, 0, 0, 0.420682,-99) , 
14, 1.94479, 1, 0, 0.47198,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.2762,-99) , 
6, 2.02342, 1, 0, 0.461383,-99)    );
  // itree = 18
  fBoostWeights.push_back(0.175024);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.545478,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.421833,-99) , 
5, 1.49599, 0, 0, 0.514591,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.369225,-99) , 
3, 2.39241, 1, 0, 0.497808,-99) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.528925,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.34856,-99) , 
19, 1.35469, 0, 0, 0.470815,-99) , 
NN(
0, 
0, 
-1, 1.21479, 0, -1, 0.3255,-99) , 
19, 1.94175, 1, 0, 0.417233,-99) , 
18, 0.712411, 1, 0, 0.454664,-99)    );
  // itree = 19
  fBoostWeights.push_back(0.153701);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.561897,-99) , 
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.527807,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.406566,-99) , 
5, 0.897595, 1, 0, 0.448692,-99) , 
20, 0.346139, 1, 0, 0.502499,-99) , 
NN(
0, 
0, 
-1, 2.39241, 1, -1, 0.417773,-99) , 
12, 0.370351, 1, 0, 0.449927,-99)    );
  // itree = 20
  fBoostWeights.push_back(0.106692);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.547595,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.46578,-99) , 
10, 1.14676, 0, 0, 0.486952,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.351277,-99) , 
15, 1.59976, 1, 0, 0.47754,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.305675,-99) , 
6, 2.02342, 1, 0, 0.468585,-99)    );
  // itree = 21
  fBoostWeights.push_back(0.115674);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.534732,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.440468,-99) , 
17, 163.931, 1, 0, 0.507072,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.381796,-99) , 
16, 70.7143, 0, 0, 0.493803,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.360236,-99) , 
18, 1.36259, 1, 0, 0.482632,-99)    );
  // itree = 22
  fBoostWeights.push_back(0.0768572);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.576891,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.483633,-99) , 
8, 170.787, 0, 0, 0.494645,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.364411,-99) , 
15, 1.59976, 1, 0, 0.485667,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.329145,-99) , 
6, 2.02342, 1, 0, 0.477692,-99)    );
  // itree = 23
  fBoostWeights.push_back(0.0804857);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.523265,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.452897,-99) , 
13, 0.160087, 1, 0, 0.509285,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.38239,-99) , 
15, 1.59976, 1, 0, 0.500608,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.346333,-99) , 
6, 2.02342, 1, 0, 0.492829,-99)    );
  // itree = 24
  fBoostWeights.push_back(0.0842206);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, 1, 0.645227,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.467936,-99) , 
20, 0.511972, 0, 0, 0.554476,-99) , 
NN(
0, 
0, 
-1, 1.56965, 0, -1, 0.47842,-99) , 
0, 68.0846, 1, 0, 0.493473,-99) , 
NN(
0, 
0, 
-1, 0, 1, -1, 0.375879,-99) , 
18, 1.36259, 1, 0, 0.483723,-99)    );
   return;
};
 
// Clean up
inline void ReaddarkHiggsWjetsSReta_2017_BDT_25Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21Var::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReaddarkHiggsWjetsSReta_2017_BDT_25Trees_AdaBoost_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21Var::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
