// Class: ReaddarkHiggsWjetsSReta_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21Var
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::darkHiggsWjetsSReta_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21Var
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : svanputt
Date           : Tue Mar 31 16:35:21 2020
Host           : Linux vocms0315.cern.ch 2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 09:23:05 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /storage_mnt/storage/user/svanputt/monoHiggs/MVA/CMSSW_8_0_17/src/UATmva
Training events: 440551
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "True" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
SeparationType: "giniindex" [Separation criterion for node splitting]
PruneMethod: "costcomplexity" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "1.200000e+01" [Pruning strength]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
# Default:
VerbosityLevel: "Verbose" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "5" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "ignorenegweightsintraining" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 21
mtw1                          mtw1                          mtw1                          mtw1                                                            'F'    [0,1429.77636719]
MHlnjj_deta_ljjVmet           MHlnjj_deta_ljjVmet           MHlnjj_deta_ljjVmet           MHlnjj_deta_ljjVmet                                             'F'    [1.36037840548e-06,7.68385124207]
MHlnjj_dphi_ljjVmet           MHlnjj_dphi_ljjVmet           MHlnjj_dphi_ljjVmet           MHlnjj_dphi_ljjVmet                                             'F'    [2.73937985185e-05,3.14159226418]
MHlnjj_deta_jjVl              MHlnjj_deta_jjVl              MHlnjj_deta_jjVl              MHlnjj_deta_jjVl                                                'F'    [4.67996233056e-06,10.0481100082]
MHlnjj_dphi_jjVl              MHlnjj_dphi_jjVl              MHlnjj_dphi_jjVl              MHlnjj_dphi_jjVl                                                'F'    [4.14871465182e-05,3.14158701897]
MHlnjj_dphi_lVmet             MHlnjj_dphi_lVmet             MHlnjj_dphi_lVmet             MHlnjj_dphi_lVmet                                               'F'    [0,3.14158368111]
MHlnjj_deta_lVmet             MHlnjj_deta_lVmet             MHlnjj_deta_lVmet             MHlnjj_deta_lVmet                                               'F'    [5.51156699657e-06,2.49951171875]
PuppiMET_pt                   PuppiMET_pt                   PuppiMET_pt                   PuppiMET_pt                                                     'F'    [50.0000076294,1308.07995605]
MHlnjj_pt_ljj                 MHlnjj_pt_ljj                 MHlnjj_pt_ljj                 MHlnjj_pt_ljj                                                   'F'    [0.275938302279,1025.22814941]
MHlnjj_m_lmetjj               MHlnjj_m_lmetjj               MHlnjj_m_lmetjj               MHlnjj_m_lmetjj                                                 'F'    [105.564781189,2611.10766602]
MHlnjj_PTljj_D_PTmet          MHlnjj_PTljj_D_PTmet          MHlnjj_PTljj_D_PTmet          MHlnjj_PTljj_D_PTmet                                            'F'    [0.00319861224853,12.7120838165]
MHlnjj_PTljj_D_Mlmetjj        MHlnjj_PTljj_D_Mlmetjj        MHlnjj_PTljj_D_Mlmetjj        MHlnjj_PTljj_D_Mlmetjj                                          'F'    [0.000932293245569,3.17160820961]
MHlnjj_MINPTlj_D_PTmet        MHlnjj_MINPTlj_D_PTmet        MHlnjj_MINPTlj_D_PTmet        MHlnjj_MINPTlj_D_PTmet                                          'F'    [0.0279273837805,3.62337827682]
MHlnjj_MINPTlj_D_Mlmetjj      MHlnjj_MINPTlj_D_Mlmetjj      MHlnjj_MINPTlj_D_Mlmetjj      MHlnjj_MINPTlj_D_Mlmetjj                                        'F'    [0.0134515520185,0.453358799219]
MHlnjj_dphi_jVj               MHlnjj_dphi_jVj               MHlnjj_dphi_jVj               MHlnjj_dphi_jVj                                                 'F'    [0,3.14158368111]
MHlnjj_deta_jVj               MHlnjj_deta_jVj               MHlnjj_deta_jVj               MHlnjj_deta_jVj                                                 'F'    [0,2.58422851562]
MHlnjj_m_jj                   MHlnjj_m_jj                   MHlnjj_m_jj                   MHlnjj_m_jj                                                     'F'    [65.000038147,104.999923706]
MHlnjj_m_ljj                  MHlnjj_m_ljj                  MHlnjj_m_ljj                  MHlnjj_m_ljj                                                    'F'    [75.383644104,2460.1262207]
MHlnjj_MAXPTlj_D_PTmet        MHlnjj_MAXPTlj_D_PTmet        MHlnjj_MAXPTlj_D_PTmet        MHlnjj_MAXPTlj_D_PTmet                                          'F'    [0.0622296258807,13.7160482407]
MHlnjj_MTljj_D_PTmet          MHlnjj_MTljj_D_PTmet          MHlnjj_MTljj_D_PTmet          MHlnjj_MTljj_D_PTmet                                            'F'    [0.079993866384,18.6729679108]
MHlnjj_MTljj_D_Mlmetjj        MHlnjj_MTljj_D_Mlmetjj        MHlnjj_MTljj_D_Mlmetjj        MHlnjj_MTljj_D_Mlmetjj                                          'F'    [0.0539623014629,0.951482534409]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new darkHiggsWjetsSReta_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode
   
#ifndef darkHiggsWjetsSReta_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode__def
#define darkHiggsWjetsSReta_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode__def
   
class darkHiggsWjetsSReta_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   darkHiggsWjetsSReta_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode ( darkHiggsWjetsSReta_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode* left,darkHiggsWjetsSReta_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~darkHiggsWjetsSReta_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   darkHiggsWjetsSReta_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   darkHiggsWjetsSReta_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   darkHiggsWjetsSReta_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode*   fLeft;     // pointer to the left daughter node
   darkHiggsWjetsSReta_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   darkHiggsWjetsSReta_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode::~darkHiggsWjetsSReta_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool darkHiggsWjetsSReta_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool darkHiggsWjetsSReta_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReaddarkHiggsWjetsSReta_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21Var : public IClassifierReader {

 public:

   // constructor
   ReaddarkHiggsWjetsSReta_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21Var( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReaddarkHiggsWjetsSReta_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21Var" ),
        fNvars( 21 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "mtw1", "MHlnjj_deta_ljjVmet", "MHlnjj_dphi_ljjVmet", "MHlnjj_deta_jjVl", "MHlnjj_dphi_jjVl", "MHlnjj_dphi_lVmet", "MHlnjj_deta_lVmet", "PuppiMET_pt", "MHlnjj_pt_ljj", "MHlnjj_m_lmetjj", "MHlnjj_PTljj_D_PTmet", "MHlnjj_PTljj_D_Mlmetjj", "MHlnjj_MINPTlj_D_PTmet", "MHlnjj_MINPTlj_D_Mlmetjj", "MHlnjj_dphi_jVj", "MHlnjj_deta_jVj", "MHlnjj_m_jj", "MHlnjj_m_ljj", "MHlnjj_MAXPTlj_D_PTmet", "MHlnjj_MTljj_D_PTmet", "MHlnjj_MTljj_D_Mlmetjj" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;
      fVmin[17] = 0;
      fVmax[17] = 0;
      fVmin[18] = 0;
      fVmax[18] = 0;
      fVmin[19] = 0;
      fVmax[19] = 0;
      fVmin[20] = 0;
      fVmax[20] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';
      fType[20] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReaddarkHiggsWjetsSReta_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21Var() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[21];
   double fVmax[21];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[21];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<darkHiggsWjetsSReta_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double ReaddarkHiggsWjetsSReta_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21Var::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      darkHiggsWjetsSReta_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(darkHiggsWjetsSReta_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode*)current->GetRight();
         else current=(darkHiggsWjetsSReta_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21VarNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void ReaddarkHiggsWjetsSReta_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21Var::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00731242) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.660556,0.00340619) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.157137,-0.0283654) , 
3, 1.53873, 1, 0, 0.504663,0.00466281) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.301756,-0.00755827) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0631409,-0.129261) , 
4, 1.68837, 1, 0, 0.0917274,-0.408273) , 
4, 1.34642, 1, 0, 0.202562,-0.297438) , 
19, 0.945647, 1, 0, 0.5,-2.32032e-15)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00725371) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.229594,-0.0200467) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.697925,0.00379563) , 
7, 69.3294, 1, 0, 0.504663,0.00787789) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.192143,-0.0237369) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0419782,-0.107011) , 
19, 1.77009, 1, 0, 0.0917274,-0.351247) , 
4, 1.34642, 1, 0, 0.202562,-0.254856) , 
19, 0.945647, 1, 0, 0.5,0.0242422)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00719624) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.237733,-0.0123454) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0237308,-0.366032) , 
17, 176.945, 1, 0, 0.132413,-0.290698) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564186,0.00263467) , 
0, 119.605, 1, 0, 0.202562,-0.225859) , 
19, 0.945647, 1, 0, 0.5,0.040299)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00713996) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.231655,-0.0171394) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.719529,0.00417617) , 
7, 69.0425, 1, 0, 0.52672,0.0586782) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0812292,-0.0471942) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.243598,-0.005194) , 
7, 112.177, 1, 0, 0.102487,-0.225557) , 
4, 1.19682, 1, 0, 0.202562,-0.158507) , 
19, 0.945647, 1, 0, 0.5,0.0795094)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00708484) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0826514,-0.0420994) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.281725,-0.00478689) , 
0, 96.823, 1, 0, 0.132413,-0.195248) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564186,0.00282059) , 
0, 119.605, 1, 0, 0.202562,-0.144686) , 
19, 0.945647, 1, 0, 0.5,0.0864332)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00703083) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.231655,-0.0154296) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.719529,0.00420917) , 
7, 69.0425, 1, 0, 0.52672,0.0684653) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0812292,-0.0422491) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.243598,-0.00422048) , 
7, 112.177, 1, 0, 0.102487,-0.196154) , 
4, 1.19682, 1, 0, 0.202562,-0.133731) , 
19, 0.945647, 1, 0, 0.5,0.0916394)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.314733,-0.00595411) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.720344,0.00400964) , 
0, 97.2585, 1, 0, 0.540116,0.0757464) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.27235,-0.00536342) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0573741,-0.0841351) , 
4, 1.75248, 1, 0, 0.0958805,-0.190091) , 
4, 1.19682, 1, 0, 0.209825,-0.121905) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00713014) , 
0, 136.169, 1, 0, 0.5,0.097293)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00695307) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0826514,-0.0341061) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.281725,-0.00328026) , 
0, 96.823, 1, 0, 0.132413,-0.149128) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564186,0.00310627) , 
0, 119.605, 1, 0, 0.202562,-0.104202) , 
19, 0.945647, 1, 0, 0.5,0.107354)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00690191) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0721409,-0.0395414) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.262042,-0.00398586) , 
11, 0.277936, 1, 0, 0.132413,-0.139539) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564186,0.00306978) , 
0, 119.605, 1, 0, 0.202562,-0.0964124) , 
19, 0.945647, 1, 0, 0.5,0.110679)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00685175) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.231655,-0.0133288) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.719529,0.00424157) , 
7, 69.0425, 1, 0, 0.52672,0.0804702) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0812292,-0.0330071) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.243598,-0.00132676) , 
7, 112.177, 1, 0, 0.102487,-0.14052) , 
4, 1.19682, 1, 0, 0.202562,-0.0883893) , 
19, 0.945647, 1, 0, 0.5,0.114155)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.314733,-0.0048707) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.720344,0.00399089) , 
0, 97.2585, 1, 0, 0.540116,0.0850908) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.236616,-0.00651437) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0515377,-0.0497086) , 
18, 0.722297, 1, 0, 0.0958805,-0.137545) , 
4, 1.19682, 1, 0, 0.209825,-0.0804399) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.0069492) , 
0, 136.169, 1, 0, 0.5,0.11754)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00676439) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0826514,-0.0279869) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.281725,-0.0018271) , 
0, 96.823, 1, 0, 0.132413,-0.111258) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564186,0.0032092) , 
0, 119.605, 1, 0, 0.202562,-0.071829) , 
19, 0.945647, 1, 0, 0.5,0.121705)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.721462,0.00449873) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.109211,-0.0445925) , 
17, 136.24, 1, 0, 0.517821,0.0766857) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.113906,-0.0154856) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0428791,-0.102043) , 
6, 1.19027, 1, 0, 0.0844426,-0.124014) , 
4, 1.34642, 1, 0, 0.209825,-0.0659492) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00685393) , 
0, 136.169, 1, 0, 0.5,0.123708)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00669528) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0826514,-0.0243365) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.281725,-0.00112847) , 
0, 96.823, 1, 0, 0.132413,-0.0918934) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564186,0.00326465) , 
0, 119.605, 1, 0, 0.202562,-0.0552697) , 
19, 0.945647, 1, 0, 0.5,0.129648)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00664933) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.660556,0.00425689) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.157137,-0.0150972) , 
3, 1.53873, 1, 0, 0.504663,0.0825473) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0691138,-0.0306884) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.237489,0.000800346) , 
7, 112.177, 1, 0, 0.0917274,-0.0998663) , 
4, 1.34642, 1, 0, 0.202562,-0.0509054) , 
19, 0.945647, 1, 0, 0.5,0.130965)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00660421) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.098382,-0.0171476) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.305001,0.000364185) , 
0, 102.519, 1, 0, 0.132413,-0.0805118) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564186,0.00333886) , 
0, 119.605, 1, 0, 0.202562,-0.0452654) , 
19, 0.945647, 1, 0, 0.5,0.133062)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.713038,0.00406818) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313864,-0.00327597) , 
3, 1.15405, 1, 0, 0.540116,0.0983296) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.25092,-0.00168672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0537678,-0.0544425) , 
4, 1.84509, 1, 0, 0.0958805,-0.0899939) , 
4, 1.19682, 1, 0, 0.209825,-0.0416899) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00669053) , 
0, 136.169, 1, 0, 0.5,0.13371)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00653381) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0826514,-0.0198335) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.281725,-0.000288062) , 
0, 96.823, 1, 0, 0.132413,-0.0681328) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564186,0.00335061) , 
0, 119.605, 1, 0, 0.202562,-0.0348539) , 
19, 0.945647, 1, 0, 0.5,0.137181)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00649093) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.173629,-0.00794746) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.648279,0.00465293) , 
0, 102.356, 1, 0, 0.372102,0.048777) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0461705,-0.0209583) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0657088,-0.0368602) , 
0, 79.737, 1, 0, 0.0556771,-0.101614) , 
19, 1.77009, 1, 0, 0.202562,-0.0318022) , 
19, 0.945647, 1, 0, 0.5,0.137744)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0780293,-0.0213969) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.267862,-0.000814531) , 
11, 0.303182, 1, 0, 0.127064,-0.0699014) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.712599,0.00502706) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137593,-0.0224479) , 
18, 0.772657, 1, 0, 0.47191,0.107816) , 
0, 103.748, 1, 0, 0.209825,-0.0272506) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00657609) , 
0, 136.169, 1, 0, 0.5,0.139033)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00641748) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573398,0.00402368) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.109616,-0.0230909) , 
17, 155.368, 1, 0, 0.431937,0.0666824) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.036954,-0.0946263) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.194216,0.00150392) , 
7, 112.177, 1, 0, 0.0593788,-0.0814221) , 
4, 1.79521, 1, 0, 0.202562,-0.024502) , 
19, 0.945647, 1, 0, 0.5,0.139882)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.145764,-0.00456494) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0301445,-0.183181) , 
3, 2.39242, 1, 0, 0.127064,-0.0559713) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.712599,0.00504789) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137593,-0.0180334) , 
18, 0.772657, 1, 0, 0.47191,0.117863) , 
0, 103.748, 1, 0, 0.209825,-0.0142523) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00652596) , 
0, 136.169, 1, 0, 0.5,0.145194)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0931962,-0.0112543) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.331069,0.00137952) , 
11, 0.302901, 1, 0, 0.157475,-0.0350809) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59091,0.00454925) , 
0, 116.716, 1, 0, 0.209825,-0.00851204) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00648409) , 
0, 136.169, 1, 0, 0.5,0.147407)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00632514) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.173629,-0.00491976) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.648279,0.00468134) , 
0, 102.356, 1, 0, 0.372102,0.0650963) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0911342,-0.00750401) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0309469,-0.0602264) , 
18, 1.05879, 1, 0, 0.0556771,-0.0709504) , 
19, 1.77009, 1, 0, 0.202562,-0.00779749) , 
19, 0.945647, 1, 0, 0.5,0.146949)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0931962,-0.0102945) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.331069,0.00153931) , 
11, 0.302901, 1, 0, 0.157475,-0.0299102) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59091,0.00454725) , 
0, 116.716, 1, 0, 0.209825,-0.00401902) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00642221) , 
0, 136.169, 1, 0, 0.5,0.148095)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0893421,-0.00982703) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.18594,-0.00105762) , 
13, 0.140382, 1, 0, 0.127064,-0.0418023) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.712599,0.00495715) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137593,-0.0155544) , 
18, 0.772657, 1, 0, 0.47191,0.120219) , 
0, 103.748, 1, 0, 0.209825,-0.00291831) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00638238) , 
0, 136.169, 1, 0, 0.5,0.147531)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00622532) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0810575,-0.0143916) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.290748,0.00132311) , 
5, 2.39359, 1, 0, 0.132413,-0.031134) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564186,0.00362046) , 
0, 119.605, 1, 0, 0.202562,-0.0022644) , 
19, 0.945647, 1, 0, 0.5,0.147044)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00618809) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0826514,-0.0116171) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.281725,0.00150033) , 
0, 96.823, 1, 0, 0.132413,-0.0290111) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564186,0.00358237) , 
0, 119.605, 1, 0, 0.202562,-0.000747511) , 
19, 0.945647, 1, 0, 0.5,0.146761)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.713038,0.00411687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.313864,-0.00152475) , 
3, 1.15405, 1, 0, 0.540116,0.115087) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0720682,-0.0242332) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.156761,0.000788877) , 
13, 0.14814, 1, 0, 0.0958805,-0.0387635) , 
4, 1.19682, 1, 0, 0.209825,0.000698481) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00627346) , 
0, 136.169, 1, 0, 0.5,0.146267)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00612782) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.173629,-0.00339242) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.648279,0.00456984) , 
0, 102.356, 1, 0, 0.372102,0.0705361) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0461705,-0.0114954) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0657088,-0.0250017) , 
0, 79.737, 1, 0, 0.0556771,-0.0570141) , 
19, 1.77009, 1, 0, 0.202562,0.00219473) , 
19, 0.945647, 1, 0, 0.5,0.146467)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00609225) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573398,0.00426789) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.109616,-0.0177804) , 
17, 155.368, 1, 0, 0.431937,0.0834719) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.167665,0.00259466) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0315292,-0.086635) , 
12, 0.385552, 1, 0, 0.0593788,-0.0456591) , 
4, 1.79521, 1, 0, 0.202562,0.00396897) , 
19, 0.945647, 1, 0, 0.5,0.146365)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0893421,-0.007619) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.18594,0.000425447) , 
13, 0.140382, 1, 0, 0.127064,-0.0270022) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.712599,0.00489622) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137593,-0.0112555) , 
18, 0.772657, 1, 0, 0.47191,0.126426) , 
0, 103.748, 1, 0, 0.209825,0.00981947) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00620143) , 
0, 136.169, 1, 0, 0.5,0.14913)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0893421,-0.00738242) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.18594,0.000414378) , 
13, 0.140382, 1, 0, 0.127064,-0.026139) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.712599,0.00485667) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137593,-0.010628) , 
18, 0.772657, 1, 0, 0.47191,0.126362) , 
0, 103.748, 1, 0, 0.209825,0.01046) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00616575) , 
0, 136.169, 1, 0, 0.5,0.148349)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.231064,-3.41786e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0277761,-0.0709388) , 
17, 174.959, 1, 0, 0.127064,-0.0253098) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.712599,0.00481758) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137593,-0.0100382) , 
18, 0.772657, 1, 0, 0.47191,0.126226) , 
0, 103.748, 1, 0, 0.209825,0.0110577) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00613062) , 
0, 136.169, 1, 0, 0.5,0.147552)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00598541) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0568828,-0.0245873) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.203318,0.00134212) , 
13, 0.131447, 1, 0, 0.132413,-0.0122177) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.564186,0.00368206) , 
0, 119.605, 1, 0, 0.202562,0.0137758) , 
19, 0.945647, 1, 0, 0.5,0.148421)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.0059523) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.216052,0.00359546) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0717155,-0.0114699) , 
12, 0.385552, 1, 0, 0.0948906,-0.0288322) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626099,0.00463585) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0949779,-0.0142693) , 
17, 155.368, 1, 0, 0.396345,0.0937045) , 
11, 0.277936, 1, 0, 0.202562,0.0149346) , 
19, 0.945647, 1, 0, 0.5,0.147989)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0780293,-0.00860099) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.267862,0.000937834) , 
11, 0.303182, 1, 0, 0.127064,-0.0187455) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.712599,0.00476656) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137593,-0.0088217) , 
18, 0.772657, 1, 0, 0.47191,0.126551) , 
0, 103.748, 1, 0, 0.209825,0.0161245) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00604106) , 
0, 136.169, 1, 0, 0.5,0.147509)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00589316) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.209603,0.00156252) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0410886,-0.0214519) , 
18, 0.769909, 1, 0, 0.0948906,-0.0263627) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.177006,-0.00139865) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.710373,0.00479748) , 
0, 102.356, 1, 0, 0.396345,0.0934866) , 
11, 0.277936, 1, 0, 0.202562,0.0164442) , 
19, 0.945647, 1, 0, 0.5,0.146803)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.282193,0.0015702) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0271031,-0.0664374) , 
17, 174.959, 1, 0, 0.157475,-0.00509353) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59091,0.00456462) , 
0, 116.716, 1, 0, 0.209825,0.017523) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00598368) , 
0, 136.169, 1, 0, 0.5,0.146315)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00584649) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.173629,-0.00102966) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.648279,0.00447024) , 
0, 102.356, 1, 0, 0.372102,0.0794552) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0911342,-0.00202672) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0309469,-0.0371445) , 
18, 1.05879, 1, 0, 0.0556771,-0.0324395) , 
19, 1.77009, 1, 0, 0.202562,0.019502) , 
19, 0.945647, 1, 0, 0.5,0.146817)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0780293,-0.00686901) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.267862,0.00120987) , 
11, 0.303182, 1, 0, 0.127064,-0.012287) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.712599,0.00465908) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137593,-0.00688269) , 
18, 0.772657, 1, 0, 0.47191,0.126331) , 
0, 103.748, 1, 0, 0.209825,0.0209802) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00593214) , 
0, 136.169, 1, 0, 0.5,0.146481)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.0057902) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.216052,0.00400495) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0717155,-0.00917728) , 
12, 0.385552, 1, 0, 0.0948906,-0.0202091) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.177006,-0.0007984) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.710373,0.00472913) , 
0, 102.356, 1, 0, 0.396345,0.0950379) , 
11, 0.277936, 1, 0, 0.202562,0.020954) , 
19, 0.945647, 1, 0, 0.5,0.145643)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0893421,-0.00448231) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.18594,0.00143465) , 
13, 0.140382, 1, 0, 0.127064,-0.0110586) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.712599,0.00460573) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137593,-0.00643235) , 
18, 0.772657, 1, 0, 0.47191,0.125249) , 
0, 103.748, 1, 0, 0.209825,0.0216542) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00587483) , 
0, 136.169, 1, 0, 0.5,0.144835)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00573573) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.216052,0.00389057) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0717155,-0.0087951) , 
12, 0.385552, 1, 0, 0.0948906,-0.0191024) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.177006,-0.000747857) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.710373,0.0046732) , 
0, 102.356, 1, 0, 0.396345,0.0939138) , 
11, 0.277936, 1, 0, 0.202562,0.0212639) , 
19, 0.945647, 1, 0, 0.5,0.143822)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00570651) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.209603,0.00195161) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0410886,-0.0176087) , 
18, 0.769909, 1, 0, 0.0948906,-0.0180648) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626099,0.00447997) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0949779,-0.0117896) , 
17, 155.368, 1, 0, 0.396345,0.0931684) , 
11, 0.277936, 1, 0, 0.202562,0.0216647) , 
19, 0.945647, 1, 0, 0.5,0.143007)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0931962,-0.00385598) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.331069,0.00244255) , 
11, 0.302901, 1, 0, 0.157475,0.00125968) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59091,0.00446542) , 
0, 116.716, 1, 0, 0.209825,0.0224133) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00580033) , 
0, 136.169, 1, 0, 0.5,0.142465)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0893421,-0.00421376) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.18594,0.00161505) , 
13, 0.140382, 1, 0, 0.127064,-0.00939367) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.712599,0.00450945) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137593,-0.00563989) , 
18, 0.772657, 1, 0, 0.47191,0.123193) , 
0, 103.748, 1, 0, 0.209825,0.0224261) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00577113) , 
0, 136.169, 1, 0, 0.5,0.141422)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00563014) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.573398,0.00418434) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.109616,-0.0133671) , 
17, 155.368, 1, 0, 0.431937,0.0881086) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.036954,-0.0473563) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.194216,0.00622627) , 
7, 112.177, 1, 0, 0.0593788,-0.0190214) , 
4, 1.79521, 1, 0, 0.202562,0.0221512) , 
19, 0.945647, 1, 0, 0.5,0.140408)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0893421,-0.00382235) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.18594,0.00185002) , 
13, 0.140382, 1, 0, 0.127064,-0.00703744) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.712599,0.00448978) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137593,-0.00440194) , 
18, 0.772657, 1, 0, 0.47191,0.124457) , 
0, 103.748, 1, 0, 0.209825,0.0245202) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00573141) , 
0, 136.169, 1, 0, 0.5,0.141013)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0893421,-0.00372279) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.18594,0.0018029) , 
13, 0.140382, 1, 0, 0.127064,-0.00683944) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.712599,0.00445609) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137593,-0.00417597) , 
18, 0.772657, 1, 0, 0.47191,0.123702) , 
0, 103.748, 1, 0, 0.209825,0.0244896) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00570337) , 
0, 136.169, 1, 0, 0.5,0.139966)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.070453,-0.00931557) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.167496,0.00116451) , 
13, 0.140382, 1, 0, 0.107872,-0.0139128) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.740029,0.00443736) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.168116,-0.000712666) , 
19, 1.34942, 1, 0, 0.421999,0.104288) , 
0, 97.2634, 1, 0, 0.209825,0.0244505) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00567571) , 
0, 136.169, 1, 0, 0.5,0.138922)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00553698) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57985,0.00474122) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.214079,-0.000293981) , 
19, 1.29898, 1, 0, 0.372102,0.0779804) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.144647,0.00113758) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0277711,-0.0262979) , 
9, 242.918, 1, 0, 0.0556771,-0.0221438) , 
19, 1.77009, 1, 0, 0.202562,0.0243339) , 
19, 0.945647, 1, 0, 0.5,0.13805)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.103559,-0.00284282) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299772,0.00263294) , 
0, 94.4845, 1, 0, 0.157475,0.00478449) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59091,0.00440856) , 
0, 116.716, 1, 0, 0.209825,0.0249982) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00563185) , 
0, 136.169, 1, 0, 0.5,0.137471)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.103559,-0.0027523) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299772,0.00259734) , 
0, 94.4845, 1, 0, 0.157475,0.00492732) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59091,0.00437182) , 
0, 116.716, 1, 0, 0.209825,0.0249185) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00560524) , 
0, 136.169, 1, 0, 0.5,0.136426)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00546745) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.216052,0.00401145) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0717155,-0.00664454) , 
12, 0.385552, 1, 0, 0.0948906,-0.01215) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.177006,-0.000353032) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.710373,0.00446717) , 
0, 102.356, 1, 0, 0.396345,0.0903981) , 
11, 0.277936, 1, 0, 0.202562,0.0244774) , 
19, 0.945647, 1, 0, 0.5,0.135384)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.282193,0.00193217) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0271031,-0.0463835) , 
17, 174.959, 1, 0, 0.157475,0.00521296) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59091,0.00431707) , 
0, 116.716, 1, 0, 0.209825,0.0248431) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00555693) , 
0, 136.169, 1, 0, 0.5,0.134509)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00542894) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.216052,0.00410091) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0717155,-0.00611652) , 
12, 0.385552, 1, 0, 0.0948906,-0.0104477) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.177006,-0.000178494) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.710373,0.00441573) , 
0, 102.356, 1, 0, 0.396345,0.0900559) , 
11, 0.277936, 1, 0, 0.202562,0.0254494) , 
19, 0.945647, 1, 0, 0.5,0.134294)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00540405) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.209603,0.00237246) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0410886,-0.0132156) , 
18, 0.769909, 1, 0, 0.0948906,-0.00985529) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626099,0.00423462) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0949779,-0.009547) , 
17, 155.368, 1, 0, 0.396345,0.0892843) , 
11, 0.277936, 1, 0, 0.202562,0.0255547) , 
19, 0.945647, 1, 0, 0.5,0.133397)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.070453,-0.00769905) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.167496,0.00154775) , 
13, 0.140382, 1, 0, 0.107872,-0.00946301) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.740029,0.00426174) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.168116,-0.000441253) , 
19, 1.34942, 1, 0, 0.421999,0.100251) , 
0, 97.2634, 1, 0, 0.209825,0.0261457) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00549358) , 
0, 136.169, 1, 0, 0.5,0.132695)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00536094) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.216052,0.00402636) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0717155,-0.00562817) , 
12, 0.385552, 1, 0, 0.0948906,-0.00903417) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.177006,-0.000141112) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.710373,0.00435298) , 
0, 102.356, 1, 0, 0.396345,0.0885742) , 
11, 0.277936, 1, 0, 0.202562,0.0258289) , 
19, 0.945647, 1, 0, 0.5,0.131795)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00533691) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.57985,0.00457662) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.214079,-0.000105113) , 
19, 1.29898, 1, 0, 0.372102,0.0755157) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0911342,0.000588637) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0309469,-0.0267196) , 
18, 1.05879, 1, 0, 0.0556771,-0.0170987) , 
19, 1.77009, 1, 0, 0.202562,0.0258929) , 
19, 0.945647, 1, 0, 0.5,0.130895)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0931962,-0.00213891) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.331069,0.00248982) , 
11, 0.302901, 1, 0, 0.157475,0.00769273) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59091,0.00421089) , 
0, 116.716, 1, 0, 0.209825,0.0263054) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00543359) , 
0, 136.169, 1, 0, 0.5,0.130259)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.070453,-0.00731814) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.167496,0.00164435) , 
13, 0.140382, 1, 0, 0.107872,-0.00840454) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.740029,0.0041671) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.168116,-0.000317525) , 
19, 1.34942, 1, 0, 0.421999,0.0980148) , 
0, 97.2634, 1, 0, 0.209825,0.026135) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00540973) , 
0, 136.169, 1, 0, 0.5,0.129224)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00527535) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.209603,0.00230058) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0410886,-0.0118958) , 
18, 0.769909, 1, 0, 0.0948906,-0.00797879) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.177006,-5.48756e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.710373,0.00427468) , 
0, 102.356, 1, 0, 0.396345,0.0868671) , 
11, 0.277936, 1, 0, 0.202562,0.0258976) , 
19, 0.945647, 1, 0, 0.5,0.128334)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.103559,-0.00188408) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299772,0.00257805) , 
0, 94.4845, 1, 0, 0.157475,0.00803208) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59091,0.00413792) , 
0, 116.716, 1, 0, 0.209825,0.0261586) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.0053682) , 
0, 136.169, 1, 0, 0.5,0.127522)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00523351) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.632532,0.00548112) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.191666,-0.000924175) , 
17, 127.186, 1, 0, 0.333809,0.0661839) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0332129,-0.0101776) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0731521,-0.0191302) , 
5, 2.09439, 1, 0, 0.0423113,-0.0236716) , 
17, 181.877, 1, 0, 0.202562,0.0257264) , 
19, 0.945647, 1, 0, 0.5,0.126508)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.103559,-0.00182917) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299772,0.00253577) , 
0, 94.4845, 1, 0, 0.157475,0.00796575) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59091,0.00410698) , 
0, 116.716, 1, 0, 0.209825,0.0258788) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00533399) , 
0, 136.169, 1, 0, 0.5,0.125808)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0931962,-0.00191887) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.331069,0.0024132) , 
11, 0.302901, 1, 0, 0.157475,0.00798262) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59091,0.00407397) , 
0, 116.716, 1, 0, 0.209825,0.0257069) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00531143) , 
0, 136.169, 1, 0, 0.5,0.124806)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.103559,-0.00176845) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299772,0.00250125) , 
0, 94.4845, 1, 0, 0.157475,0.00798812) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59091,0.00404122) , 
0, 116.716, 1, 0, 0.209825,0.0255265) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00528912) , 
0, 136.169, 1, 0, 0.5,0.123805)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00515578) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.632532,0.00539915) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.191666,-0.000992518) , 
17, 127.186, 1, 0, 0.333809,0.0643029) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0332129,-0.00951035) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0731521,-0.0187452) , 
5, 2.09439, 1, 0, 0.0423113,-0.0228557) , 
17, 181.877, 1, 0, 0.202562,0.0250597) , 
19, 0.945647, 1, 0, 0.5,0.122816)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0931962,-0.00183593) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.331069,0.00235402) , 
11, 0.302901, 1, 0, 0.157475,0.00790085) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59091,0.00401141) , 
0, 116.716, 1, 0, 0.209825,0.0252341) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00525673) , 
0, 136.169, 1, 0, 0.5,0.122131)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.070453,-0.00668765) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.167496,0.00168713) , 
13, 0.140382, 1, 0, 0.107872,-0.00704447) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.740029,0.00398502) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.168116,-0.000423497) , 
19, 1.34942, 1, 0, 0.421999,0.091851) , 
0, 97.2634, 1, 0, 0.209825,0.0250531) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00523512) , 
0, 136.169, 1, 0, 0.5,0.121149)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0931962,-0.00173627) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.331069,0.00232774) , 
11, 0.302901, 1, 0, 0.157475,0.00807681) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59091,0.00395922) , 
0, 116.716, 1, 0, 0.209825,0.0250832) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00521372) , 
0, 136.169, 1, 0, 0.5,0.120302)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00508255) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.632532,0.00531038) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.191666,-0.0010344) , 
17, 127.186, 1, 0, 0.333809,0.0625754) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.150462,0.004217) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0130353,-0.264379) , 
12, 0.385552, 1, 0, 0.0423113,-0.0219033) , 
17, 181.877, 1, 0, 0.202562,0.0245388) , 
19, 0.945647, 1, 0, 0.5,0.119331)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.100033,-0.00649799) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.136661,0.00147561) , 
16, 76.4286, 1, 0, 0.127064,0.00232189) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.712599,0.00399509) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137593,-0.000403496) , 
18, 0.772657, 1, 0, 0.47191,0.1122) , 
0, 103.748, 1, 0, 0.209825,0.0286919) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00523525) , 
0, 136.169, 1, 0, 0.5,0.122064)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.103559,-0.00102793) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299772,0.00262304) , 
0, 94.4845, 1, 0, 0.157475,0.0112993) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59091,0.00412602) , 
0, 116.716, 1, 0, 0.209825,0.0285428) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00521483) , 
0, 136.169, 1, 0, 0.5,0.121125)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.103559,-0.00099702) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299772,0.00258969) , 
0, 94.4845, 1, 0, 0.157475,0.0112164) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59091,0.00409494) , 
0, 116.716, 1, 0, 0.209825,0.0282903) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00519464) , 
0, 136.169, 1, 0, 0.5,0.12013)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.103559,-0.00096704) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299772,0.00255672) , 
0, 94.4845, 1, 0, 0.157475,0.0111324) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59091,0.00406408) , 
0, 116.716, 1, 0, 0.209825,0.0280382) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00517464) , 
0, 136.169, 1, 0, 0.5,0.119141)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0931962,-0.000990357) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.331069,0.00240659) , 
11, 0.302901, 1, 0, 0.157475,0.0110471) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59091,0.00403344) , 
0, 116.716, 1, 0, 0.209825,0.0277864) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00515485) , 
0, 136.169, 1, 0, 0.5,0.11816)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.103559,-0.00095134) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299772,0.00251664) , 
0, 94.4845, 1, 0, 0.157475,0.0109503) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59091,0.00400301) , 
0, 116.716, 1, 0, 0.209825,0.027526) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00513526) , 
0, 136.169, 1, 0, 0.5,0.117179)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0931962,-0.00097179) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.331069,0.00236704) , 
11, 0.302901, 1, 0, 0.157475,0.010866) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59091,0.00397279) , 
0, 116.716, 1, 0, 0.209825,0.027278) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00511587) , 
0, 136.169, 1, 0, 0.5,0.116213)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.139311,0.00102303) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.030312,-0.108077) , 
16, 99.2856, 1, 0, 0.127064,0.00234721) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.712599,0.0038405) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137593,-0.001199) , 
18, 0.772657, 1, 0, 0.47191,0.105159) , 
0, 103.748, 1, 0, 0.209825,0.0270213) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00509666) , 
0, 136.169, 1, 0, 0.5,0.115247)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0931962,-0.000752703) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.331069,0.0023839) , 
11, 0.302901, 1, 0, 0.157475,0.0116925) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59091,0.00392429) , 
0, 116.716, 1, 0, 0.209825,0.0277114) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00507764) , 
0, 136.169, 1, 0, 0.5,0.114861)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.070453,-0.00486781) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.167496,0.00206568) , 
13, 0.140382, 1, 0, 0.107872,-0.00228825) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.740029,0.00379754) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.168116,0.00028109) , 
19, 1.34942, 1, 0, 0.421999,0.0892947) , 
0, 97.2634, 1, 0, 0.209825,0.027436) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.0050588) , 
0, 136.169, 1, 0, 0.5,0.113897)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.103559,-0.000701744) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299772,0.00247593) , 
0, 94.4845, 1, 0, 0.157475,0.0115797) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59091,0.00387461) , 
0, 116.716, 1, 0, 0.209825,0.0273186) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00504014) , 
0, 136.169, 1, 0, 0.5,0.113034)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0931962,-0.00073457) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.331069,0.00233947) , 
11, 0.302901, 1, 0, 0.157475,0.0114706) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59091,0.00384533) , 
0, 116.716, 1, 0, 0.209825,0.0270551) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00502165) , 
0, 136.169, 1, 0, 0.5,0.11209)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.070453,-0.00467899) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.167496,0.00200828) , 
13, 0.140382, 1, 0, 0.107872,-0.00210991) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.740029,0.00373726) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.168116,0.000168654) , 
19, 1.34942, 1, 0, 0.421999,0.0869179) , 
0, 97.2634, 1, 0, 0.209825,0.026785) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00500333) , 
0, 136.169, 1, 0, 0.5,0.111147)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0931962,-0.000702332) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.331069,0.00230412) , 
11, 0.302901, 1, 0, 0.157475,0.0113562) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59091,0.00379685) , 
0, 116.716, 1, 0, 0.209825,0.0266687) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00498518) , 
0, 136.169, 1, 0, 0.5,0.110304)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.070453,-0.00451776) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.167496,0.00194127) , 
13, 0.140382, 1, 0, 0.107872,-0.00201359) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.155131,-0.00245525) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.656599,0.0037136) , 
11, 0.253287, 1, 0, 0.421999,0.085533) , 
0, 97.2634, 1, 0, 0.209825,0.0264006) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00496719) , 
0, 136.169, 1, 0, 0.5,0.109375)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00482497) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.105205,0.00184134) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0609911,-0.0129053) , 
2, 2.99199, 1, 0, 0.0948906,-0.00148778) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.177006,0.00019063) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.710373,0.00385662) , 
0, 102.356, 1, 0, 0.396345,0.0757167) , 
11, 0.277936, 1, 0, 0.202562,0.0260876) , 
19, 0.945647, 1, 0, 0.5,0.108576)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.103559,-0.000656945) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299772,0.0023798) , 
0, 94.4845, 1, 0, 0.157475,0.0111286) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59091,0.00373974) , 
0, 116.716, 1, 0, 0.209825,0.0261084) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.0049348) , 
0, 136.169, 1, 0, 0.5,0.107761)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.0047924) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.105205,0.00174204) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0609911,-0.012376) , 
2, 2.99199, 1, 0, 0.0948906,-0.00148982) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.177006,0.000183089) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.710373,0.00380658) , 
0, 102.356, 1, 0, 0.396345,0.0743755) , 
11, 0.277936, 1, 0, 0.202562,0.0256072) , 
19, 0.945647, 1, 0, 0.5,0.106857)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.103559,-0.000652903) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299772,0.00233793) , 
0, 94.4845, 1, 0, 0.157475,0.0108817) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59091,0.00369532) , 
0, 116.716, 1, 0, 0.209825,0.0256207) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00490301) , 
0, 136.169, 1, 0, 0.5,0.106051)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00476041) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0622995,-0.0234414) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0762187,0.000976565) , 
2, 1.49603, 1, 0, 0.0736985,-0.00521006) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.210303,0.000864737) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.723944,0.00381958) , 
7, 77.1324, 1, 0, 0.381776,0.06732) , 
5, 2.09439, 1, 0, 0.202562,0.025128) , 
19, 0.945647, 1, 0, 0.5,0.105161)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0931962,-0.000679541) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.331069,0.00221628) , 
11, 0.302901, 1, 0, 0.157475,0.0108437) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59091,0.00364769) , 
0, 116.716, 1, 0, 0.209825,0.025304) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00487119) , 
0, 136.169, 1, 0, 0.5,0.104452)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.00472848) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.105205,0.00163497) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0609911,-0.0120006) , 
2, 2.99199, 1, 0, 0.0948906,-0.00162187) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626099,0.00357119) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0949779,-0.0070674) , 
17, 155.368, 1, 0, 0.396345,0.0723466) , 
11, 0.277936, 1, 0, 0.202562,0.0247977) , 
19, 0.945647, 1, 0, 0.5,0.10357)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0931962,-0.000654901) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.331069,0.00215968) , 
11, 0.302901, 1, 0, 0.157475,0.0105769) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59091,0.00361129) , 
0, 116.716, 1, 0, 0.209825,0.0248374) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00484303) , 
0, 136.169, 1, 0, 0.5,0.102849)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.070453,-0.00444222) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.167496,0.00193307) , 
13, 0.140382, 1, 0, 0.107872,-0.00188277) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.740029,0.00356097) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.168116,-0.000144719) , 
19, 1.34942, 1, 0, 0.421999,0.0796687) , 
0, 97.2634, 1, 0, 0.209825,0.0245856) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00482634) , 
0, 136.169, 1, 0, 0.5,0.10198)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.952447,0.0046849) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.076716,-0.00389983) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.137051,0.00363502) , 
13, 0.145545, 1, 0, 0.0948906,-0.00164412) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.626099,0.00350507) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0949779,-0.00691656) , 
17, 155.368, 1, 0, 0.396345,0.07065) , 
11, 0.277936, 1, 0, 0.202562,0.0241774) , 
19, 0.945647, 1, 0, 0.5,0.101208)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.103559,-0.000633783) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.299772,0.00222768) , 
0, 94.4845, 1, 0, 0.157475,0.0102427) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.59091,0.00355881) , 
0, 116.716, 1, 0, 0.209825,0.0242106) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.943483,0.00479975) , 
0, 136.169, 1, 0, 0.5,0.100482)    );
   return;
};
 
// Clean up
inline void ReaddarkHiggsWjetsSReta_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21Var::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double ReaddarkHiggsWjetsSReta_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_21Var::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
