// Class: Read2HDMaVWjetsSR_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_18Var
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : BDT::2HDMaVWjetsSR_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_18Var
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.06/01       [394753]
Creator        : svanputt
Date           : Tue Mar 17 18:33:15 2020
Host           : Linux vocms0315.cern.ch 2.6.32-573.26.1.el6.x86_64 #1 SMP Wed May 4 09:23:05 CEST 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /storage_mnt/storage/user/svanputt/monoHiggs/MVA/CMSSW_8_0_17/src/UATmva
Training events: 146755
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "True" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "True" [Print method-specific help message]
NTrees: "100" [Number of trees in the forest]
nCuts: "20" [Number of grid points in variable range used in finding optimal cut in node splitting]
BoostType: "Grad" [Boosting type for the trees in the forest (note: AdaCost is still experimental)]
Shrinkage: "1.000000e+00" [Learning rate for GradBoost algorithm]
SeparationType: "giniindex" [Separation criterion for node splitting]
PruneMethod: "costcomplexity" [Note: for BDTs use small trees (e.g.MaxDepth=3) and NoPruning:  Pruning: Method used for pruning (removal) of statistically insignificant branches ]
PruneStrength: "1.200000e+01" [Pruning strength]
UseBaggedGrad: "False" [deprecated: Use *UseBaggedBoost* instead:  Use only a random subsample of all events for growing the trees in each iteration.]
GradBaggingFraction: "6.000000e-01" [deprecated: Use *BaggedSampleFraction* instead: Defines the fraction of events to be used in each iteration, e.g. when UseBaggedGrad=kTRUE. ]
# Default:
VerbosityLevel: "Verbose" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
MaxDepth: "3" [Max depth of the decision tree allowed]
MinNodeSize: "5%" [Minimum percentage of training events required in a leaf node (default: Classification: 5%, Regression: 0.2%)]
AdaBoostR2Loss: "quadratic" [Type of Loss function in AdaBoostR2]
UseBaggedBoost: "False" [Use only a random subsample of all events for growing the trees in each boost iteration.]
AdaBoostBeta: "5.000000e-01" [Learning rate  for AdaBoost algorithm]
UseRandomisedTrees: "False" [Determine at each node splitting the cut variable only as the best out of a random subset of variables (like in RandomForests)]
UseNvars: "4" [Size of the subset of variables used with RandomisedTree option]
UsePoissonNvars: "True" [Interpret "UseNvars" not as fixed number but as mean of a Possion distribution in each split with RandomisedTree option]
BaggedSampleFraction: "6.000000e-01" [Relative size of bagged event sample to original size of the data sample (used whenever bagging is used (i.e. UseBaggedBoost, Bagging,)]
UseYesNoLeaf: "True" [Use Sig or Bkg categories, or the purity=S/(S+B) as classification of the leaf node -> Real-AdaBoost]
NegWeightTreatment: "ignorenegweightsintraining" [How to treat events with negative weights in the BDT training (particular the boosting) : IgnoreInTraining;  Boost With inverse boostweight; Pair events with negative and positive weights in traning sample and *annihilate* them (experimental!)]
Css: "1.000000e+00" [AdaCost: cost of true signal selected signal]
Cts_sb: "1.000000e+00" [AdaCost: cost of true signal selected bkg]
Ctb_ss: "1.000000e+00" [AdaCost: cost of true bkg    selected signal]
Cbb: "1.000000e+00" [AdaCost: cost of true bkg    selected bkg ]
NodePurityLimit: "5.000000e-01" [In boosting/pruning, nodes with purity > NodePurityLimit are signal; background otherwise.]
DoBoostMonitor: "False" [Create control plot with ROC integral vs tree number]
UseFisherCuts: "False" [Use multivariate splits using the Fisher criterion]
MinLinCorrForFisher: "8.000000e-01" [The minimum linear correlation between two variables demanded for use in Fisher criterion in node splitting]
UseExclusiveVars: "False" [Variables already used in fisher criterion are not anymore analysed individually for node splitting]
DoPreselection: "False" [and and apply automatic pre-selection for 100% efficient signal (bkg) cuts prior to training]
SigToBkgFraction: "1.000000e+00" [Sig to Bkg ratio used in Training (similar to NodePurityLimit, which cannot be used in real adaboost]
PruningValFraction: "5.000000e-01" [Fraction of events to use for optimizing automatic pruning.]
nEventsMin: "0" [deprecated: Use MinNodeSize (in % of training events) instead]
UseNTrainEvents: "0" [deprecated: Use *BaggedSampleFraction* instead: Number of randomly picked training events used in randomised (and bagged) trees]
NNodesMax: "0" [deprecated: Use MaxDepth instead to limit the tree size]
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 18
mtw1                          mtw1                          mtw1                          mtw1                                                            'F'    [29.8875827789,1306.83081055]
MHlnjj_dr_ljjVmet             MHlnjj_dr_ljjVmet             MHlnjj_dr_ljjVmet             MHlnjj_dr_ljjVmet                                               'F'    [0.0178854763508,7.0923333168]
MHlnjj_dphi_ljjVmet           MHlnjj_dphi_ljjVmet           MHlnjj_dphi_ljjVmet           MHlnjj_dphi_ljjVmet                                             'F'    [5.16651161888e-05,3.14159035683]
MHlnjj_dr_jjVl                MHlnjj_dr_jjVl                MHlnjj_dr_jjVl                MHlnjj_dr_jjVl                                                  'F'    [0.00099454598967,7.12494087219]
MHlnjj_dphi_jjVl              MHlnjj_dphi_jjVl              MHlnjj_dphi_jjVl              MHlnjj_dphi_jjVl                                                'F'    [3.28119494952e-06,3.14158821106]
MHlnjj_dphi_lVmet             MHlnjj_dphi_lVmet             MHlnjj_dphi_lVmet             MHlnjj_dphi_lVmet                                               'F'    [1.50000607967,3.14158368111]
MHlnjj_dr_lVmet               MHlnjj_dr_lVmet               MHlnjj_dr_lVmet               MHlnjj_dr_lVmet                                                 'F'    [1.5005967617,4.00708770752]
PuppiMET_pt                   PuppiMET_pt                   PuppiMET_pt                   PuppiMET_pt                                                     'F'    [50.0003929138,2046.80969238]
MHlnjj_pt_ljj                 MHlnjj_pt_ljj                 MHlnjj_pt_ljj                 MHlnjj_pt_ljj                                                   'F'    [0.946991443634,2294.85302734]
MHlnjj_m_lmetjj               MHlnjj_m_lmetjj               MHlnjj_m_lmetjj               MHlnjj_m_lmetjj                                                 'F'    [93.1993408203,4499.51953125]
MHlnjj_PTljj_D_PTmet          MHlnjj_PTljj_D_PTmet          MHlnjj_PTljj_D_PTmet          MHlnjj_PTljj_D_PTmet                                            'F'    [0.0147964144126,26.0707874298]
MHlnjj_PTljj_D_Mlmetjj        MHlnjj_PTljj_D_Mlmetjj        MHlnjj_PTljj_D_Mlmetjj        MHlnjj_PTljj_D_Mlmetjj                                          'F'    [0.00336579862051,2.50472545624]
MHlnjj_MINPTlj_D_PTmet        MHlnjj_MINPTlj_D_PTmet        MHlnjj_MINPTlj_D_PTmet        MHlnjj_MINPTlj_D_PTmet                                          'F'    [0.0148068051785,5.87077951431]
MHlnjj_MINPTlj_D_Mlmetjj      MHlnjj_MINPTlj_D_Mlmetjj      MHlnjj_MINPTlj_D_Mlmetjj      MHlnjj_MINPTlj_D_Mlmetjj                                        'F'    [0.00363438692875,0.600595116615]
MHlnjj_dphi_jVj               MHlnjj_dphi_jVj               MHlnjj_dphi_jVj               MHlnjj_dphi_jVj                                                 'F'    [0,1.99998223782]
MHlnjj_dr_jVj                 MHlnjj_dr_jVj                 MHlnjj_dr_jVj                 MHlnjj_dr_jVj                                                   'F'    [0.395072728395,7.80423927307]
MHlnjj_m_jj                   MHlnjj_m_jj                   MHlnjj_m_jj                   MHlnjj_m_jj                                                     'F'    [16.3461723328,2927.87280273]
MHlnjj_m_ljj                  MHlnjj_m_ljj                  MHlnjj_m_ljj                  MHlnjj_m_ljj                                                    'F'    [21.7504272461,4244.16455078]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#define NN new 2HDMaVWjetsSR_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_18VarNode
   
#ifndef 2HDMaVWjetsSR_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_18VarNode__def
#define 2HDMaVWjetsSR_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_18VarNode__def
   
class 2HDMaVWjetsSR_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_18VarNode {
   
public:
   
   // constructor of an essentially "empty" node floating in space
   2HDMaVWjetsSR_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_18VarNode ( 2HDMaVWjetsSR_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_18VarNode* left,2HDMaVWjetsSR_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_18VarNode* right,
                          int selector, double cutValue, bool cutType, 
                          int nodeType, double purity, double response ) :
   fLeft         ( left         ),
   fRight        ( right        ),
   fSelector     ( selector     ),
   fCutValue     ( cutValue     ),
   fCutType      ( cutType      ),
   fNodeType     ( nodeType     ),
   fPurity       ( purity       ),
   fResponse     ( response     ){
   }

   virtual ~2HDMaVWjetsSR_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_18VarNode();

   // test event if it decends the tree at this node to the right
   virtual bool GoesRight( const std::vector<double>& inputValues ) const;
   2HDMaVWjetsSR_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_18VarNode* GetRight( void )  {return fRight; };

   // test event if it decends the tree at this node to the left 
   virtual bool GoesLeft ( const std::vector<double>& inputValues ) const;
   2HDMaVWjetsSR_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_18VarNode* GetLeft( void ) { return fLeft; };   

   // return  S/(S+B) (purity) at this node (from  training)

   double GetPurity( void ) const { return fPurity; } 
   // return the node type
   int    GetNodeType( void ) const { return fNodeType; }
   double GetResponse(void) const {return fResponse;}

private:

   2HDMaVWjetsSR_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_18VarNode*   fLeft;     // pointer to the left daughter node
   2HDMaVWjetsSR_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_18VarNode*   fRight;    // pointer to the right daughter node
   int                     fSelector; // index of variable used in node selection (decision tree)   
   double                  fCutValue; // cut value appplied on this node to discriminate bkg against sig
   bool                    fCutType;  // true: if event variable > cutValue ==> signal , false otherwise
   int                     fNodeType; // Type of node: -1 == Bkg-leaf, 1 == Signal-leaf, 0 = internal 
   double                  fPurity;   // Purity of node from training
   double                  fResponse; // Regression response value of node
}; 
   
//_______________________________________________________________________
   2HDMaVWjetsSR_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_18VarNode::~2HDMaVWjetsSR_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_18VarNode()
{
   if (fLeft  != NULL) delete fLeft;
   if (fRight != NULL) delete fRight;
}; 
   
//_______________________________________________________________________
bool 2HDMaVWjetsSR_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_18VarNode::GoesRight( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the right
   bool result;
     result = (inputValues[fSelector] > fCutValue );
   if (fCutType == true) return result; //the cuts are selecting Signal ;
   else return !result;
}
   
//_______________________________________________________________________
bool 2HDMaVWjetsSR_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_18VarNode::GoesLeft( const std::vector<double>& inputValues ) const
{
   // test event if it decends the tree at this node to the left
   if (!this->GoesRight(inputValues)) return true;
   else return false;
}
   
#endif
   
#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class Read2HDMaVWjetsSR_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_18Var : public IClassifierReader {

 public:

   // constructor
   Read2HDMaVWjetsSR_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_18Var( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "Read2HDMaVWjetsSR_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_18Var" ),
        fNvars( 18 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "mtw1", "MHlnjj_dr_ljjVmet", "MHlnjj_dphi_ljjVmet", "MHlnjj_dr_jjVl", "MHlnjj_dphi_jjVl", "MHlnjj_dphi_lVmet", "MHlnjj_dr_lVmet", "PuppiMET_pt", "MHlnjj_pt_ljj", "MHlnjj_m_lmetjj", "MHlnjj_PTljj_D_PTmet", "MHlnjj_PTljj_D_Mlmetjj", "MHlnjj_MINPTlj_D_PTmet", "MHlnjj_MINPTlj_D_Mlmetjj", "MHlnjj_dphi_jVj", "MHlnjj_dr_jVj", "MHlnjj_m_jj", "MHlnjj_m_ljj" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;
      fVmin[17] = 0;
      fVmax[17] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~Read2HDMaVWjetsSR_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_18Var() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[18];
   double fVmax[18];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[18];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   std::vector<2HDMaVWjetsSR_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_18VarNode*> fForest;       // i.e. root nodes of decision trees
   std::vector<double>                fBoostWeights; // the weights applied in the individual boosts
};

double Read2HDMaVWjetsSR_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_18Var::GetMvaValue__( const std::vector<double>& inputValues ) const
{
   double myMVA = 0;
   for (unsigned int itree=0; itree<fForest.size(); itree++){
      2HDMaVWjetsSR_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_18VarNode *current = fForest[itree];
      while (current->GetNodeType() == 0) { //intermediate node
         if (current->GoesRight(inputValues)) current=(2HDMaVWjetsSR_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_18VarNode*)current->GetRight();
         else current=(2HDMaVWjetsSR_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_18VarNode*)current->GetLeft();
      }
      myMVA += current->GetResponse();
   }
   return 2.0/(1.0+exp(-2.0*myMVA))-1.0;
};

void Read2HDMaVWjetsSR_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_18Var::Initialize()
{
  // itree = 0
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.336718,-0.0195194) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.143991,-0.0845281) , 
15, 1.45436, 1, 0, 0.208529,-0.291471) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471855,-0.00196363) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.794101,0.0163812) , 
5, 2.28153, 1, 0, 0.66234,0.16234) , 
7, 91.2675, 1, 0, 0.301868,-0.198132) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.0302056) , 
7, 122.218, 1, 0, 0.5,1.53935e-15)    );
  // itree = 1
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.336718,-0.0183598) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.143991,-0.0750508) , 
15, 1.45436, 1, 0, 0.208529,-0.260159) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471855,-0.00189513) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.794101,0.0159293) , 
5, 2.28153, 1, 0, 0.66234,0.1579) , 
7, 91.2675, 1, 0, 0.301868,-0.174173) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.0292374) , 
7, 122.218, 1, 0, 0.5,0.0121721)    );
  // itree = 2
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.354701,-0.0130947) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.152939,-0.0653894) , 
15, 1.10159, 1, 0, 0.19061,-0.249892) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.401152,-0.00697218) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.739108,0.0143828) , 
5, 2.28167, 1, 0, 0.597617,0.104205) , 
7, 84.3897, 1, 0, 0.301868,-0.153097) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.0283494) , 
7, 122.218, 1, 0, 0.5,0.0224854)    );
  // itree = 3
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.161746,-0.0529248) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.330964,-0.0130208) , 
7, 73.5812, 1, 0, 0.208529,-0.208026) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471855,-0.001586) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.794101,0.0151147) , 
5, 2.28153, 1, 0, 0.66234,0.150764) , 
7, 91.2675, 1, 0, 0.301868,-0.134231) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.0275316) , 
7, 122.218, 1, 0, 0.5,0.0314039)    );
  // itree = 4
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.138536,-0.0635463) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.279102,-0.014716) , 
0, 93.7055, 1, 0, 0.201094,-0.204008) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.281233,-0.0223849) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.727608,0.0155373) , 
7, 80.9514, 1, 0, 0.563982,0.101498) , 
0, 113.14, 1, 0, 0.301868,-0.119169) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.0267758) , 
7, 122.218, 1, 0, 0.5,0.0378089)    );
  // itree = 5
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.17361,-0.0394827) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.361256,-0.00664477) , 
0, 113.14, 1, 0, 0.208529,-0.170619) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.471855,-0.000888511) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.794101,0.014436) , 
5, 2.28153, 1, 0, 0.66234,0.147204) , 
7, 91.2675, 1, 0, 0.301868,-0.105249) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.0260746) , 
7, 122.218, 1, 0, 0.5,0.043554)    );
  // itree = 6
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.161746,-0.0420997) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.39026,-0.00413923) , 
7, 73.5814, 1, 0, 0.24266,-0.13708) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.779848,0.0152225) , 
7, 105.023, 1, 0, 0.301868,-0.0938691) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.0254221) , 
7, 122.218, 1, 0, 0.5,0.0476587)    );
  // itree = 7
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.191696,-0.0265512) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.427519,0.000510862) , 
0, 113.14, 1, 0, 0.24266,-0.124204) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.779848,0.0148017) , 
7, 105.023, 1, 0, 0.301868,-0.083245) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.024813) , 
7, 122.218, 1, 0, 0.5,0.0513636)    );
  // itree = 8
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.147556,-0.0425443) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.341996,-0.00583447) , 
0, 96.818, 1, 0, 0.24266,-0.114973) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.779848,0.0143979) , 
7, 105.023, 1, 0, 0.301868,-0.0758401) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.0242427) , 
7, 122.218, 1, 0, 0.5,0.0529445)    );
  // itree = 9
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.174657,-0.0362905) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.329328,-0.00407478) , 
11, 0.46752, 1, 0, 0.24266,-0.104331) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.779848,0.0140099) , 
7, 105.023, 1, 0, 0.301868,-0.0671564) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.0237072) , 
7, 122.218, 1, 0, 0.5,0.0555374)    );
  // itree = 10
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.354701,-0.00224177) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.152939,-0.0395327) , 
15, 1.10159, 1, 0, 0.19061,-0.121794) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.401152,-0.00401052) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.739108,0.0132761) , 
5, 2.28167, 1, 0, 0.597617,0.106338) , 
7, 84.3897, 1, 0, 0.301868,-0.0594325) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.0232032) , 
7, 122.218, 1, 0, 0.5,0.0575753)    );
  // itree = 11
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.268219,-0.0054869) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.139254,-0.0531388) , 
9, 264.711, 1, 0, 0.201094,-0.111374) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673058,0.0145383) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302399,-0.0173574) , 
17, 214.351, 1, 0, 0.563982,0.107647) , 
0, 113.14, 1, 0, 0.301868,-0.0505518) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.0227275) , 
7, 122.218, 1, 0, 0.5,0.0605321)    );
  // itree = 12
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.247319,-0.010201) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.101981,-0.109692) , 
17, 208.277, 1, 0, 0.208529,-0.0899813) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.489282,0.00134378) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.802624,0.0132009) , 
5, 2.35968, 1, 0, 0.66234,0.141605) , 
7, 91.2675, 1, 0, 0.301868,-0.0423491) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.0222774) , 
7, 122.218, 1, 0, 0.5,0.0631228)    );
  // itree = 13
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.153678,-0.0279783) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.392996,0.000162362) , 
7, 74.0729, 1, 0, 0.237767,-0.0707203) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.660943,0.014962) , 
0, 129.463, 1, 0, 0.301868,-0.03206) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.0218507) , 
7, 122.218, 1, 0, 0.5,0.0672738)    );
  // itree = 14
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.133643,-0.0367428) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.317507,-0.00245739) , 
0, 92.1542, 1, 0, 0.237767,-0.0638968) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.660943,0.0144279) , 
0, 129.463, 1, 0, 0.301868,-0.0273327) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.0214452) , 
7, 122.218, 1, 0, 0.5,0.0676418)    );
  // itree = 15
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.161746,-0.0226162) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.39026,0.00124812) , 
7, 73.5814, 1, 0, 0.24266,-0.0521448) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.779848,0.0130658) , 
7, 105.023, 1, 0, 0.301868,-0.0229173) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.021059) , 
7, 122.218, 1, 0, 0.5,0.0678886)    );
  // itree = 16
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.300108,-0.000109054) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.187517,-0.0241903) , 
9, 264.711, 1, 0, 0.237767,-0.0528115) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.660943,0.0139147) , 
0, 129.463, 1, 0, 0.301868,-0.019067) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.0206904) , 
7, 122.218, 1, 0, 0.5,0.0678344)    );
  // itree = 17
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.422927,0.00581324) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.198253,-0.0130678) , 
15, 1.10159, 1, 0, 0.24266,-0.0433965) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.779848,0.0127977) , 
7, 105.023, 1, 0, 0.301868,-0.0157794) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.020338) , 
7, 122.218, 1, 0, 0.5,0.0674774)    );
  // itree = 18
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.268219,-0.00187542) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.139254,-0.036484) , 
9, 264.711, 1, 0, 0.201094,-0.0606443) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673058,0.0136742) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302399,-0.0101584) , 
17, 214.351, 1, 0, 0.563982,0.109221) , 
0, 113.14, 1, 0, 0.301868,-0.0134728) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.0200002) , 
7, 122.218, 1, 0, 0.5,0.0665229)    );
  // itree = 19
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.147556,-0.0226299) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.341996,0.00117745) , 
0, 96.818, 1, 0, 0.24266,-0.0354318) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.779848,0.0125033) , 
7, 105.023, 1, 0, 0.301868,-0.00942831) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.019676) , 
7, 122.218, 1, 0, 0.5,0.0668661)    );
  // itree = 20
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.161746,-0.0173292) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.39026,0.00271185) , 
7, 73.5814, 1, 0, 0.24266,-0.0317621) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.779848,0.0121903) , 
7, 105.023, 1, 0, 0.301868,-0.00682177) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.0193642) , 
7, 122.218, 1, 0, 0.5,0.0662867)    );
  // itree = 21
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.422927,0.00672736) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.198253,-0.0100121) , 
15, 1.10159, 1, 0, 0.24266,-0.0284033) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.779848,0.0118866) , 
7, 105.023, 1, 0, 0.301868,-0.00447268) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.0190638) , 
7, 122.218, 1, 0, 0.5,0.0656064)    );
  // itree = 22
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.259241,-0.00196279) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.117553,-0.0791134) , 
6, 3.1699, 1, 0, 0.237767,-0.0312758) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.660943,0.0129762) , 
0, 129.463, 1, 0, 0.301868,-0.00310603) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.0187738) , 
7, 122.218, 1, 0, 0.5,0.0643163)    );
  // itree = 23
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.268219,-1.05227e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.139254,-0.0291407) , 
9, 264.711, 1, 0, 0.201094,-0.0396893) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.673058,0.0130249) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.302399,-0.00899766) , 
17, 214.351, 1, 0, 0.563982,0.103162) , 
0, 113.14, 1, 0, 0.301868,-1.94649e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.0184935) , 
7, 122.218, 1, 0, 0.5,0.0643006)    );
  // itree = 24
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.374288,0.004708) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.174967,-0.010564) , 
15, 1.45436, 1, 0, 0.24266,-0.0194959) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.779848,0.0115416) , 
7, 105.023, 1, 0, 0.301868,0.0025476) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.018222) , 
7, 122.218, 1, 0, 0.5,0.0639933)    );
  // itree = 25
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.116434,-0.0261856) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.227145,-0.00227331) , 
7, 58.1882, 1, 0, 0.19061,-0.034336) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678489,0.0102028) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391486,-0.00935292) , 
16, 121.98, 1, 0, 0.597617,0.103606) , 
7, 84.3897, 1, 0, 0.301868,0.00337122) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.0179587) , 
7, 122.218, 1, 0, 0.5,0.0625375)    );
  // itree = 26
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228128,-0.00191083) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.11259,-0.0626812) , 
6, 3.1699, 1, 0, 0.208529,-0.02502) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.77623,0.0108506) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.524004,0.00173392) , 
17, 135.842, 1, 0, 0.66234,0.121318) , 
7, 91.2675, 1, 0, 0.301868,0.00507865) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.0177029) , 
7, 122.218, 1, 0, 0.5,0.0617653)    );
  // itree = 27
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.116297,-0.0425617) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.293104,0.00145018) , 
0, 87.4907, 1, 0, 0.237767,-0.0171299) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.660943,0.0124392) , 
0, 129.463, 1, 0, 0.301868,0.0074705) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.0174541) , 
7, 122.218, 1, 0, 0.5,0.0615353)    );
  // itree = 28
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.422927,0.00786363) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.198253,-0.0059396) , 
15, 1.10159, 1, 0, 0.24266,-0.00978875) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.779848,0.0108604) , 
7, 105.023, 1, 0, 0.301868,0.00967689) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.0172116) , 
7, 122.218, 1, 0, 0.5,0.061238)    );
  // itree = 29
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.300108,0.00316163) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.187517,-0.0125943) , 
9, 264.711, 1, 0, 0.237767,-0.012974) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.660943,0.0119411) , 
0, 129.463, 1, 0, 0.301868,0.00991431) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.016975) , 
7, 122.218, 1, 0, 0.5,0.0596259)    );
  // itree = 30
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.116434,-0.0213847) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.227145,-0.000237012) , 
7, 58.1882, 1, 0, 0.19061,-0.0222629) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678489,0.00973588) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391486,-0.00887834) , 
16, 121.98, 1, 0, 0.597617,0.0977438) , 
7, 84.3897, 1, 0, 0.301868,0.0105417) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.0167438) , 
7, 122.218, 1, 0, 0.5,0.0583443)    );
  // itree = 31
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.376234,0.0064149) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.187416,-0.0064369) , 
3, 0.679735, 1, 0, 0.24266,-0.00677636) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.779848,0.0104779) , 
7, 105.023, 1, 0, 0.301868,0.0114707) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.0165177) , 
7, 122.218, 1, 0, 0.5,0.0573296)    );
  // itree = 32
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.268219,0.00166015) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.139254,-0.0209718) , 
9, 264.711, 1, 0, 0.201094,-0.0199736) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.228211,-0.0110778) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.688994,0.0114305) , 
7, 74.0766, 1, 0, 0.563982,0.0935516) , 
0, 113.14, 1, 0, 0.301868,0.0115524) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.0162961) , 
7, 122.218, 1, 0, 0.5,0.0557774)    );
  // itree = 33
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0848862,-0.0876282) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.20306,-0.00250177) , 
11, 0.436296, 1, 0, 0.139608,-0.0506235) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678748,0.00837931) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.25319,7.66344e-05) , 
12, 0.550929, 1, 0, 0.494401,0.0631581) , 
0, 95.1481, 1, 0, 0.350063,0.016869) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.926802,0.0191971) , 
0, 152.986, 1, 0, 0.5,0.0551217)    );
  // itree = 34
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.210311,0.000204227) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0969087,-0.0536734) , 
6, 3.1699, 1, 0, 0.19061,-0.0125075) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.678489,0.00942661) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.391486,-0.0083449) , 
16, 121.98, 1, 0, 0.597617,0.0938554) , 
7, 84.3897, 1, 0, 0.301868,0.0165674) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.0158564) , 
7, 122.218, 1, 0, 0.5,0.0562698)    );
  // itree = 35
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.179819,-0.00527082) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.413542,0.00423359) , 
0, 102.033, 1, 0, 0.256044,-0.00280461) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.743388,0.0115721) , 
0, 124.066, 1, 0, 0.350063,0.0211835) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.926802,0.0186589) , 
0, 152.986, 1, 0, 0.5,0.0556418)    );
  // itree = 36
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.199791,0.00233918) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.125917,-0.0438109) , 
4, 0.89765, 1, 0, 0.164694,-0.0231381) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.876538,0.0171045) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.683891,0.00758605) , 
15, 1.42268, 1, 0, 0.785116,0.12519) , 
0, 92.257, 1, 0, 0.657709,0.0947301) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.326484,0.00641059) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.105367,-0.0601403) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.216131,-0.0007659) , 
2, 2.5434, 1, 0, 0.170924,-0.0408756) , 
14, 0.571598, 1, 0, 0.202742,-0.0234448) , 
12, 0.572518, 1, 0, 0.5,0.0537661)    );
  // itree = 37
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.296551,0.00383514) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.224511,-0.00559972) , 
9, 264.711, 1, 0, 0.256044,2.81181e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.743388,0.011154) , 
0, 124.066, 1, 0, 0.350063,0.0221823) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.926802,0.0181408) , 
0, 152.986, 1, 0, 0.5,0.0539626)    );
  // itree = 38
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.222396,0.00346812) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.100768,-0.0432115) , 
6, 2.45295, 1, 0, 0.164694,-0.0178047) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.876538,0.0165221) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.683891,0.00723084) , 
15, 1.42268, 1, 0, 0.785116,0.117749) , 
0, 92.257, 1, 0, 0.657709,0.0899127) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.326484,0.00583737) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.105367,-0.0520478) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.216131,-0.000897811) , 
2, 2.5434, 1, 0, 0.170924,-0.0345876) , 
14, 0.571598, 1, 0, 0.202742,-0.0192239) , 
12, 0.572518, 1, 0, 0.5,0.0520817)    );
  // itree = 39
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.422927,0.0074731) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.198253,-0.00186843) , 
15, 1.10159, 1, 0, 0.24266,0.00531922) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.779848,0.00926089) , 
7, 105.023, 1, 0, 0.301868,0.0193282) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.0148294) , 
7, 122.218, 1, 0, 0.5,0.051962)    );
  // itree = 40
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.296551,0.00388761) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.224511,-0.00513904) , 
9, 264.711, 1, 0, 0.256044,0.00147146) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.743388,0.0105996) , 
0, 124.066, 1, 0, 0.350063,0.0216065) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.926802,0.0174389) , 
0, 152.986, 1, 0, 0.5,0.0503014)    );
  // itree = 41
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.113677,-0.0404873) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.21415,0.00361803) , 
8, 101.38, 1, 0, 0.164694,-0.0136763) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.81092,0.0124488) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.72242,0.00664246) , 
16, 124.632, 1, 0, 0.785116,0.107859) , 
0, 92.257, 1, 0, 0.657709,0.0829011) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.34078,0.00300439) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.167387,-0.00245129) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.051689,-0.175642) , 
10, 2.48895, 1, 0, 0.138664,-0.0350552) , 
15, 1.45436, 1, 0, 0.202742,-0.0162475) , 
12, 0.572518, 1, 0, 0.5,0.0485324)    );
  // itree = 42
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.179631,0.00029567) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0886476,-0.0431487) , 
6, 2.57197, 1, 0, 0.139608,-0.0242302) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.756022,0.0075725) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.354486,0.0036389) , 
10, 1.27019, 1, 0, 0.494401,0.0555387) , 
0, 95.1481, 1, 0, 0.350063,0.0230868) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.926802,0.0171342) , 
0, 152.986, 1, 0, 0.5,0.0496981)    );
  // itree = 43
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.296551,0.00415775) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.224511,-0.00400928) , 
9, 264.711, 1, 0, 0.256044,0.00524356) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.743388,0.0103956) , 
0, 124.066, 1, 0, 0.350063,0.0237709) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.926802,0.0168122) , 
0, 152.986, 1, 0, 0.5,0.0489272)    );
  // itree = 44
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.199791,0.00487417) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.125917,-0.0294231) , 
4, 0.89765, 1, 0, 0.164694,-0.00567328) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.81092,0.0118023) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.72242,0.00591623) , 
16, 124.632, 1, 0, 0.785116,0.0985909) , 
0, 92.257, 1, 0, 0.657709,0.0771798) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0672982,-0.052937) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.265991,0.00384609) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.145813,-0.024496) , 
6, 3.17247, 1, 0, 0.241348,0.00552025) , 
0, 86.2873, 1, 0, 0.202742,-0.00941889) , 
12, 0.572518, 1, 0, 0.5,0.0471613)    );
  // itree = 45
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.261129,0.00344961) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.149178,-0.0258835) , 
6, 3.17166, 1, 0, 0.24266,0.00916004) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.779848,0.00826523) , 
7, 105.023, 1, 0, 0.301868,0.0205914) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.0137377) , 
7, 122.218, 1, 0, 0.5,0.0467556)    );
  // itree = 46
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.296551,0.00407498) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.224511,-0.00372506) , 
9, 264.711, 1, 0, 0.256044,0.0057267) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.743388,0.0099017) , 
0, 124.066, 1, 0, 0.350063,0.0227164) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.926802,0.0162047) , 
0, 152.986, 1, 0, 0.5,0.0455806)    );
  // itree = 47
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.229234,0.00511307) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.110708,-0.0231493) , 
6, 2.33393, 1, 0, 0.164694,-0.00371015) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.81092,0.0112229) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.72242,0.00531446) , 
16, 124.632, 1, 0, 0.785116,0.090552) , 
0, 92.257, 1, 0, 0.657709,0.0711948) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.333242,0.00618547) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.191768,-0.000647189) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0967238,-0.0576059) , 
10, 2.51053, 1, 0, 0.169898,-0.0207495) , 
4, 0.299135, 1, 0, 0.202742,-0.00747145) , 
12, 0.572518, 1, 0, 0.5,0.043926)    );
  // itree = 48
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.296551,0.00393721) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.224511,-0.00344128) , 
9, 264.711, 1, 0, 0.256044,0.00594197) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.743388,0.00958099) , 
0, 124.066, 1, 0, 0.350063,0.0219929) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.926802,0.0158128) , 
0, 152.986, 1, 0, 0.5,0.043462)    );
  // itree = 49
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.328615,0.00526853) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.185359,-0.00265865) , 
14, 0.952372, 1, 0, 0.24266,0.00849595) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.779848,0.00761258) , 
7, 105.023, 1, 0, 0.301868,0.0186799) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.0130289) , 
7, 122.218, 1, 0, 0.5,0.0418752)    );
  // itree = 50
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.261129,0.00307333) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.149178,-0.0233274) , 
6, 3.17166, 1, 0, 0.24266,0.00819363) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.779848,0.00742538) , 
7, 105.023, 1, 0, 0.301868,0.0180705) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.0128514) , 
7, 122.218, 1, 0, 0.5,0.0405294)    );
  // itree = 51
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.113677,-0.0277618) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.21415,0.00464014) , 
8, 101.38, 1, 0, 0.164694,-0.0026656) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.81092,0.0105224) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.72242,0.00451022) , 
16, 124.632, 1, 0, 0.785116,0.0809288) , 
0, 92.257, 1, 0, 0.657709,0.0637623) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.32957,0.0038331) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.102927,-0.0512294) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.166766,0.000239148) , 
3, 0.979769, 1, 0, 0.146135,-0.0228592) , 
3, 0.682949, 1, 0, 0.202742,-0.00618961) , 
12, 0.572518, 1, 0, 0.5,0.0395143)    );
  // itree = 52
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.267877,0.00323621) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.234526,-0.00631132) , 
8, 129.833, 1, 0, 0.256044,0.005667) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.743388,0.00902569) , 
0, 124.066, 1, 0, 0.350063,0.0201828) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.926802,0.0150668) , 
0, 152.986, 1, 0, 0.5,0.0392778)    );
  // itree = 53
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.541632,0.00975276) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.338058,-0.000236947) , 
4, 0.448776, 1, 0, 0.455273,0.0533986) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.137718,-0.0134595) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.263643,0.0037239) , 
5, 2.12533, 1, 0, 0.215015,-0.00267974) , 
15, 1.45436, 1, 0, 0.301868,0.0175925) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.0123738) , 
7, 122.218, 1, 0, 0.5,0.0379361)    );
  // itree = 54
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526067,0.00538847) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.378012,-0.00959854) , 
6, 1.97614, 1, 0, 0.449737,-0.00237875) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.203033,0.0040312) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.837239,0.0106973) , 
0, 98.9924, 1, 0, 0.710417,0.0743961) , 
5, 1.96904, 1, 0, 0.657709,0.0588727) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0672982,-0.0439231) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.250242,0.00469645) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.223198,-0.0131238) , 
9, 360.022, 1, 0, 0.241348,0.00784953) , 
0, 86.2873, 1, 0, 0.202742,-0.004657) , 
12, 0.572518, 1, 0, 0.5,0.0368508)    );
  // itree = 55
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.267877,0.00314875) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.234526,-0.006067) , 
8, 129.833, 1, 0, 0.256044,0.00560326) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.743388,0.00848511) , 
0, 124.066, 1, 0, 0.350063,0.0188028) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.926802,0.0144776) , 
0, 152.986, 1, 0, 0.5,0.0362121)    );
  // itree = 56
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.183205,-0.00450562) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.621617,0.00559394) , 
0, 99.6345, 1, 0, 0.39199,0.0261804) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.953839,0.0141574) , 
0, 133.706, 1, 0, 0.646465,0.057248) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504644,0.00780578) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.174897,-0.000484706) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.158071,-0.0314102) , 
9, 315.065, 1, 0, 0.16696,-0.028449) , 
15, 1.10159, 1, 0, 0.260021,-0.00152141) , 
10, 1.73303, 1, 0, 0.5,0.034974)    );
  // itree = 57
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.155887,0.00286636) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.243472,-0.0148232) , 
7, 76.3834, 1, 0, 0.174523,-0.00604337) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.801356,0.00707904) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.384195,0.00190889) , 
10, 1.27019, 1, 0, 0.5432,0.0455989) , 
0, 100.932, 1, 0, 0.350063,0.0185454) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.926802,0.0140801) , 
0, 152.986, 1, 0, 0.5,0.0346265)    );
  // itree = 58
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.810259,0.0151157) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.673246,0.00886787) , 
15, 0.804755, 1, 0, 0.740298,0.0893033) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.791792,0.00877806) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.27696,-0.00498394) , 
12, 0.435718, 1, 0, 0.567241,0.0258137) , 
4, 0.448776, 1, 0, 0.672189,0.064316) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.423692,-0.00458557) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.709531,0.00883115) , 
5, 1.89084, 1, 0, 0.637197,0.0524559) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.241863,-9.52599e-05) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.124282,-0.0639492) , 
6, 3.16943, 1, 0, 0.220956,-0.0131949) , 
10, 1.25187, 1, 0, 0.369029,0.0101597) , 
15, 1.45436, 1, 0, 0.5,0.0335562)    );
  // itree = 59
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.183205,-0.00380415) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.621617,0.00526865) , 
0, 99.6345, 1, 0, 0.39199,0.0252235) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.953839,0.0136992) , 
0, 133.706, 1, 0, 0.646465,0.0534684) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.406474,0.00876999) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.158937,-0.0171962) , 
16, 92.2817, 1, 0, 0.314823,0.0233469) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.105302,-0.0806193) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.126372,-0.0471004) , 
14, 1.23803, 1, 0, 0.115643,-0.0635649) , 
17, 210.649, 1, 0, 0.260021,-0.000566024) , 
10, 1.73303, 1, 0, 0.5,0.032989)    );
  // itree = 60
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.132234,0.000581948) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.172427,-0.0301331) , 
7, 76.3834, 1, 0, 0.139608,-0.010707) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.595814,0.00784839) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.438851,0.00187275) , 
3, 0.679989, 1, 0, 0.494401,0.0388895) , 
0, 95.1481, 1, 0, 0.350063,0.0187125) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.926802,0.0137124) , 
0, 152.986, 1, 0, 0.5,0.0333062)    );
  // itree = 61
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.526067,0.00542064) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.378012,-0.00876181) , 
6, 1.97614, 1, 0, 0.449737,0.000164057) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.203033,0.00444545) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.837239,0.00953515) , 
0, 98.9924, 1, 0, 0.710417,0.062687) , 
5, 1.96904, 1, 0, 0.657709,0.0500453) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0672982,-0.0372896) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.179502,-0.0157653) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.257434,0.00382444) , 
5, 2.04751, 1, 0, 0.241348,0.0101177) , 
0, 86.2873, 1, 0, 0.202742,-0.00086854) , 
12, 0.572518, 1, 0, 0.5,0.0323966)    );
  // itree = 62
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.183205,-0.00274575) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.621617,0.00486814) , 
0, 99.6345, 1, 0, 0.39199,0.0246151) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.953839,0.013217) , 
0, 133.706, 1, 0, 0.646465,0.0499404) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.504644,0.00647344) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.0693329,-0.11691) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.195079,-0.00192406) , 
5, 1.96906, 1, 0, 0.16696,-0.0191729) , 
15, 1.10159, 1, 0, 0.260021,0.00191404) , 
10, 1.73303, 1, 0, 0.5,0.0317381)    );
  // itree = 63
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.431593,0.00645759) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.247903,0.00148805) , 
14, 0.952372, 1, 0, 0.318598,0.026877) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.363594,0.000871733) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0813813,-0.0786141) , 
3, 0.66921, 1, 0, 0.216298,-0.0296445) , 
6, 3.17166, 1, 0, 0.301868,0.0176333) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.0108297) , 
7, 122.218, 1, 0, 0.5,0.0319248)    );
  // itree = 64
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.245717,-0.00039206) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.292592,0.00480519) , 
13, 0.175736, 1, 0, 0.256044,0.00852496) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.743388,0.00779562) , 
0, 124.066, 1, 0, 0.350063,0.0190404) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.926802,0.0130299) , 
0, 152.986, 1, 0, 0.5,0.0314797)    );
  // itree = 65
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.653577,0.00712221) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.375212,-0.00224996) , 
14, 0.857135, 1, 0, 0.449004,0.0065073) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.757301,0.00980765) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.624689,0.00409778) , 
6, 3.20124, 1, 0, 0.735104,0.0644537) , 
5, 2.12538, 1, 0, 0.646465,0.0465008) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.406474,0.00789722) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.158937,-0.0141594) , 
16, 92.2817, 1, 0, 0.314823,0.022567) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.115455,-0.0292852) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.115838,-0.0713098) , 
5, 2.35986, 1, 0, 0.115643,-0.045988) , 
17, 210.649, 1, 0, 0.260021,0.00370473) , 
10, 1.73303, 1, 0, 0.5,0.0302808)    );
  // itree = 66
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.267877,0.00313105) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.234526,-0.00421513) , 
8, 129.833, 1, 0, 0.256044,0.00808275) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.743388,0.00764007) , 
0, 124.066, 1, 0, 0.350063,0.018253) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.926802,0.0128176) , 
0, 152.986, 1, 0, 0.5,0.0301311)    );
  // itree = 67
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.551122,0.00769135) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.297504,0.00315971) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.163472,-0.0163777) , 
6, 3.17166, 1, 0, 0.276667,0.0108428) , 
15, 0.748823, 1, 0, 0.301868,0.0164163) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.0102504) , 
7, 122.218, 1, 0, 0.5,0.0290515)    );
  // itree = 68
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.245717,-0.000497686) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.292592,0.00437891) , 
13, 0.175736, 1, 0, 0.256044,0.00729504) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.743388,0.00731475) , 
0, 124.066, 1, 0, 0.350063,0.0169752) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.926802,0.0124012) , 
0, 152.986, 1, 0, 0.5,0.0281493)    );
  // itree = 69
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.784774,0.0106426) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.656976,0.00203088) , 
17, 167.545, 1, 0, 0.757577,0.0597552) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.524493,0.000588088) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.554271,0.0072153) , 
1, 3.39576, 1, 0, 0.530325,0.0159432) , 
4, 0.59843, 1, 0, 0.657709,0.0405017) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.326484,0.00492287) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.137101,-0.0125042) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.255628,0.00644509) , 
5, 2.67251, 1, 0, 0.170924,-0.00673737) , 
14, 0.571598, 1, 0, 0.202742,0.00177704) , 
12, 0.572518, 1, 0, 0.5,0.0270782)    );
  // itree = 70
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.238925,0.00612038) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.243733,-0.000111031) , 
6, 2.21689, 1, 0, 0.24266,0.00873989) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.779848,0.00530997) , 
7, 105.023, 1, 0, 0.301868,0.0145189) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.00982531) , 
7, 122.218, 1, 0, 0.5,0.0263806)    );
  // itree = 71
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39508,0.00458846) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.281806,-0.0062551) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.246933,-0.0162907) , 
4, 0.897564, 1, 0, 0.264389,-0.0428824) , 
6, 1.97614, 1, 0, 0.324186,-0.00766869) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.663538,0.00636183) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.812004,0.0107458) , 
11, 0.447666, 1, 0, 0.712368,0.0522947) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.207793,-0.00383223) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454869,0.00497572) , 
11, 0.587907, 1, 0, 0.289409,0.00695223) , 
10, 1.74055, 1, 0, 0.549331,0.0348167) , 
5, 1.96904, 1, 0, 0.5,0.0255077)    );
  // itree = 72
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.25022,0.00114177) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.459271,0.00518074) , 
5, 2.51571, 1, 0, 0.318598,0.0203284) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.363594,0.000113323) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0813813,-0.0617761) , 
3, 0.66921, 1, 0, 0.216298,-0.0227599) , 
6, 3.17166, 1, 0, 0.301868,0.0132817) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.00956726) , 
7, 122.218, 1, 0, 0.5,0.0247601)    );
  // itree = 73
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.179631,0.00449581) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0886476,-0.029128) , 
6, 2.57197, 1, 0, 0.139608,-0.00756832) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.589955,0.00615135) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.408116,0.000681233) , 
14, 0.952352, 1, 0, 0.494401,0.0293966) , 
0, 95.1481, 1, 0, 0.350063,0.0143584) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.926802,0.0116519) , 
0, 152.986, 1, 0, 0.5,0.024403)    );
  // itree = 74
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39508,0.00418185) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.281806,-0.00614351) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.246933,-0.0155266) , 
4, 0.897564, 1, 0, 0.264389,-0.0411619) , 
6, 1.97614, 1, 0, 0.324186,-0.00815227) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.677457,0.00647955) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.794,0.00962404) , 
2, 2.99199, 1, 0, 0.712368,0.0491539) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.207793,-0.00315949) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454869,0.00455523) , 
11, 0.587907, 1, 0, 0.289409,0.00711939) , 
10, 1.74055, 1, 0, 0.549331,0.032951) , 
5, 1.96904, 1, 0, 0.5,0.0239449)    );
  // itree = 75
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39508,0.00402867) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.204615,-0.0321107) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.329097,-0.0034089) , 
3, 1.3102, 1, 0, 0.264389,-0.0387146) , 
6, 1.97614, 1, 0, 0.324186,-0.0073503) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.677457,0.00623893) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.794,0.00940504) , 
2, 2.99199, 1, 0, 0.712368,0.0473744) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.207793,-0.0028987) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.454869,0.00435494) , 
11, 0.587907, 1, 0, 0.289409,0.00706309) , 
10, 1.74055, 1, 0, 0.549331,0.0318357) , 
5, 1.96904, 1, 0, 0.5,0.0232497)    );
  // itree = 76
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.443283,0.00703351) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.307349,0.00255167) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0676283,-0.11283) , 
12, 0.899514, 1, 0, 0.287211,0.00746363) , 
4, 0.149637, 1, 0, 0.301868,0.0123754) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.00907816) , 
7, 122.218, 1, 0, 0.5,0.0227771)    );
  // itree = 77
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.810259,0.0117366) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.673246,0.00577788) , 
15, 0.804755, 1, 0, 0.740298,0.0587672) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.791792,0.00640287) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.27696,-0.00523271) , 
12, 0.435718, 1, 0, 0.567241,0.0124025) , 
4, 0.448776, 1, 0, 0.672189,0.0405196) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.226422,-0.00739465) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.338356,0.00100309) , 
3, 1.63104, 1, 0, 0.270231,-0.0198009) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.503936,0.00754861) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.336894,-0.00418047) , 
6, 2.93347, 1, 0, 0.426845,0.026865) , 
5, 2.12533, 1, 0, 0.369029,0.00963794) , 
15, 1.45436, 1, 0, 0.5,0.0229794)    );
  // itree = 78
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.245717,-0.000934903) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.292592,0.0040144) , 
13, 0.175736, 1, 0, 0.256044,0.00496822) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.743388,0.00653404) , 
0, 124.066, 1, 0, 0.350063,0.013282) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.926802,0.0110922) , 
0, 152.986, 1, 0, 0.5,0.0222761)    );
  // itree = 79
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.245717,-0.000883557) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.292592,0.00386993) , 
13, 0.175736, 1, 0, 0.256044,0.00486674) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.743388,0.00632521) , 
0, 124.066, 1, 0, 0.350063,0.0128443) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.926802,0.0108213) , 
0, 152.986, 1, 0, 0.5,0.0214466)    );
  // itree = 80
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402441,0.00834277) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.167403,-0.00899938) , 
17, 137.647, 1, 0, 0.278464,0.0378589) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.149129,-0.0127602) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.353304,0.00237591) , 
5, 2.20355, 1, 0, 0.308513,0.00383633) , 
6, 2.21689, 1, 0, 0.301868,0.0113602) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.00853002) , 
7, 122.218, 1, 0, 0.5,0.0206453)    );
  // itree = 81
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.669175,0.00527774) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.791703,0.00986375) , 
5, 2.82896, 1, 0, 0.719836,0.0482923) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.415751,-0.00728092) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.652289,0.0039178) , 
2, 2.84236, 1, 0, 0.528712,-0.000706431) , 
4, 0.598343, 1, 0, 0.672189,0.0360769) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.295725,-0.00350869) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.474805,0.0058455) , 
5, 2.12533, 1, 0, 0.408057,0.0157606) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0615552,-0.087477) , 
10, 2.48895, 1, 0, 0.369029,0.00826123) , 
15, 1.45436, 1, 0, 0.5,0.0202781)    );
  // itree = 82
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.245717,-0.000810296) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.292592,0.00366246) , 
13, 0.175736, 1, 0, 0.256044,0.00472051) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.743388,0.00611567) , 
0, 124.066, 1, 0, 0.350063,0.012268) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.926802,0.0104962) , 
0, 152.986, 1, 0, 0.5,0.0202642)    );
  // itree = 83
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402441,0.008067) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.167403,-0.00747861) , 
17, 137.647, 1, 0, 0.278464,0.0382977) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.101695,-0.0308633) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.341582,0.00173257) , 
5, 2.04721, 1, 0, 0.308513,0.00325993) , 
6, 2.21689, 1, 0, 0.301868,0.0110083) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.00816831) , 
7, 122.218, 1, 0, 0.5,0.0195054)    );
  // itree = 84
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.155887,0.00351493) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.243472,-0.0132476) , 
7, 76.3834, 1, 0, 0.174523,-0.0019797) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.801356,0.00519342) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.384195,0.000479968) , 
10, 1.27019, 1, 0, 0.5432,0.027176) , 
0, 100.932, 1, 0, 0.350063,0.0119023) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.926802,0.0101105) , 
0, 152.986, 1, 0, 0.5,0.0193098)    );
  // itree = 85
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.77412,0.008538) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601396,0.00310552) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.790261,0.00686764) , 
11, 0.419335, 1, 0, 0.655997,0.0334316) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.238793,0.00228331) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.256713,-0.0122058) , 
9, 300.049, 1, 0, 0.247576,-0.00681118) , 
10, 1.52811, 1, 0, 0.458388,0.0139607) , 
15, 0.748823, 1, 0, 0.5,0.0187637)    );
  // itree = 86
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.267877,0.00221851) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.234526,-0.00403552) , 
8, 129.833, 1, 0, 0.256044,0.00420933) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.743388,0.00582345) , 
0, 124.066, 1, 0, 0.350063,0.0112874) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.926802,0.00985269) , 
0, 152.986, 1, 0, 0.5,0.0183887)    );
  // itree = 87
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612519,0.00943031) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.467339,-0.00058156) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.797599,0.00839398) , 
8, 164.741, 1, 0, 0.619589,0.01862) , 
6, 2.21764, 1, 0, 0.618551,0.0305459) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.302438,-0.00293201) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.512052,0.00511038) , 
5, 2.12533, 1, 0, 0.432442,0.0127003) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.0562818,-0.0464694) , 
12, 0.855897, 1, 0, 0.395641,0.00648298) , 
14, 0.952372, 1, 0, 0.5,0.0177484)    );
  // itree = 88
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.081758,-0.0270593) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.242301,0.0114665) , 
11, 0.433699, 1, 0, 0.132579,0.0145242) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.135593,-0.0360707) , 
11, 0.531979, 1, 0, 0.133211,-0.00196164) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.817048,0.00822811) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.518014,-0.000188433) , 
15, 1.26928, 1, 0, 0.742598,0.0439106) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.749482,0.00378548) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.216877,-0.0112718) , 
10, 1.52811, 1, 0, 0.548415,0.0104192) , 
3, 0.679989, 1, 0, 0.6283,0.0241972) , 
0, 92.257, 1, 0, 0.5,0.0174183)    );
  // itree = 89
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.640138,0.00547703) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.400036,0.000990055) , 
14, 0.952372, 1, 0, 0.503676,0.0184061) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.628973,0.00918215) , 
6, 3.09209, 1, 0, 0.514054,0.0231491) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.775841,0.00783829) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.292428,-0.00346711) , 
10, 1.55464, 1, 0, 0.521681,0.0121967) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.231941,-0.0465573) , 
17, 178.538, 1, 0, 0.425491,-0.00839717) , 
6, 3.17166, 1, 0, 0.5,0.018143)    );
  // itree = 90
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.485973,0.00579689) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.366327,0.00193387) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.121474,-0.0164219) , 
10, 2.51053, 1, 0, 0.336269,0.00710335) , 
4, 0.149637, 1, 0, 0.350063,0.0113648) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.926802,0.00946553) , 
0, 152.986, 1, 0, 0.5,0.0177276)    );
  // itree = 91
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.77412,0.00771049) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.601396,0.00273453) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.790261,0.00635977) , 
11, 0.419335, 1, 0, 0.655997,0.0297956) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.238793,0.00234187) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.256713,-0.0106125) , 
9, 300.049, 1, 0, 0.247576,-0.00477289) , 
10, 1.52811, 1, 0, 0.458388,0.0130701) , 
15, 0.748823, 1, 0, 0.5,0.0171828)    );
  // itree = 92
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39508,0.00383486) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.281806,-0.0031481) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.246933,-0.0127937) , 
4, 0.897564, 1, 0, 0.264389,-0.029234) , 
6, 1.97614, 1, 0, 0.324186,-0.00309397) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.898853,0.00807084) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.396326,0.00297176) , 
12, 0.373098, 1, 0, 0.577098,0.0290497) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.449977,-0.0285053) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.374324,0.00315875) , 
13, 0.108405, 1, 0, 0.407758,-0.0115266) , 
6, 3.23089, 1, 0, 0.549331,0.0223965) , 
5, 1.96904, 1, 0, 0.5,0.0168113)    );
  // itree = 93
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.449825,0.00952926) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.188985,-0.000473681) , 
14, 1.04761, 1, 0, 0.278464,0.0374517) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.336407,-0.0019271) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.252392,0.00482906) , 
14, 1.42856, 1, 0, 0.308513,0.00157589) , 
6, 2.21689, 1, 0, 0.301868,0.00950955) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.00726144) , 
7, 122.218, 1, 0, 0.5,0.0163927)    );
  // itree = 94
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.45545,0.000861401) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.794979,0.00940911) , 
8, 143.321, 1, 0, 0.678233,0.0384833) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.427265,-0.00852882) , 
16, 155.491, 1, 0, 0.63759,0.0287228) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.616032,0.0100519) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.356085,-0.00578663) , 
13, 0.0994451, 1, 0, 0.407907,-0.00902032) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.462732,0.0102824) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.395786,0.000572453) , 
4, 0.943463, 1, 0, 0.410024,0.0224842) , 
4, 0.833538, 1, 0, 0.409015,0.00746989) , 
4, 0.448832, 1, 0, 0.5,0.0159297)    );
  // itree = 95
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.39508,0.00350207) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.281806,-0.00319598) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.246933,-0.0122861) , 
4, 0.897564, 1, 0, 0.264389,-0.0284228) , 
6, 1.97614, 1, 0, 0.324186,-0.00379344) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.898853,0.00777041) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.396326,0.00273308) , 
12, 0.373098, 1, 0, 0.577098,0.0271724) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.449977,-0.0253903) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.374324,0.00286999) , 
13, 0.108405, 1, 0, 0.407758,-0.0105511) , 
6, 3.23089, 1, 0, 0.549331,0.0209869) , 
5, 1.96904, 1, 0, 0.5,0.0155573)    );
  // itree = 96
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.245717,-0.00100951) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.292592,0.00310088) , 
13, 0.175736, 1, 0, 0.256044,0.00282213) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.743388,0.00523902) , 
0, 124.066, 1, 0, 0.350063,0.00905926) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.926802,0.0089537) , 
0, 152.986, 1, 0, 0.5,0.0151651)    );
  // itree = 97
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402441,0.00728853) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.167403,-0.00644699) , 
17, 137.647, 1, 0, 0.278464,0.0354034) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.336407,-0.00211209) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.252392,0.00446482) , 
14, 1.42856, 1, 0, 0.308513,0.000256461) , 
6, 2.21689, 1, 0, 0.301868,0.00802894) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.00689165) , 
7, 122.218, 1, 0, 0.5,0.0146048)    );
  // itree = 98
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.612519,0.0085294) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.467339,-0.00118133) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.797599,0.00742478) , 
8, 164.741, 1, 0, 0.619589,0.0137426) , 
6, 2.21764, 1, 0, 0.618551,0.0249286) , 
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.111477,-0.00390693) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.650081,-0.00368487) , 
7, 93.6965, 1, 0, 0.270214,-0.0157005) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.518181,-0.000499189) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.433434,0.00599203) , 
14, 1.45124, 1, 0, 0.475736,0.018158) , 
5, 2.12533, 1, 0, 0.395641,0.0049629) , 
14, 0.952372, 1, 0, 0.5,0.0143101)    );
  // itree = 99
  fBoostWeights.push_back(1);
  fForest.push_back( 
NN(
NN(
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.402441,0.0070188) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.167403,-0.00585697) , 
17, 137.647, 1, 0, 0.278464,0.0346153) , 
NN(
NN(
0, 
0, 
-1, 0, 1, -99, 0.336407,-0.00203368) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.252392,0.00407848) , 
14, 1.42856, 1, 0, 0.308513,-0.000151182) , 
6, 2.21689, 1, 0, 0.301868,0.00753716) , 
NN(
0, 
0, 
-1, 0, 1, -99, 0.958405,0.00670184) , 
7, 122.218, 1, 0, 0.5,0.0138892)    );
   return;
};
 
// Clean up
inline void Read2HDMaVWjetsSR_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_18Var::Clear() 
{
   for (unsigned int itree=0; itree<fForest.size(); itree++) { 
      delete fForest[itree]; 
   }
}
   inline double Read2HDMaVWjetsSR_2017_BDT_100Trees_Grad_FalseBagged_0.6BagFrac_1BagShrink_GiniIndex_20Cuts_CostComplexity_12PruneStrength_18Var::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
